/**
 * Injury module test cases — TC-INJ-01 ~ TC-INJ-09
 * Scope: injury claim submission, approval flow, proxy entry, claim entry, validation, permission
 */
import type { TestCase } from '../../../../tools/autotest/runner/types.js';
import { loginSteps, USERS } from '../_helpers.js';

const cases: TestCase[] = [
  {
    id: 'TC-INJ-01',
    title: '劳工自主提交工伤申报（含受伤部位/原因/附件）',
    description: '角色：worker。路径：登录 → /injury → 发起申报 → 填写受伤日期/伤情描述/上传附件 → 提交。期望：提示“工伤申报已提交，等待审批”并列表出现新记录。',
    module: 'injury',
    priority: 'P1',
    roles: ['worker'],
    credentials: USERS.worker,
    steps: [
      ...loginSteps(USERS.worker.username, USERS.worker.password),
      { id: 6, desc: '访问 /injury', action: 'navigate', to: '/injury' },
      { id: 7, desc: '点击“发起申报”', action: 'click', locator: { by: 'catch', value: 'injury-apply-btn' } },
      { id: 8, desc: '选择受伤日期', action: 'fill', locator: { by: 'label', value: '受伤日期' }, value: '2024-01-15' },
      { id: 9, desc: '填写伤情描述', action: 'fill', locator: { by: 'label', value: '伤情描述' }, value: '手指被机器压伤，流血不止' },
      { id: 10, desc: '上传附件', action: 'upload', locator: { by: 'catch', value: 'injury-file-upload' }, value: 'test-injury.jpg' },
      { id: 11, desc: '点击提交', action: 'click', locator: { by: 'catch', value: 'injury-apply-modal-submit' } },
      { id: 12, desc: '出现提交成功提示', action: 'assert', check: { type: 'toast_contains', value: '工伤申报已提交，等待审批' } },
      { id: 13, desc: '列表出现待审批记录', action: 'assert', check: { type: 'text_visible', value: '待审批' } },
    ],
    expect: { result: 'pass', url: '/injury' },
  },
  {
    id: 'TC-INJ-02',
    title: 'PM 在待办收到工伤申报通知',
    description: '角色：pm。路径：登录 → /todo。期望：待办列表中出现工伤申报待审批通知。',
    module: 'injury',
    priority: 'P1',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问 /todo', action: 'navigate', to: '/todo' },
      { id: 7, desc: '待办列表应显示工伤申报通知', action: 'assert', check: { type: 'text_visible', value: '工伤申报' } },
    ],
    expect: { result: 'pass', url: '/todo' },
  },
  {
    id: 'TC-INJ-03',
    title: 'PM 提交者触发 skipCondition，直接进入 CEO 审批节点',
    description: '角色：pm。路径：登录 → /injury → 发起申报 → 填写并提交 → 查询审批流状态。期望：该单据跳过 PM 审批，直接到达 CEO 节点。',
    module: 'injury',
    priority: 'P1',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问 /injury', action: 'navigate', to: '/injury' },
      { id: 7, desc: '点击“发起申报”', action: 'click', locator: { by: 'catch', value: 'injury-apply-btn' } },
      { id: 8, desc: '选择受伤日期', action: 'fill', locator: { by: 'label', value: '受伤日期' }, value: '2024-01-15' },
      { id: 9, desc: '填写伤情描述', action: 'fill', locator: { by: 'label', value: '伤情描述' }, value: 'PM代录测试-跳过本节点' },
      { id: 10, desc: '点击提交', action: 'click', locator: { by: 'catch', value: 'injury-apply-modal-submit' } },
      { id: 11, desc: '调用 API 查询审批节点状态', action: 'api_call', method: 'GET', endpoint: '/api/logs/records' },
      { id: 12, desc: '人工核对单据处于 CEO 审批节点', action: 'screenshot', label: 'injury-skip-ceo-node' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-INJ-04',
    title: 'CEO 审批通过工伤申报，状态变 APPROVED',
    description: '角色：ceo。路径：登录 → /approval → 找到待审批工伤申报 → 点击通过。期望：状态变为“已通过”。',
    module: 'injury',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /approval', action: 'navigate', to: '/approval' },
      { id: 7, desc: '点击工伤申报“通过”按钮', action: 'click', locator: { by: 'catch', value: 'injury-approve-btn' } },
      { id: 8, desc: '确认审批通过', action: 'click', locator: { by: 'catch', value: 'injury-approve-modal-ok' } },
      { id: 9, desc: '出现审批成功提示', action: 'assert', check: { type: 'toast_contains', value: '审批通过' } },
      { id: 10, desc: '状态显示为“已通过”', action: 'assert', check: { type: 'text_visible', value: '已通过' } },
    ],
    expect: { result: 'pass', url: '/approval' },
  },
  {
    id: 'TC-INJ-05',
    title: 'PM 代录工伤申报（第二角色）',
    description: '角色：pm。路径：登录 → /injury → 发起申报 → 选择代录员工 → 填写并提交。期望：代录成功，列表出现该员工申报记录。',
    module: 'injury',
    priority: 'P2',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问 /injury', action: 'navigate', to: '/injury' },
      { id: 7, desc: '点击“发起申报”', action: 'click', locator: { by: 'catch', value: 'injury-apply-btn' } },
      { id: 8, desc: '选择代录员工', action: 'fill', locator: { by: 'catch', value: 'injury-proxy-select' }, value: 'worker.demo' },
      { id: 9, desc: '选择受伤日期', action: 'fill', locator: { by: 'label', value: '受伤日期' }, value: '2024-01-15' },
      { id: 10, desc: '填写伤情描述', action: 'fill', locator: { by: 'label', value: '伤情描述' }, value: '工长代录工伤申报测试' },
      { id: 11, desc: '点击提交', action: 'click', locator: { by: 'catch', value: 'injury-apply-modal-submit' } },
      { id: 12, desc: '出现提交成功提示', action: 'assert', check: { type: 'toast_contains', value: '工伤申报已提交，等待审批' } },
    ],
    expect: { result: 'pass', url: '/injury' },
  },
  {
    id: 'TC-INJ-06',
    title: '审批通过后 finance 可录入工伤理赔信息',
    description: '角色：finance。路径：登录 → /injury → 录入理赔 → 填写申报单ID/员工ID/金额 → 提交。期望：提示“理赔已录入”。',
    module: 'injury',
    priority: 'P2',
    roles: ['finance'],
    credentials: USERS.finance,
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      { id: 6, desc: '访问 /injury', action: 'navigate', to: '/injury' },
      { id: 7, desc: '点击“录入理赔”', action: 'click', locator: { by: 'catch', value: 'injury-claim-btn' } },
      { id: 8, desc: '填写关联申报单 ID', action: 'fill', locator: { by: 'label', value: '关联申报单 ID' }, value: '1' },
      { id: 9, desc: '填写员工 ID', action: 'fill', locator: { by: 'label', value: '员工 ID' }, value: '1' },
      { id: 10, desc: '选择受伤日期', action: 'fill', locator: { by: 'label', value: '受伤日期' }, value: '2024-01-15' },
      { id: 11, desc: '填写理赔金额', action: 'fill', locator: { by: 'label', value: '理赔金额（元）' }, value: '5000.00' },
      { id: 12, desc: '点击提交理赔', action: 'click', locator: { by: 'catch', value: 'injury-claim-modal-submit' } },
      { id: 13, desc: '出现录入成功提示', action: 'assert', check: { type: 'toast_contains', value: '理赔已录入' } },
    ],
    expect: { result: 'pass', url: '/injury' },
  },
  {
    id: 'TC-INJ-07',
    title: '必填字段（伤情描述）为空提交',
    description: '角色：worker。路径：登录 → /injury → 发起申报 → 不填伤情描述 → 提交。期望：出现“请填写伤情描述”校验提示。',
    module: 'injury',
    priority: 'P1',
    roles: ['worker'],
    credentials: USERS.worker,
    steps: [
      ...loginSteps(USERS.worker.username, USERS.worker.password),
      { id: 6, desc: '访问 /injury', action: 'navigate', to: '/injury' },
      { id: 7, desc: '点击“发起申报”', action: 'click', locator: { by: 'catch', value: 'injury-apply-btn' } },
      { id: 8, desc: '选择受伤日期', action: 'fill', locator: { by: 'label', value: '受伤日期' }, value: '2024-01-15' },
      { id: 9, desc: '留空伤情描述并点击提交', action: 'click', locator: { by: 'catch', value: 'injury-apply-modal-submit' } },
      { id: 10, desc: '出现必填校验提示', action: 'assert', check: { type: 'toast_contains', value: '请填写伤情描述' } },
    ],
    expect: { result: 'pass', url: '/injury' },
  },
  {
    id: 'TC-INJ-08',
    title: '上传不支持的附件格式',
    description: '角色：worker。路径：登录 → /injury → 发起申报 → 上传 .exe 附件。期望：提示格式不支持。',
    module: 'injury',
    priority: 'P2',
    roles: ['worker'],
    credentials: USERS.worker,
    steps: [
      ...loginSteps(USERS.worker.username, USERS.worker.password),
      { id: 6, desc: '访问 /injury', action: 'navigate', to: '/injury' },
      { id: 7, desc: '点击“发起申报”', action: 'click', locator: { by: 'catch', value: 'injury-apply-btn' } },
      { id: 8, desc: '上传不支持的附件格式', action: 'upload', locator: { by: 'catch', value: 'injury-file-upload' }, value: 'malicious.exe' },
      { id: 9, desc: '出现格式不支持提示', action: 'assert', check: { type: 'toast_contains', value: '格式不支持' } },
    ],
    expect: { result: 'pass', url: '/injury' },
  },
  {
    id: 'TC-INJ-09',
    title: '员工（非劳工）尝试提交工伤申报',
    description: '角色：employee。路径：登录 → /injury。期望：无“发起申报”按钮或页面被重定向。',
    module: 'injury',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    tags: ['permission'],
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /injury', action: 'navigate', to: '/injury' },
      { id: 7, desc: '不应显示“发起申报”按钮', action: 'assert', check: { type: 'text_absent', value: '发起申报' } },
    ],
    expect: { result: 'pass' },
  },
];

export default cases;
