/**
 * Leave module test cases — TC-LVE-01 ~ TC-LVE-14
 * Scope: leave request submit, approval, view history, validation, concurrency
 */
import type { TestCase } from '../../../../tools/autotest/runner/types.js';
import { loginSteps, USERS } from '../_helpers.js';

const cases: TestCase[] = [
  {
    id: 'TC-LVE-01',
    title: '员工提交请假申请',
    description: '角色：Employee。路径：/attendance → 请假申请 tab → 填写假种/日期/原因 → 提交。期望：状态变为 PENDING，列表可见。',
    module: 'leave',
    priority: 'P0',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问考勤页', action: 'navigate', to: '/attendance' },
      { id: 7, desc: '切换到请假申请 tab', action: 'click', locator: { by: 'role', role: 'tab', name: '请假申请' } },
      { id: 8, desc: '选择假种下拉', action: 'click', locator: { by: 'label', value: '假种' } },
      { id: 9, desc: '选择"事假"', action: 'click', locator: { by: 'text', value: '事假', exact: true } },
      { id: 10, desc: '选择开始日期', action: 'click', locator: { by: 'label', value: '开始日期' } },
      { id: 11, desc: '使用 catch 定位日期选择"今天"', action: 'click', locator: { by: 'catch', value: 'datepicker-today' } },
      { id: 12, desc: '选择结束日期', action: 'click', locator: { by: 'label', value: '结束日期' } },
      { id: 13, desc: '使用 catch 定位日期选择"今天"', action: 'click', locator: { by: 'catch', value: 'datepicker-today' } },
      { id: 14, desc: '输入请假原因', action: 'fill', locator: { by: 'label', value: '请假原因' }, value: '自动化测试请假' },
      { id: 15, desc: '点击提交申请', action: 'click', locator: { by: 'catch', value: 'leave-form-submit' } },
      { id: 16, desc: '出现提交成功提示', action: 'assert', check: { type: 'toast_contains', value: '提交成功' } },
    ],
    expect: { result: 'pass', url: '/attendance' },
  },
  {
    id: 'TC-LVE-02',
    title: 'PM 在待办列表看到员工请假',
    description: '角色：PM。路径：登录 → /todo。期望：待办列表包含刚提交的请假审批项。',
    module: 'leave',
    priority: 'P0',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问 /todo', action: 'navigate', to: '/todo' },
      { id: 7, desc: '待办页标题可见', action: 'assert', check: { type: 'text_visible', value: '待办' } },
      { id: 8, desc: '列表应包含"请假"字样', action: 'assert', check: { type: 'text_visible', value: '请假' } },
    ],
    expect: { result: 'pass', url: '/todo' },
  },
  {
    id: 'TC-LVE-03',
    title: 'PM 审批通过请假',
    description: '角色：PM。路径：/todo → 点击待办项 → 通过。期望：状态变为 APPROVED，申请人收到通知。',
    module: 'leave',
    priority: 'P0',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问 /todo', action: 'navigate', to: '/todo' },
      { id: 7, desc: '点击某待办项详情', action: 'click', locator: { by: 'catch', value: 'todo-row-detail-btn-leave' } },
      { id: 8, desc: '点击"通过"按钮', action: 'click', locator: { by: 'catch', value: 'approval-approve-btn' } },
      { id: 9, desc: '输入审批意见', action: 'fill', locator: { by: 'label', value: '审批意见' }, value: '同意' },
      { id: 10, desc: '确认', action: 'click', locator: { by: 'catch', value: 'approval-confirm-btn' } },
      { id: 11, desc: '出现成功提示', action: 'assert', check: { type: 'toast_contains', value: '审批通过' } },
    ],
    expect: { result: 'pass', url: '/todo' },
  },
  {
    id: 'TC-LVE-04',
    title: 'PM 驳回请假',
    description: '角色：PM。路径：/todo → 待办项 → 驳回 → 填意见。期望：状态变为 REJECTED，申请人收驳回通知。',
    module: 'leave',
    priority: 'P0',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问 /todo', action: 'navigate', to: '/todo' },
      { id: 7, desc: '点击某待办项详情', action: 'click', locator: { by: 'catch', value: 'todo-row-detail-btn-leave2' } },
      { id: 8, desc: '点击"驳回"按钮', action: 'click', locator: { by: 'catch', value: 'approval-reject-btn' } },
      { id: 9, desc: '填写驳回原因', action: 'fill', locator: { by: 'label', value: '审批意见' }, value: '材料不完整' },
      { id: 10, desc: '确认驳回', action: 'click', locator: { by: 'catch', value: 'approval-confirm-btn' } },
      { id: 11, desc: '出现驳回提示', action: 'assert', check: { type: 'toast_contains', value: '已驳回' } },
    ],
    expect: { result: 'pass', url: '/todo' },
  },
  {
    id: 'TC-LVE-05',
    title: '员工查看"我的请假记录"',
    description: '角色：Employee。路径：/attendance → "我的记录" tab。期望：显示历史请假列表，含状态列（审批中/已通过/已驳回）。',
    module: 'leave',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /attendance', action: 'navigate', to: '/attendance' },
      { id: 7, desc: '切换到"我的记录"', action: 'click', locator: { by: 'role', role: 'tab', name: '我的记录' } },
      { id: 8, desc: '表格/列表可见', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'attendance-records-table' } } },
    ],
    expect: { result: 'pass', url: '/attendance' },
  },
  {
    id: 'TC-LVE-06',
    title: '劳工提交请假 PM 审批通过',
    description: '角色：Worker → PM。路径：worker 提交请假 → pm 审批通过。期望：状态 APPROVED。',
    module: 'leave',
    priority: 'P1',
    roles: ['worker', 'pm'],
    credentials: USERS.worker,
    steps: [
      ...loginSteps(USERS.worker.username, USERS.worker.password),
      { id: 6, desc: '访问 /attendance', action: 'navigate', to: '/attendance' },
      { id: 7, desc: '切换到请假申请', action: 'click', locator: { by: 'role', role: 'tab', name: '请假申请' } },
      { id: 8, desc: '选择假种', action: 'click', locator: { by: 'label', value: '假种' } },
      { id: 9, desc: '选择"事假"', action: 'click', locator: { by: 'text', value: '事假', exact: true } },
      { id: 10, desc: '输入原因', action: 'fill', locator: { by: 'label', value: '请假原因' }, value: '劳工请假测试' },
      { id: 11, desc: '截图保存（日期手工选）', action: 'screenshot', label: 'worker-leave-form' },
      { id: 12, desc: '提交', action: 'click', locator: { by: 'catch', value: 'leave-form-submit' } },
      { id: 13, desc: '出现提交成功', action: 'assert', check: { type: 'toast_contains', value: '提交' } },
    ],
    expect: { result: 'pass', url: '/attendance' },
  },
  {
    id: 'TC-LVE-07',
    title: 'CEO 查看全体请假记录',
    description: '角色：CEO。路径：调 GET /api/leave/records?all=true 或访问管理页。期望：返回所有员工请假记录。',
    module: 'leave',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    tags: ['api-only'],
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '调用 GET /api/leave/records', action: 'api_call', method: 'GET', endpoint: '/api/leave/records?scope=all' },
      { id: 7, desc: '截图记录', action: 'screenshot', label: 'ceo-all-leave-records' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-LVE-08',
    title: '结束时间早于开始时间校验失败',
    description: '角色：Employee。路径：请假申请表单填写倒序时间 → 提交。期望：表单校验报错，不提交。',
    module: 'leave',
    priority: 'P0',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /attendance', action: 'navigate', to: '/attendance' },
      { id: 7, desc: '切到请假申请', action: 'click', locator: { by: 'role', role: 'tab', name: '请假申请' } },
      { id: 8, desc: '选择假种', action: 'click', locator: { by: 'label', value: '假种' } },
      { id: 9, desc: '选择"事假"', action: 'click', locator: { by: 'text', value: '事假', exact: true } },
      { id: 10, desc: '手动输入原因', action: 'fill', locator: { by: 'label', value: '请假原因' }, value: '倒序时间测试' },
      { id: 11, desc: '通过 catch 设置倒序日期（开始 2026-05-10，结束 2026-05-05）', action: 'screenshot', label: 'inverted-dates' },
      { id: 12, desc: '提交', action: 'click', locator: { by: 'catch', value: 'leave-form-submit' } },
      { id: 13, desc: '应出现校验错误或后端拒绝', action: 'assert', check: { type: 'text_visible', value: '日期' } },
    ],
    expect: { result: 'pass', url: '/attendance' },
  },
  {
    id: 'TC-LVE-09',
    title: '开始时间为空触发校验',
    description: '角色：Employee。路径：请假表单 → 不填开始日期 → 提交。期望：表单校验报错"请选择开始日期"。',
    module: 'leave',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /attendance', action: 'navigate', to: '/attendance' },
      { id: 7, desc: '切到请假申请', action: 'click', locator: { by: 'role', role: 'tab', name: '请假申请' } },
      { id: 8, desc: '不填任何字段直接提交', action: 'click', locator: { by: 'catch', value: 'leave-form-submit' } },
      { id: 9, desc: '出现"请选择开始日期"校验', action: 'assert', check: { type: 'text_visible', value: '请选择开始日期' } },
    ],
    expect: { result: 'pass', url: '/attendance' },
  },
  {
    id: 'TC-LVE-10',
    title: '超出年假配额触发提示',
    description: '角色：Employee。路径：请假表单 → 输入超大天数（如年假 100 天）→ 提交。期望：后端返回余额不足或超限。',
    module: 'leave',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '通过 API 直接提交超大天数', action: 'api_call', method: 'POST', endpoint: '/api/leave', body: { leaveType: 'ANNUAL', startDate: '2026-05-01', endDate: '2026-09-01', reason: '超配额测试' } },
      { id: 7, desc: '截图记录响应', action: 'screenshot', label: 'quota-exceeded' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-LVE-11',
    title: 'CEO 审批自己的请假',
    description: '角色：CEO。路径：CEO 提交请假 → 检查审批流路由。期望：审批链不应由 CEO 自己审批（按业务规则应 fallback 或跳过）。',
    module: 'leave',
    priority: 'P2',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: 'CEO 提交请假（API）', action: 'api_call', method: 'POST', endpoint: '/api/leave', body: { leaveType: 'PERSONAL', startDate: '2026-05-01', endDate: '2026-05-02', reason: 'CEO 请假自审测试' } },
      { id: 7, desc: '查询审批流状态', action: 'api_call', method: 'GET', endpoint: '/api/approval/my-submitted' },
      { id: 8, desc: '截图记录', action: 'screenshot', label: 'ceo-self-approval' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-LVE-12',
    title: '请假原因超长处理',
    description: '角色：Employee。路径：API 提交 500+ 字原因。期望：或被截断或校验提示。',
    module: 'leave',
    priority: 'P2',
    roles: ['employee'],
    credentials: USERS.employee,
    tags: ['edge-case'],
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '通过 API 提交超长原因', action: 'api_call', method: 'POST', endpoint: '/api/leave', body: { leaveType: 'PERSONAL', startDate: '2026-05-03', endDate: '2026-05-04', reason: 'X'.repeat(600) } },
      { id: 7, desc: '截图记录响应', action: 'screenshot', label: 'long-reason' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-LVE-13',
    title: 'PM 和 CEO 并发审批同一请假',
    description: '并发场景。路径：parallel PM 和 CEO 同时审批同一申请。期望：后者收到"已处理"提示，只有一次状态变更。',
    module: 'leave',
    priority: 'P1',
    roles: ['pm', 'ceo'],
    tags: ['concurrency'],
    steps: [
      {
        id: 1,
        desc: '并行 PM 与 CEO 审批同一单',
        action: 'parallel',
        contexts: [
          [
            ...loginSteps(USERS.pm.username, USERS.pm.password, 1),
            { id: 6, desc: 'PM 通过审批', action: 'api_call', method: 'POST', endpoint: '/api/approval/leave/1/approve', body: { comment: 'PM 同意' } },
          ],
          [
            ...loginSteps(USERS.ceo.username, USERS.ceo.password, 1),
            { id: 6, desc: 'CEO 通过审批', action: 'api_call', method: 'POST', endpoint: '/api/approval/leave/1/approve', body: { comment: 'CEO 同意' } },
          ],
        ],
      },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-LVE-14',
    title: '两名员工并发提交请假',
    description: '并发场景。路径：parallel employee 和 worker 同时提交请假。期望：各自成功、各自出现在列表中。',
    module: 'leave',
    priority: 'P2',
    roles: ['employee', 'worker'],
    tags: ['concurrency'],
    steps: [
      {
        id: 1,
        desc: '并行提交请假',
        action: 'parallel',
        contexts: [
          [
            ...loginSteps(USERS.employee.username, USERS.employee.password, 1),
            { id: 6, desc: 'Employee API 提交', action: 'api_call', method: 'POST', endpoint: '/api/leave', body: { leaveType: 'PERSONAL', startDate: '2026-05-10', endDate: '2026-05-10', reason: '并发 A' } },
          ],
          [
            ...loginSteps(USERS.worker.username, USERS.worker.password, 1),
            { id: 6, desc: 'Worker API 提交', action: 'api_call', method: 'POST', endpoint: '/api/leave', body: { leaveType: 'PERSONAL', startDate: '2026-05-10', endDate: '2026-05-10', reason: '并发 B' } },
          ],
        ],
      },
    ],
    expect: { result: 'pass' },
  },
];

export default cases;
