/**
 * Directory module test cases — TC-DIR-01 ~ TC-DIR-07
 * Scope: CSV import preview, import apply, result, error handling, permission
 */
import type { TestCase } from '../../../../tools/autotest/runner/types.js';
import { loginSteps, USERS } from '../_helpers.js';

const cases: TestCase[] = [
  {
    id: 'TC-DIR-01',
    title: '粘贴合法 CSV，预览界面展示字段和行数',
    description: '角色：HR。路径：登录 → /directory → 粘贴合法 CSV → 点击下一步。期望：预览页展示字段映射、数据行数及统计卡片。',
    module: 'directory',
    priority: 'P0',
    roles: ['hr'],
    credentials: USERS.hr,
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '访问 /directory', action: 'navigate', to: '/directory' },
      { id: 7, desc: '页面标题"通讯录导入"可见', action: 'assert', check: { type: 'text_visible', value: '通讯录导入' } },
      { id: 8, desc: '在 CSV 输入框粘贴合法数据', action: 'fill', locator: { by: 'catch', value: 'directory-textarea-csv' }, value: '张三,13800138000,工程部\n李四,13900139000,财务部' },
      { id: 9, desc: '点击"下一步"按钮', action: 'click', locator: { by: 'catch', value: 'directory-btn-next' } },
      { id: 10, desc: '预览页统计卡片"共计"可见', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'directory-stat-total' } } },
      { id: 11, desc: '预览表格展示姓名/手机号/部门列', action: 'assert', check: { type: 'text_visible', value: '姓名' } },
    ],
    expect: { result: 'pass', url: '/directory' },
  },
  {
    id: 'TC-DIR-02',
    title: '确认导入后展示导入结果（成功条数）',
    description: '角色：HR。路径：/directory → 预览确认 → 点击确认导入。期望：进入导入完成步骤，展示成功条数及成功提示。',
    module: 'directory',
    priority: 'P0',
    roles: ['hr'],
    credentials: USERS.hr,
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '访问 /directory', action: 'navigate', to: '/directory' },
      { id: 7, desc: '在 CSV 输入框粘贴合法数据', action: 'fill', locator: { by: 'catch', value: 'directory-textarea-csv' }, value: '王五,13700137000,技术部' },
      { id: 8, desc: '点击"下一步"按钮', action: 'click', locator: { by: 'catch', value: 'directory-btn-next' } },
      { id: 9, desc: '点击"确认导入"按钮', action: 'click', locator: { by: 'catch', value: 'directory-btn-import' } },
      { id: 10, desc: '显示导入成功结果页', action: 'assert', check: { type: 'text_visible', value: '导入成功' } },
    ],
    expect: { result: 'pass', url: '/directory' },
  },
  {
    id: 'TC-DIR-03',
    title: '导入后在员工列表中可查到新增人员',
    description: '角色：HR。路径：导入完成后 → 访问员工列表。期望：搜索新导入人员姓名，结果列表中出现该员工。',
    module: 'directory',
    priority: 'P0',
    roles: ['hr'],
    credentials: USERS.hr,
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '访问 /directory', action: 'navigate', to: '/directory' },
      { id: 7, desc: '在 CSV 输入框粘贴合法数据', action: 'fill', locator: { by: 'catch', value: 'directory-textarea-csv' }, value: '赵六,13600136000,市场部' },
      { id: 8, desc: '点击"下一步"按钮', action: 'click', locator: { by: 'catch', value: 'directory-btn-next' } },
      { id: 9, desc: '点击"确认导入"按钮', action: 'click', locator: { by: 'catch', value: 'directory-btn-import' } },
      { id: 10, desc: '访问员工列表页', action: 'navigate', to: '/employees' },
      { id: 11, desc: '列表中可查到"赵六"', action: 'assert', check: { type: 'text_visible', value: '赵六' } },
    ],
    expect: { result: 'pass', url: '/employees' },
  },
  {
    id: 'TC-DIR-04',
    title: 'CSV 格式错误（列数不匹配）',
    description: '角色：HR。路径：/directory → 粘贴列数不匹配的 CSV → 点击下一步。期望：预览页展示错误提示，不允许进入导入步骤。',
    module: 'directory',
    priority: 'P0',
    roles: ['hr'],
    credentials: USERS.hr,
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '访问 /directory', action: 'navigate', to: '/directory' },
      { id: 7, desc: '在 CSV 输入框粘贴格式错误数据（仅两列）', action: 'fill', locator: { by: 'catch', value: 'directory-textarea-csv' }, value: '张三,13800138000\n李四,13900139000' },
      { id: 8, desc: '点击"下一步"按钮', action: 'click', locator: { by: 'catch', value: 'directory-btn-next' } },
      { id: 9, desc: '预览页展示错误提示', action: 'assert', check: { type: 'text_visible', value: '无效' } },
      { id: 10, desc: '"确认导入"按钮不可点或不存在', action: 'assert', check: { type: 'element_hidden', locator: { by: 'catch', value: 'directory-btn-import' } } },
    ],
    expect: { result: 'pass', url: '/directory' },
  },
  {
    id: 'TC-DIR-05',
    title: 'CSV 含重复手机号',
    description: '角色：HR。路径：/directory → 粘贴含重复手机号的 CSV → 预览 → 确认导入。期望：导入结果报告中标注重复行，成功条数正确。',
    module: 'directory',
    priority: 'P1',
    roles: ['hr'],
    credentials: USERS.hr,
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '访问 /directory', action: 'navigate', to: '/directory' },
      { id: 7, desc: '在 CSV 输入框粘贴含重复手机号数据', action: 'fill', locator: { by: 'catch', value: 'directory-textarea-csv' }, value: '张三,13800138000,工程部\n李四,13800138000,财务部' },
      { id: 8, desc: '点击"下一步"按钮', action: 'click', locator: { by: 'catch', value: 'directory-btn-next' } },
      { id: 9, desc: '预览页统计卡片"重复"数量大于 0', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'directory-stat-duplicate' } } },
      { id: 10, desc: '点击"确认导入"按钮', action: 'click', locator: { by: 'catch', value: 'directory-btn-import' } },
      { id: 11, desc: '导入结果页显示成功条数', action: 'assert', check: { type: 'text_visible', value: '导入成功' } },
    ],
    expect: { result: 'pass', url: '/directory' },
  },
  {
    id: 'TC-DIR-06',
    title: 'CSV 内容为空',
    description: '角色：HR。路径：/directory → 不填写任何内容 → 点击下一步。期望：页面提示"内容为空"或"请输入 CSV 数据"。',
    module: 'directory',
    priority: 'P1',
    roles: ['hr'],
    credentials: USERS.hr,
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '访问 /directory', action: 'navigate', to: '/directory' },
      { id: 7, desc: '清空 CSV 输入框', action: 'fill', locator: { by: 'catch', value: 'directory-textarea-csv' }, value: '' },
      { id: 8, desc: '点击"下一步"按钮', action: 'click', locator: { by: 'catch', value: 'directory-btn-next' } },
      { id: 9, desc: '出现"内容为空"或类似提示', action: 'assert', check: { type: 'toast_contains', value: '请输入' } },
    ],
    expect: { result: 'pass', url: '/directory' },
  },
  {
    id: 'TC-DIR-07',
    title: '员工（非 HR/财务）访问通讯录导入页',
    description: '角色：employee。路径：登录后直接访问 /directory。期望：页面被重定向或侧边栏无"通讯录导入"入口，显示 403 或无权限提示。',
    module: 'directory',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    tags: ['permission'],
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '直接访问 /directory', action: 'navigate', to: '/directory' },
      { id: 7, desc: '侧边栏不应显示"通讯录导入"菜单', action: 'assert', check: { type: 'text_absent', value: '通讯录导入' } },
    ],
    expect: { result: 'pass' },
  },
];

export default cases;
