/**
 * ESLint flat config for oa-h5 (Nuxt 3 + TypeScript + Vue 3)
 *
 * Rule severity policy:
 * - error: structural/correctness issues that must be fixed (no free pass in CI)
 * - warn:  code quality signals (any, non-null assertion, jsdoc) — tracked but non-blocking
 *
 * All jsdoc rules are set to "warn" per project specification.
 *
 * Ref: eslint.org/docs/latest/use/configure/configuration-files
 */

import tsParser from '@typescript-eslint/parser'
import tsPlugin from '@typescript-eslint/eslint-plugin'
import vuePlugin from 'eslint-plugin-vue'
import vueParser from 'vue-eslint-parser'
import jsdocPlugin from 'eslint-plugin-jsdoc'

export default [
  // Ignore generated and build artifacts
  {
    ignores: [
      '.nuxt/**',
      '.output/**',
      'node_modules/**',
      'dist/**',
      // Generated by unplugin-vue-components — do not lint
      'components.d.ts',
    ],
  },

  // TypeScript source files (.ts only, not .vue)
  {
    files: ['**/*.ts'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
      jsdoc: jsdocPlugin,
    },
    rules: {
      // TypeScript quality rules — warn level (non-blocking)
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-non-null-assertion': 'warn',

      // JSDoc rules — all warn per project specification
      // Require JSDoc on exported functions and classes
      'jsdoc/require-jsdoc': [
        'warn',
        {
          require: {
            FunctionDeclaration: true,
            MethodDefinition: false,
            ClassDeclaration: false,
            ArrowFunctionExpression: false,
            FunctionExpression: false,
          },
          publicOnly: true,
        },
      ],
      'jsdoc/require-description': 'warn',
      'jsdoc/check-tag-names': 'warn',
      'jsdoc/check-types': 'warn',
    },
  },

  // Vue SFC files — use vue-eslint-parser as outer parser, TS parser for <script>
  {
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: tsParser,
        ecmaVersion: 'latest',
        sourceType: 'module',
        extraFileExtensions: ['.vue'],
      },
    },
    plugins: {
      vue: vuePlugin,
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      // Vue 3 essential rules
      ...vuePlugin.configs['vue3-essential'].rules,
      // Nuxt 3 uses file-based routing: index.vue, login.vue etc. are route files,
      // not component names — disable multi-word-component-names for pages/layouts/components
      'vue/multi-word-component-names': 'off',
      // vue/no-deprecated-filter fires on TypeScript union-type syntax `a | b` inside
      // v-bind expressions — this is a known false-positive in vue-eslint-parser <9.4
      'vue/no-deprecated-filter': 'off',
      // TypeScript rules applied inside <script> blocks
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-non-null-assertion': 'warn',
    },
  },
]
