sonar.organization=taozhuowei
sonar.projectKey=taozhuowei_boyuan-oa
sonar.projectName=Boyuan OA

sonar.sources=server/src/main/java,app/h5
sonar.tests=server/src/test/java,test

sonar.java.binaries=server/target/classes
sonar.coverage.jacoco.xmlReportPaths=server/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=app/h5/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/.nuxt/**,**/target/**,**/dist/**
