@echo off
chcp 65001 >nul

echo === Test 7: JWT payload verification ===
echo Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvYS1iYWNrZW5kIiwic3ViIjoiY2VvLmRlbW8iLCJ1c2VySWQiOjQsInJvbGUiOiJjZW8iLCJlbXBsb3llZVR5cGUiOiJPRkZJQ0UiLCJkaXNwbGF5TmFtZSI6IumXhOWgn-ankeadqe-_vSIsImlhdCI6MTc3NTIzNzIzOSwiZXhwIjoxNzc1MzIzNjM5fQ.vseb5Z-E_VpsgUvyWYw9vFrfWEK6urRhh3HLWmu20b8
echo.
echo Decoded payload (middle part):
echo eyJpc3MiOiJvYS1iYWNrZW5kIiwic3ViIjoiY2VvLmRlbW8iLCJ1c2VySWQiOjQsInJvbGUiOiJjZW8iLCJlbXBsb3llZVR5cGUiOiJPRkZJQ0UiLCJkaXNwbGF5TmFtZSI6IumXhOWgn-ankeadqe-_vSIsImlhdCI6MTc3NTIzNzIzOSwiZXhwIjoxNzc1MzIzNjM5fQ
echo.
echo Verified fields: userId=4, role=ceo, employeeType=OFFICE
echo.
