-- Flyway V1: Initial schema for Boyuan OA Platform

-- 用户表
CREATE TABLE IF NOT EXISTS sys_user (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20),
    wx_user_id VARCHAR(50),
    status INT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 角色表
CREATE TABLE IF NOT EXISTS sys_role (
    id BIGSERIAL PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL UNIQUE,
    role_name VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    status INT DEFAULT 1,
    is_system INT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- ============================================
-- 员工与组织
-- ============================================

-- 部门表
CREATE TABLE IF NOT EXISTS department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    name VARCHAR(100) NOT NULL,
    sort INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 岗位表
CREATE TABLE IF NOT EXISTS position (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_code VARCHAR(50) NOT NULL UNIQUE,
    position_name VARCHAR(100) NOT NULL,
    employee_category VARCHAR(20) NOT NULL CHECK(employee_category IN('OFFICE','LABOR')),
    default_role_code VARCHAR(50),
    supervisor_position_code VARCHAR(50),
    requires_construction_log BOOLEAN DEFAULT FALSE,
    has_performance_bonus BOOLEAN DEFAULT FALSE,
    base_salary DECIMAL(12,2),
    overtime_base_type VARCHAR(20) CHECK(overtime_base_type IN('BASE','TOTAL','CUSTOM')),
    overtime_base_amount DECIMAL(12,2),
    overtime_rate_weekday DECIMAL(4,2) DEFAULT 1.5,
    overtime_rate_weekend DECIMAL(4,2) DEFAULT 2.0,
    overtime_rate_holiday DECIMAL(4,2) DEFAULT 3.0,
    default_performance_bonus DECIMAL(12,2),
    annual_leave INT DEFAULT 0,
    leave_deduct_base_type VARCHAR(20) CHECK(leave_deduct_base_type IN('BASE','TOTAL','CUSTOM')),
    social_insurance_mode VARCHAR(20) CHECK(social_insurance_mode IN('COMPANY_PAID','MERGED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 岗位级别表
CREATE TABLE IF NOT EXISTS position_level (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_id BIGINT NOT NULL REFERENCES position(id),
    level_name VARCHAR(100) NOT NULL,
    level_order INT DEFAULT 0,
    base_salary_override DECIMAL(12,2),
    performance_bonus_override DECIMAL(12,2),
    annual_leave_override INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 社保项目表
CREATE TABLE IF NOT EXISTS social_insurance_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_id BIGINT NOT NULL REFERENCES position(id),
    name VARCHAR(100) NOT NULL,
    employee_rate DECIMAL(5,4),
    company_rate DECIMAL(5,4),
    is_enabled BOOLEAN DEFAULT TRUE,
    display_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 假期类型定义表
CREATE TABLE IF NOT EXISTS leave_type_def (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    deduction_rate DECIMAL(4,2) DEFAULT 1.0,
    is_enabled BOOLEAN DEFAULT TRUE,
    is_system BOOLEAN DEFAULT FALSE,
    display_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 员工表
CREATE TABLE IF NOT EXISTS employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_no VARCHAR(20) NOT NULL UNIQUE,
    password_hash VARCHAR(60),
    is_default_password BOOLEAN DEFAULT TRUE,
    name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) UNIQUE,
    email VARCHAR(100),
    position_id BIGINT,
    level_id BIGINT,
    role_code VARCHAR(50),
    employee_type VARCHAR(50),
    direct_supervisor_id BIGINT,
    department_id BIGINT,
    account_status VARCHAR(20) DEFAULT 'ACTIVE' CHECK(account_status IN('ACTIVE','DISABLED')),
    entry_date DATE,
    leave_date DATE,
    base_salary_override DECIMAL(12,2),
    performance_base_override DECIMAL(12,2),
    salary_override_note VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 项目表
CREATE TABLE IF NOT EXISTS project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE' CHECK(status IN('ACTIVE','CLOSED')),
    start_date DATE,
    actual_end_date DATE,
    log_cycle_days INT DEFAULT 1,
    log_report_cycle_days INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 项目成员表
CREATE TABLE IF NOT EXISTS project_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    role VARCHAR(20) DEFAULT 'MEMBER' CHECK(role IN('PM','MEMBER')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0,
    UNIQUE(project_id, employee_id)
);

-- ============================================
-- 权限
-- ============================================

-- 权限表
CREATE TABLE IF NOT EXISTS permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    description VARCHAR(200),
    is_enabled BOOLEAN DEFAULT TRUE,
    is_system BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 角色权限表（无逻辑删除）
CREATE TABLE IF NOT EXISTS role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL,
    permission_code VARCHAR(100) NOT NULL,
    data_scope VARCHAR(20) DEFAULT 'SELF' CHECK(data_scope IN('GLOBAL','PROJECT','SELF')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 审批与表单
-- ============================================

-- 表单类型定义表
CREATE TABLE IF NOT EXISTS form_type_def (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    is_enabled BOOLEAN DEFAULT TRUE,
    is_system BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 表单记录表
CREATE TABLE IF NOT EXISTS form_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_type VARCHAR(50) NOT NULL,
    submitter_id BIGINT REFERENCES employee(id),
    target_employee_id BIGINT REFERENCES employee(id),
    project_id BIGINT REFERENCES project(id),
    form_data TEXT,
    status VARCHAR(30) DEFAULT 'PENDING' CHECK(status IN('PENDING','APPROVING','APPROVED','REJECTED','ARCHIVED','RECALLED')),
    current_node_order INT DEFAULT 0,
    remark VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 审批流定义表
CREATE TABLE IF NOT EXISTS approval_flow_def (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_type VARCHAR(50) NOT NULL,
    version INT DEFAULT 1,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 审批流节点表
CREATE TABLE IF NOT EXISTS approval_flow_node (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flow_id BIGINT NOT NULL REFERENCES approval_flow_def(id),
    node_order INT NOT NULL,
    node_name VARCHAR(100) NOT NULL,
    approval_mode VARCHAR(30) DEFAULT 'SEQUENTIAL',
    approver_type VARCHAR(30) NOT NULL CHECK(approver_type IN('DIRECT_SUPERVISOR','ROLE','DESIGNATED')),
    approver_ref VARCHAR(200),
    skip_condition TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 审批记录表（无 deleted 字段）
CREATE TABLE IF NOT EXISTS approval_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT NOT NULL REFERENCES form_record(id),
    node_order INT NOT NULL,
    approver_id BIGINT REFERENCES employee(id),
    action VARCHAR(20) CHECK(action IN('APPROVE','REJECT','SKIP','RECALL')),
    comment VARCHAR(500),
    acted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 考勤
-- ============================================

-- 加班通知表
CREATE TABLE IF NOT EXISTS overtime_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES project(id),
    initiator_id BIGINT REFERENCES employee(id),
    overtime_date DATE NOT NULL,
    overtime_type VARCHAR(20) CHECK(overtime_type IN('WEEKDAY','WEEKEND','HOLIDAY')),
    content VARCHAR(500),
    status VARCHAR(20) DEFAULT 'NOTIFIED' CHECK(status IN('NOTIFIED','ARCHIVED','CLOSED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 加班响应表
CREATE TABLE IF NOT EXISTS overtime_response (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL REFERENCES overtime_notification(id),
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    accepted BOOLEAN DEFAULT TRUE,
    reject_reason VARCHAR(500),
    reject_approval_status VARCHAR(20) CHECK(reject_approval_status IN('PENDING','APPROVED','REJECTED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0,
    UNIQUE(notification_id, employee_id)
);

-- ============================================
-- 施工
-- ============================================

-- 工作项模板表
CREATE TABLE IF NOT EXISTS work_item_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    project_id BIGINT REFERENCES project(id),
    created_by BIGINT REFERENCES employee(id),
    items TEXT,
    derived_from BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 工作项模板明细表
CREATE TABLE IF NOT EXISTS work_item_template_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES work_item_template(id),
    name VARCHAR(100) NOT NULL,
    default_unit VARCHAR(20),
    display_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 项目里程碑表
CREATE TABLE IF NOT EXISTS project_milestone (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    name VARCHAR(200) NOT NULL,
    sort INT DEFAULT 0,
    actual_completion_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 项目进度日志表
CREATE TABLE IF NOT EXISTS project_progress_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    pm_id BIGINT REFERENCES employee(id),
    milestone_id BIGINT REFERENCES project_milestone(id),
    completed_at TIMESTAMP,
    note VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 施工日志汇总表
CREATE TABLE IF NOT EXISTS construction_log_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    pm_id BIGINT REFERENCES employee(id),
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    aggregated_items TEXT,
    worker_summary TEXT,
    viz_components TEXT,
    pm_note VARCHAR(2000),
    ceo_notified_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- ============================================
-- 薪资
-- ============================================

-- 薪资周期表
CREATE TABLE IF NOT EXISTS payroll_cycle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period VARCHAR(20) NOT NULL,
    settlement_type VARCHAR(20) DEFAULT 'MONTHLY',
    start_date DATE,
    end_date DATE,
    pay_date DATE,
    window_days INT DEFAULT 7,
    window_status VARCHAR(20) CHECK(window_status IN('OPEN','CLOSED')),
    window_start_date DATE,
    window_end_date DATE,
    status VARCHAR(30) DEFAULT 'OPEN' CHECK(status IN('OPEN','WINDOW_OPEN','WINDOW_CLOSED','SETTLED','LOCKED','CORRECTING')),
    locked_at TIMESTAMP,
    version INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 工资项定义表
CREATE TABLE IF NOT EXISTS payroll_item_def (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(20) NOT NULL CHECK(type IN('EARNING','DEDUCTION')),
    display_order INT DEFAULT 0,
    is_enabled BOOLEAN DEFAULT TRUE,
    is_system BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 工资条表
CREATE TABLE IF NOT EXISTS payroll_slip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT NOT NULL REFERENCES payroll_cycle(id),
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    version INT DEFAULT 1,
    status VARCHAR(20) DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PUBLISHED','CONFIRMED','DISPUTED','SUPERSEDED')),
    net_pay DECIMAL(12,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 工资条项目表（无 deleted 字段）
CREATE TABLE IF NOT EXISTS payroll_slip_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slip_id BIGINT NOT NULL REFERENCES payroll_slip(id),
    item_def_id BIGINT NOT NULL REFERENCES payroll_item_def(id),
    amount DECIMAL(12,2),
    remark VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 薪资等级表
CREATE TABLE IF NOT EXISTS salary_grade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_code VARCHAR(50) NOT NULL UNIQUE,
    grade_name VARCHAR(100) NOT NULL,
    min_salary DECIMAL(12,2),
    max_salary DECIMAL(12,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 薪资调整表
CREATE TABLE IF NOT EXISTS payroll_adjustment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT NOT NULL REFERENCES payroll_cycle(id),
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    initiator_id BIGINT REFERENCES employee(id),
    reason VARCHAR(500),
    status VARCHAR(20) DEFAULT 'PENDING' CHECK(status IN('PENDING','APPROVED','REJECTED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 薪资确认表（无 deleted 字段）
CREATE TABLE IF NOT EXISTS payroll_confirmation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slip_id BIGINT NOT NULL REFERENCES payroll_slip(id),
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    confirmed_at TIMESTAMP,
    client_ip VARCHAR(45),
    user_agent VARCHAR(500),
    payroll_content_hash VARCHAR(64),
    signature_hash VARCHAR(64),
    agreement_version VARCHAR(50),
    evidence_pdf_path VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 签名
-- ============================================

-- 员工签名表
CREATE TABLE IF NOT EXISTS employee_signature (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL UNIQUE REFERENCES employee(id),
    signature_image_encrypted TEXT,
    signature_hash VARCHAR(64),
    pin_hash VARCHAR(60),
    bound_at TIMESTAMP,
    last_agreement_version VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 薪资确认协议表
CREATE TABLE IF NOT EXISTS salary_confirmation_agreement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version VARCHAR(50) NOT NULL,
    file_path VARCHAR(500),
    content TEXT,
    uploaded_by BIGINT REFERENCES employee(id),
    is_active BOOLEAN DEFAULT FALSE,
    uploaded_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 工资条确认存证链表（审计记录，无 deleted 字段）
CREATE TABLE IF NOT EXISTS evidence_chain (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slip_id BIGINT NOT NULL REFERENCES payroll_slip(id),
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    content_hash VARCHAR(64) NOT NULL,
    confirmed_at TIMESTAMP,
    agreement_version VARCHAR(50),
    pdf_path VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 工伤
-- ============================================

-- 工伤申报表
CREATE TABLE IF NOT EXISTS injury_claim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT REFERENCES form_record(id),
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    injury_date DATE NOT NULL,
    injury_description VARCHAR(1000),
    compensation_amount DECIMAL(12,2),
    finance_note VARCHAR(500),
    status VARCHAR(20) DEFAULT 'PENDING' CHECK(status IN('PENDING','PROCESSING','SETTLED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- ============================================
-- 运维
-- ============================================

-- 附件元数据表（无 deleted 字段）
CREATE TABLE IF NOT EXISTS attachment_meta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_type VARCHAR(50),
    business_id BIGINT,
    file_name VARCHAR(255),
    storage_path VARCHAR(500),
    file_md5 VARCHAR(32),
    file_size BIGINT,
    mime_type VARCHAR(100),
    uploaded_by BIGINT REFERENCES employee(id),
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 操作日志表（无 deleted 字段）
CREATE TABLE IF NOT EXISTS operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id BIGINT REFERENCES employee(id),
    action VARCHAR(100),
    target_type VARCHAR(50),
    target_id BIGINT,
    detail TEXT,
    acted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 通知表
CREATE TABLE IF NOT EXISTS notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL REFERENCES employee(id),
    title VARCHAR(200) NOT NULL,
    content VARCHAR(1000),
    type VARCHAR(50),
    related_type VARCHAR(50),
    related_id BIGINT,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 保留策略表
CREATE TABLE IF NOT EXISTS retention_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_type VARCHAR(50) NOT NULL UNIQUE,
    retention_years INT DEFAULT 1,
    warn_before_days INT DEFAULT 30,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 保留提醒表
CREATE TABLE IF NOT EXISTS retention_reminder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id BIGINT NOT NULL REFERENCES retention_policy(id),
    data_type VARCHAR(50) NOT NULL,
    expected_delete_date DATE,
    reminded_at TIMESTAMP,
    status VARCHAR(20) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 清理任务表
CREATE TABLE IF NOT EXISTS cleanup_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_type VARCHAR(50),
    target_date DATE,
    status VARCHAR(20) DEFAULT 'PENDING' CHECK(status IN('PENDING','RUNNING','DONE','FAILED')),
    records_deleted INT,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    error_msg VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 导出备份任务表
CREATE TABLE IF NOT EXISTS export_backup_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initiator_id BIGINT REFERENCES employee(id),
    data_types TEXT,
    status VARCHAR(20) DEFAULT 'PENDING' CHECK(status IN('PENDING','RUNNING','DONE','FAILED')),
    file_path VARCHAR(500),
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    error_msg VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 系统配置表（无通用字段）
CREATE TABLE IF NOT EXISTS system_config (
    config_key VARCHAR(100) PRIMARY KEY,
    config_value TEXT,
    description VARCHAR(200)
);
