-- Flyway V3: Expense/Reimbursement Module
-- 报销系统数据库迁移：添加报销表类型、审批流定义、报销详情表

-- ============================================
-- 报销申请表（表单扩展表）
-- ============================================
CREATE TABLE IF NOT EXISTS expense_claim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT NOT NULL REFERENCES form_record(id),
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    -- 出差/报销基本信息
    expense_type VARCHAR(30) NOT NULL CHECK(expense_type IN('TRAVEL','MEAL','ACCOMMODATION','TRANSPORT','OFFICE','OTHER')),
    trip_start_date DATE,
    trip_end_date DATE,
    trip_destination VARCHAR(200),
    trip_purpose VARCHAR(500),
    -- 费用金额
    total_amount DECIMAL(12,2) NOT NULL,
    -- 发票信息（JSON数组：发票号、金额、日期简要描述）
    invoices_json TEXT,
    -- 项目关联（可选，用于项目相关报销）
    project_id BIGINT REFERENCES project(id),
    -- 审批后计入工资标志
    included_in_payroll BOOLEAN DEFAULT FALSE,
    payroll_cycle_id BIGINT,
    -- 备注
    remark VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 创建索引
CREATE INDEX idx_expense_claim_form_id ON expense_claim(form_id);
CREATE INDEX idx_expense_claim_employee_id ON expense_claim(employee_id);
CREATE INDEX idx_expense_claim_project_id ON expense_claim(project_id);
CREATE INDEX idx_expense_claim_status ON expense_claim(deleted, created_at);

-- ============================================
-- 报销明细表（每笔费用明细）
-- ============================================
CREATE TABLE IF NOT EXISTS expense_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_claim_id BIGINT NOT NULL REFERENCES expense_claim(id),
    -- 费用明细类型
    item_type VARCHAR(30) NOT NULL CHECK(item_type IN('TRAVEL','TRANSPORT','ACCOMMODATION','MEAL','MATERIAL','OTHER')),
    -- 发生日期（nullable: backend DTO does not validate this field, consistent with schema.sql）
    expense_date DATE,
    -- 金额
    amount DECIMAL(10,2) NOT NULL,
    -- 发票号
    invoice_no VARCHAR(100),
    -- 描述
    description VARCHAR(500),
    -- 附件ID
    attachment_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

CREATE INDEX idx_expense_item_claim_id ON expense_item(expense_claim_id);

-- ============================================
-- 添加报销表单类型定义
-- ============================================
INSERT INTO form_type_def (code, name, is_enabled, is_system) 
VALUES ('EXPENSE', '报销申请', TRUE, TRUE)
ON CONFLICT (code) DO NOTHING;

-- ============================================
-- 添加报销审批流定义（CEO → 财务）
-- 使用标准 SQL（兼容 H2 和 PostgreSQL）
-- ============================================

-- 插入审批流定义（如果不存在）
INSERT INTO approval_flow_def (business_type, version, is_active, created_at)
SELECT 'EXPENSE', 1, TRUE, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM approval_flow_def WHERE business_type = 'EXPENSE' AND is_active = TRUE);

-- 插入审批流节点：节点1 - CEO审批
INSERT INTO approval_flow_node (flow_id, node_order, node_name, approval_mode, approver_type, approver_ref)
SELECT a.id, 1, 'CEO审批', 'SEQUENTIAL', 'ROLE', 'ceo'
FROM approval_flow_def a
WHERE a.business_type = 'EXPENSE' AND a.is_active = TRUE
AND NOT EXISTS (SELECT 1 FROM approval_flow_node n WHERE n.flow_id = a.id AND n.node_order = 1);

-- 插入审批流节点：节点2 - 财务审批
INSERT INTO approval_flow_node (flow_id, node_order, node_name, approval_mode, approver_type, approver_ref)
SELECT a.id, 2, '财务审批', 'SEQUENTIAL', 'ROLE', 'finance'
FROM approval_flow_def a
WHERE a.business_type = 'EXPENSE' AND a.is_active = TRUE
AND NOT EXISTS (SELECT 1 FROM approval_flow_node n WHERE n.flow_id = a.id AND n.node_order = 2);

-- ============================================
-- 添加默认费用类型定义
-- ============================================
CREATE TABLE IF NOT EXISTS expense_type_def (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(200),
    require_invoice BOOLEAN DEFAULT TRUE,
    daily_limit DECIMAL(10,2),
    display_order INT DEFAULT 0,
    is_enabled BOOLEAN DEFAULT TRUE,
    is_system BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 插入默认费用类型
INSERT INTO expense_type_def (code, name, description, require_invoice, display_order, is_enabled, is_system) VALUES
('TRAVEL', '差旅费', '出差期间的交通、住宿等费用', TRUE, 1, TRUE, TRUE),
('MEAL', '餐饮费', '出差期间的餐饮补贴', TRUE, 2, TRUE, TRUE),
('ACCOMMODATION', '住宿费', '出差期间的住宿费用', TRUE, 3, TRUE, TRUE),
('TRANSPORT', '交通费', '打车、公共交通等费用', TRUE, 4, TRUE, TRUE),
('OFFICE', '办公用品', '办公耗材、用品等', TRUE, 5, TRUE, TRUE),
('OTHER', '其他', '其他报销费用', FALSE, 99, TRUE, TRUE)
ON CONFLICT (code) DO NOTHING;
