-- Flyway V5: Payroll composition extension
-- 薪资构成扩展：岗位工资 + 绩效奖金 + 三级覆盖固定补贴 + 周期临时补贴/奖金
-- 最终公式：净薪资 = 基本 + 岗位 + 绩效 + 加班 - 请假 + Σ固定补贴 + Σ临时补贴 ± 保险补贴/扣款

-- ============================================
-- 1. Position 表新增 岗位工资 字段
-- ============================================
ALTER TABLE position ADD COLUMN IF NOT EXISTS position_salary DECIMAL(12,2);

-- ============================================
-- 2. PositionLevel 表新增 岗位工资覆盖 字段
-- ============================================
ALTER TABLE position_level ADD COLUMN IF NOT EXISTS position_salary_override DECIMAL(12,2);

-- ============================================
-- 3. 补贴项定义表（餐补/交通/住房等分类）
-- ============================================
CREATE TABLE IF NOT EXISTS allowance_def (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(300),
    display_order INT DEFAULT 0,
    is_enabled BOOLEAN DEFAULT TRUE,
    is_system BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- ============================================
-- 4. 补贴三级覆盖配置表（GLOBAL / POSITION / EMPLOYEE）
--    解析顺序：EMPLOYEE > POSITION > GLOBAL；上层未命中回落下一层
-- ============================================
CREATE TABLE IF NOT EXISTS allowance_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allowance_def_id BIGINT NOT NULL REFERENCES allowance_def(id),
    scope VARCHAR(20) NOT NULL CHECK(scope IN('GLOBAL','POSITION','EMPLOYEE')),
    scope_target_id BIGINT,
    amount DECIMAL(12,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_allowance_config_def ON allowance_config(allowance_def_id, deleted);
CREATE INDEX IF NOT EXISTS idx_allowance_config_scope ON allowance_config(scope, scope_target_id, deleted);

-- ============================================
-- 5. 周期临时补贴/奖金表（财务在窗口期录入）
--    status: PENDING / APPROVED / REJECTED；不需审批时直接 APPROVED
-- ============================================
CREATE TABLE IF NOT EXISTS payroll_bonus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT NOT NULL REFERENCES payroll_cycle(id),
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    name VARCHAR(100) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    type VARCHAR(20) NOT NULL CHECK(type IN('EARNING','DEDUCTION')),
    status VARCHAR(20) NOT NULL DEFAULT 'APPROVED' CHECK(status IN('PENDING','APPROVED','REJECTED')),
    remark VARCHAR(500),
    form_id BIGINT,
    created_by BIGINT REFERENCES employee(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_payroll_bonus_cycle ON payroll_bonus(cycle_id, deleted);
CREATE INDEX IF NOT EXISTS idx_payroll_bonus_employee ON payroll_bonus(employee_id, deleted);

-- ============================================
-- 6. 新增 form_type_def：PAYROLL_BONUS（审批开关开启时使用）
-- ============================================
INSERT INTO form_type_def (code, name, is_enabled, is_system)
VALUES ('PAYROLL_BONUS', '临时薪资调整', TRUE, TRUE)
ON CONFLICT (code) DO NOTHING;

-- ============================================
-- 7. 新增 approval_flow_def：PAYROLL_BONUS 审批流（默认 CEO 单节点）
-- ============================================
INSERT INTO approval_flow_def (business_type, version, is_active, created_at)
SELECT 'PAYROLL_BONUS', 1, TRUE, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM approval_flow_def WHERE business_type = 'PAYROLL_BONUS' AND is_active = TRUE);

INSERT INTO approval_flow_node (flow_id, node_order, node_name, approval_mode, approver_type, approver_ref)
SELECT a.id, 1, 'CEO审批', 'SEQUENTIAL', 'ROLE', 'ceo'
FROM approval_flow_def a
WHERE a.business_type = 'PAYROLL_BONUS' AND a.is_active = TRUE
AND NOT EXISTS (SELECT 1 FROM approval_flow_node n WHERE n.flow_id = a.id AND n.node_order = 1);

-- ============================================
-- 8. 新增 system_config：临时补贴是否需要 CEO 审批（默认 false）
-- ============================================
INSERT INTO system_config (config_key, config_value, description)
VALUES ('payroll_bonus_approval_required', 'false', '临时薪资调整是否需要 CEO 审批（true/false）')
ON CONFLICT (config_key) DO NOTHING;

-- ============================================
-- 9. 新增 payroll_item_def 内置项：岗位工资 / 绩效奖金 / 临时补贴 / 临时扣款
-- ============================================
INSERT INTO payroll_item_def (code, name, type, display_order, is_enabled, is_system)
VALUES
    ('POSITION_SALARY',   '岗位工资',   'EARNING',   11, TRUE, TRUE),
    ('PERFORMANCE_BONUS', '绩效奖金',   'EARNING',   12, TRUE, TRUE),
    ('TEMPORARY_BONUS',   '临时补贴',   'EARNING',   90, TRUE, TRUE),
    ('TEMPORARY_DEDUCT',  '临时扣款',   'DEDUCTION', 91, TRUE, TRUE)
ON CONFLICT (code) DO NOTHING;

-- 原 COMPANY_PAID_SUBSIDY 保留 code，显示名调整为更通用的"保险补贴"
UPDATE payroll_item_def SET name = '保险补贴' WHERE code = 'COMPANY_PAID_SUBSIDY';
