-- Flyway V7
-- 设计文档对齐：第二角色、临时委托、售后问题单、项目实体成本、HR 字段、总经理角色

-- ============================================
-- 1. Employee 增加 HR/财务字段
-- ============================================
ALTER TABLE employee ADD COLUMN IF NOT EXISTS social_seniority INT;
ALTER TABLE employee ADD COLUMN IF NOT EXISTS contract_type VARCHAR(20);
ALTER TABLE employee ADD COLUMN IF NOT EXISTS daily_subsidy DECIMAL(12,2);
ALTER TABLE employee ADD COLUMN IF NOT EXISTS expense_limit DECIMAL(12,2);
ALTER TABLE employee ADD COLUMN IF NOT EXISTS performance_ratio DECIMAL(5,2);

-- ============================================
-- 2. emergency_contact（员工紧急联系人子表，1:N）
-- ============================================
CREATE TABLE IF NOT EXISTS emergency_contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    address VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_emergency_contact_emp ON emergency_contact(employee_id, deleted);

-- ============================================
-- 3. 总经理角色（可选主角色，加入种子）
-- ============================================
INSERT INTO sys_role (role_code, role_name, description, status, is_system)
SELECT 'general_manager', '总经理', '介于 CEO 与各部门负责人之间；可加入审批流末端链；可见全项目但不可见考勤/薪资/HR 档案。', 1, 1
WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE role_code = 'general_manager');

-- ============================================
-- 4. 第二角色：第二角色定义 + 分配
--    code: AFTER_SALES（员工，项目结束后）
--          MATERIAL_MANAGER（员工，项目期间）
--          FOREMAN（劳工，项目期间）
-- ============================================
CREATE TABLE IF NOT EXISTS second_role_def (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    applies_to VARCHAR(20) NOT NULL CHECK(applies_to IN('OFFICE','LABOR')),
    project_bound BOOLEAN NOT NULL DEFAULT TRUE,
    description VARCHAR(200),
    is_system BOOLEAN DEFAULT TRUE,
    is_enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

INSERT INTO second_role_def (code, name, applies_to, project_bound, description, is_system, is_enabled)
SELECT 'AFTER_SALES', '售后', 'OFFICE', TRUE, '项目结束后处理售后问题单', TRUE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM second_role_def WHERE code = 'AFTER_SALES');
INSERT INTO second_role_def (code, name, applies_to, project_bound, description, is_system, is_enabled)
SELECT 'MATERIAL_MANAGER', '物资管理', 'OFFICE', TRUE, '录入项目实体成本', TRUE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM second_role_def WHERE code = 'MATERIAL_MANAGER');
INSERT INTO second_role_def (code, name, applies_to, project_bound, description, is_system, is_enabled)
SELECT 'FOREMAN', '工长', 'LABOR', TRUE, '提交施工日志，可代录工伤', TRUE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM second_role_def WHERE code = 'FOREMAN');

CREATE TABLE IF NOT EXISTS second_role_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    role_code VARCHAR(50) NOT NULL,
    project_id BIGINT REFERENCES project(id),
    assigned_by BIGINT REFERENCES employee(id),
    revoked BOOLEAN DEFAULT FALSE,
    revoked_at TIMESTAMP,
    note VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_second_role_emp ON second_role_assignment(employee_id, deleted);
CREATE INDEX IF NOT EXISTS idx_second_role_project ON second_role_assignment(project_id, deleted);

-- ============================================
-- 5. 临时委托：委托人填写代办人手机号，系统生成 token
--    委托人/被委托人 + 有效期 + 表单类型范围
-- ============================================
CREATE TABLE IF NOT EXISTS temporary_delegation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delegator_id BIGINT NOT NULL REFERENCES employee(id),
    delegate_phone VARCHAR(20) NOT NULL,
    delegate_employee_id BIGINT REFERENCES employee(id),
    related_form_id BIGINT,
    scope VARCHAR(50),
    starts_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    token VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK(status IN('ACTIVE','EXPIRED','REVOKED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_delegation_delegator ON temporary_delegation(delegator_id, status);
CREATE INDEX IF NOT EXISTS idx_delegation_delegate ON temporary_delegation(delegate_employee_id, status);

-- ============================================
-- 6. 售后问题单
-- ============================================
CREATE TABLE IF NOT EXISTS after_sale_type_def (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    is_system BOOLEAN DEFAULT TRUE,
    is_enabled BOOLEAN DEFAULT TRUE,
    display_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

INSERT INTO after_sale_type_def (code, name, display_order)
SELECT 'QUALITY', '质量问题', 1 WHERE NOT EXISTS (SELECT 1 FROM after_sale_type_def WHERE code = 'QUALITY');
INSERT INTO after_sale_type_def (code, name, display_order)
SELECT 'CONSTRUCTION', '施工问题', 2 WHERE NOT EXISTS (SELECT 1 FROM after_sale_type_def WHERE code = 'CONSTRUCTION');
INSERT INTO after_sale_type_def (code, name, display_order)
SELECT 'NON_QUALITY', '非质量问题（客户原因）', 3 WHERE NOT EXISTS (SELECT 1 FROM after_sale_type_def WHERE code = 'NON_QUALITY');

CREATE TABLE IF NOT EXISTS after_sale_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    type_code VARCHAR(50) NOT NULL,
    incident_date DATE NOT NULL,
    description TEXT NOT NULL,
    customer_feedback TEXT,
    resolution TEXT,
    attachment_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','PROCESSING','CLOSED')),
    created_by BIGINT REFERENCES employee(id),
    handler_id BIGINT REFERENCES employee(id),
    closed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_after_sale_project ON after_sale_ticket(project_id, deleted);
CREATE INDEX IF NOT EXISTS idx_after_sale_status ON after_sale_ticket(status, deleted);

-- ============================================
-- 7. 项目实体成本（PM 或 物资管理 角色录入）
-- ============================================
CREATE TABLE IF NOT EXISTS project_material_cost (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    item_name VARCHAR(100) NOT NULL,
    spec VARCHAR(100),
    quantity DECIMAL(12,2) NOT NULL,
    unit VARCHAR(20) NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    occurred_on DATE NOT NULL,
    remark VARCHAR(500),
    recorded_by BIGINT REFERENCES employee(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_material_cost_project ON project_material_cost(project_id, deleted);
