-- Flyway V8: 营收管理（合同里程碑收款）+ 工种保险成本（按出勤天数自动累计）

-- ============================================
-- 1. project_milestone 增加财务字段（设计 §8.4-8.5）
-- ============================================
ALTER TABLE project_milestone ADD COLUMN IF NOT EXISTS contract_amount DECIMAL(12,2);
ALTER TABLE project_milestone ADD COLUMN IF NOT EXISTS receipt_status VARCHAR(20) DEFAULT 'PENDING' CHECK(receipt_status IN('PENDING','RECEIVED'));
ALTER TABLE project_milestone ADD COLUMN IF NOT EXISTS actual_receipt_amount DECIMAL(12,2);
ALTER TABLE project_milestone ADD COLUMN IF NOT EXISTS receipt_date DATE;
ALTER TABLE project_milestone ADD COLUMN IF NOT EXISTS receipt_remark VARCHAR(500);

-- ============================================
-- 2. project_insurance_def — 项目保险条目配置（按工种或个人）
--    scope: GLOBAL（全劳工）/ POSITION（劳工某岗位）/ EMPLOYEE（指定个人）
-- ============================================
CREATE TABLE IF NOT EXISTS project_insurance_def (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    insurance_name VARCHAR(50) NOT NULL,
    scope VARCHAR(20) NOT NULL CHECK(scope IN('GLOBAL','POSITION','EMPLOYEE')),
    scope_target_id BIGINT,
    daily_rate DECIMAL(12,2) NOT NULL,
    effective_date DATE NOT NULL,
    remark VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_insurance_def_project ON project_insurance_def(project_id, deleted);
