-- Flyway V9: 结构化施工出勤 + 工资条项分类 + 周期解锁/确认状态 + 营收变更草稿

-- ============================================
-- 1. construction_attendance — 标准化出勤数据（每行 = 某员工某天某条日志）
--    日志提交/审批时由后端写入；保险/工资聚合从此查询，不再解析自由 JSON
-- ============================================
CREATE TABLE IF NOT EXISTS construction_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    attendance_date DATE NOT NULL,
    source VARCHAR(20) NOT NULL DEFAULT 'LOG' CHECK(source IN('LOG','MANUAL','OT_SELF_REPORT')),
    source_form_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0,
    UNIQUE(employee_id, attendance_date, source_form_id)
);

CREATE INDEX IF NOT EXISTS idx_attendance_project_date ON construction_attendance(project_id, attendance_date, deleted);
CREATE INDEX IF NOT EXISTS idx_attendance_employee_date ON construction_attendance(employee_id, attendance_date, deleted);

-- ============================================
-- 2. payroll_item_def 增加 category 字段（分组展示用：基本/补贴/扣款/合计前的小计标签）
-- ============================================
ALTER TABLE payroll_item_def ADD COLUMN IF NOT EXISTS category VARCHAR(20) DEFAULT 'OTHER';

UPDATE payroll_item_def SET category = 'EARNING'  WHERE type = 'EARNING'   AND category IS NULL OR category = 'OTHER';
UPDATE payroll_item_def SET category = 'DEDUCTION' WHERE type = 'DEDUCTION' AND (category IS NULL OR category = 'OTHER');

-- ============================================
-- 3. project_milestone 增加「合同金额变更草稿」+ 待审批方
--    财务改 → 待 PM 审批；PM 改 → 待财务审批
--    pending_change_amount 非空表示有未审批的变更
-- ============================================
ALTER TABLE project_milestone ADD COLUMN IF NOT EXISTS pending_change_amount DECIMAL(12,2);
ALTER TABLE project_milestone ADD COLUMN IF NOT EXISTS pending_change_role VARCHAR(20);
ALTER TABLE project_milestone ADD COLUMN IF NOT EXISTS pending_change_initiator BIGINT;
ALTER TABLE project_milestone ADD COLUMN IF NOT EXISTS pending_change_form_id BIGINT;

-- ============================================
-- 4. 项目工长字段（设计 §8.3 — PM 可指定一个工长劳工；未指定 → PM 自填免审批）
-- ============================================
ALTER TABLE project ADD COLUMN IF NOT EXISTS foreman_employee_id BIGINT;

-- ============================================
-- 5. PAYROLL_REVENUE_CHANGE 表单类型 + 双向审批流（财务发起 → PM 审批；反之亦然）
--    审批节点的实际审批人由提交方反向决定，approver_type=ROLE 配合 approver_ref 在 service 中动态切换
-- ============================================
INSERT INTO form_type_def (code, name, is_enabled, is_system)
VALUES ('PAYROLL_REVENUE_CHANGE', '营收金额变更', TRUE, TRUE)
ON CONFLICT (code) DO NOTHING;

INSERT INTO approval_flow_def (business_type, version, is_active, created_at)
SELECT 'PAYROLL_REVENUE_CHANGE', 1, TRUE, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM approval_flow_def WHERE business_type = 'PAYROLL_REVENUE_CHANGE' AND is_active = TRUE);

-- 单节点：approver_ref 在 form_data 中通过 "counterparty" 字段动态决定
INSERT INTO approval_flow_node (flow_id, node_order, node_name, approval_mode, approver_type, approver_ref)
SELECT a.id, 1, '对方审批', 'SEQUENTIAL', 'ROLE', 'ceo'
FROM approval_flow_def a
WHERE a.business_type = 'PAYROLL_REVENUE_CHANGE' AND a.is_active = TRUE
AND NOT EXISTS (SELECT 1 FROM approval_flow_node n WHERE n.flow_id = a.id AND n.node_order = 1);

-- ============================================
-- 6. payroll_cycle 增加自动锁定标记（用于 CEO unlock 时区别于初始 OPEN）
-- ============================================
-- 已有 status 包含 LOCKED；无需新字段。CEO unlock = 把 SETTLED/LOCKED 改回 WINDOW_CLOSED
