/**
 * System module test cases — TC-SYS-01 ~ TC-SYS-13
 * Scope: concurrency, security/token/CORS/XSS, end-to-end regression baseline
 */
import type { TestCase } from '../../../../tools/autotest/runner/types.js';
import { loginSteps, USERS } from '../_helpers.js';

const cases: TestCase[] = [
  {
    id: 'TC-SYS-01',
    title: '6 个角色同时登录各自独立',
    description: '并发。路径：parallel 同时登录 6 个角色，各自访问工作台。期望：session 隔离，数据不串。',
    module: 'system',
    priority: 'P0',
    roles: ['ceo', 'hr', 'finance', 'pm', 'employee', 'worker'],
    tags: ['concurrency'],
    steps: [
      {
        id: 1,
        desc: '并行登录 6 角色',
        action: 'parallel',
        contexts: [
          loginSteps(USERS.ceo.username, USERS.ceo.password),
          loginSteps(USERS.hr.username, USERS.hr.password),
          loginSteps(USERS.finance.username, USERS.finance.password),
          loginSteps(USERS.pm.username, USERS.pm.password),
          loginSteps(USERS.employee.username, USERS.employee.password),
          loginSteps(USERS.worker.username, USERS.worker.password),
        ],
      },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-SYS-02',
    title: 'CEO 与 PM 并发审批同一待办',
    description: '并发。路径：parallel CEO 和 PM 同时审批同一单。期望：其中一方成功，另一方提示已处理。',
    module: 'system',
    priority: 'P1',
    roles: ['ceo', 'pm'],
    tags: ['concurrency'],
    steps: [
      {
        id: 1,
        desc: '并发审批',
        action: 'parallel',
        contexts: [
          [
            ...loginSteps(USERS.ceo.username, USERS.ceo.password, 1),
            { id: 6, desc: 'CEO approve', action: 'api_call', method: 'POST', endpoint: '/api/approval/1/approve', body: { comment: 'CEO' } },
          ],
          [
            ...loginSteps(USERS.pm.username, USERS.pm.password, 1),
            { id: 6, desc: 'PM approve', action: 'api_call', method: 'POST', endpoint: '/api/approval/1/approve', body: { comment: 'PM' } },
          ],
        ],
      },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-SYS-03',
    title: '两名 HR 并发创建同手机号员工',
    description: '并发。路径：parallel 两个 HR session 同时 POST /api/employees phone 相同。期望：至少一个返回 409。',
    module: 'system',
    priority: 'P1',
    roles: ['hr'],
    tags: ['concurrency', 'api-only'],
    steps: [
      {
        id: 1,
        desc: '并发相同手机号创建',
        action: 'parallel',
        contexts: [
          [
            ...loginSteps(USERS.hr.username, USERS.hr.password, 1),
            { id: 6, desc: 'A 创建', action: 'api_call', method: 'POST', endpoint: '/api/employees', body: { name: '并发 A', phone: '13900000000', departmentId: 1, positionId: 1 } },
          ],
          [
            ...loginSteps(USERS.hr.username, USERS.hr.password, 1),
            { id: 6, desc: 'B 创建', action: 'api_call', method: 'POST', endpoint: '/api/employees', body: { name: '并发 B', phone: '13900000000', departmentId: 1, positionId: 1 } },
          ],
        ],
      },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-SYS-04',
    title: '财务对两个不同周期并发结算',
    description: '并发。路径：parallel Finance 对 cycleA 和 cycleB 分别发起结算。期望：两者互不干扰均成功。',
    module: 'system',
    priority: 'P2',
    roles: ['finance'],
    tags: ['concurrency', 'api-only'],
    steps: [
      {
        id: 1,
        desc: '并发不同周期结算',
        action: 'parallel',
        contexts: [
          [
            ...loginSteps(USERS.finance.username, USERS.finance.password, 1),
            { id: 6, desc: 'cycle A settle', action: 'api_call', method: 'POST', endpoint: '/api/payroll/cycles/1/settle', body: {} },
          ],
          [
            ...loginSteps(USERS.finance.username, USERS.finance.password, 1),
            { id: 6, desc: 'cycle B settle', action: 'api_call', method: 'POST', endpoint: '/api/payroll/cycles/2/settle', body: {} },
          ],
        ],
      },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-SYS-05',
    title: '无 Token 访问 /api/employees 返回 401',
    description: '安全。路径：不登录直接 GET /api/employees。期望：401。',
    module: 'system',
    priority: 'P0',
    roles: ['anonymous'],
    tags: ['security', 'api-only'],
    steps: [
      { id: 1, desc: '访问登录页（清 token）', action: 'navigate', to: '/login' },
      { id: 2, desc: '调用受保护 API', action: 'api_call', method: 'GET', endpoint: '/api/employees' },
      { id: 3, desc: '截图记录 401', action: 'screenshot', label: 'no-token-401' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-SYS-06',
    title: '过期 Token 访问受保护接口 401',
    description: '安全。路径：注入过期 JWT → GET /api/me。期望：401。',
    module: 'system',
    priority: 'P0',
    roles: ['anonymous'],
    tags: ['security', 'api-only'],
    steps: [
      { id: 1, desc: '使用 dev API 注入过期 token', action: 'api_call', method: 'POST', endpoint: '/api/dev/inject-expired-token', body: {} },
      { id: 2, desc: '调用 /api/me', action: 'api_call', method: 'GET', endpoint: '/api/me' },
      { id: 3, desc: '截图记录 401', action: 'screenshot', label: 'expired-token-401' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-SYS-07',
    title: '员工 Token 访问 /api/payroll/cycles 403',
    description: '安全。路径：员工登录 → GET /api/payroll/cycles。期望：403。',
    module: 'system',
    priority: 'P0',
    roles: ['employee'],
    credentials: USERS.employee,
    tags: ['security', 'api-only'],
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '调用 GET /api/payroll/cycles', action: 'api_call', method: 'GET', endpoint: '/api/payroll/cycles' },
      { id: 7, desc: '截图记录 403', action: 'screenshot', label: 'employee-403' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-SYS-08',
    title: '登录表单 XSS payload 被转义',
    description: '安全。路径：登录页账号输入 <script>alert(1)</script>。期望：脚本不执行，文本被转义。',
    module: 'system',
    priority: 'P1',
    roles: ['anonymous'],
    tags: ['security'],
    steps: [
      { id: 1, desc: '打开登录页', action: 'navigate', to: '/login' },
      { id: 2, desc: '输入 XSS payload', action: 'fill', locator: { by: 'label', value: '工号 / 手机号' }, value: '<script>alert(1)</script>' },
      { id: 3, desc: '输入密码', action: 'fill', locator: { by: 'label', value: '登录密码' }, value: 'pw' },
      { id: 4, desc: '点击登录', action: 'click', locator: { by: 'catch', value: 'login-form-submit' } },
      { id: 5, desc: '页面不应弹出 alert', action: 'screenshot', label: 'xss-no-alert' },
      { id: 6, desc: '应停留在 /login', action: 'assert', check: { type: 'url_contains', value: '/login' } },
    ],
    expect: { result: 'pass', url: '/login' },
  },
  {
    id: 'TC-SYS-09',
    title: '跨域请求非 /api 路径被 CORS 拒绝',
    description: '安全。路径：前端尝试请求 http://backend/internal/debug。期望：CORS 拒绝。',
    module: 'system',
    priority: 'P2',
    roles: ['anonymous'],
    tags: ['security', 'api-only'],
    steps: [
      { id: 1, desc: '访问 /debug 路径', action: 'api_call', method: 'GET', endpoint: '/debug/internal' },
      { id: 2, desc: '截图记录 CORS 拒绝', action: 'screenshot', label: 'cors-reject' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-SYS-10',
    title: '主链路 E2E：请假→审批→通知',
    description: '回归基线。路径：员工提交请假 → PM 审批通过 → 员工收通知。期望：整条链路成功。',
    module: 'system',
    priority: 'P0',
    roles: ['employee', 'pm'],
    tags: ['e2e'],
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '员工提交请假 API', action: 'api_call', method: 'POST', endpoint: '/api/leave', body: { leaveType: 'PERSONAL', startDate: '2026-05-15', endDate: '2026-05-15', reason: 'E2E 链路' } },
      { id: 7, desc: '切换到登录页', action: 'navigate', to: '/login' },
      ...loginSteps(USERS.pm.username, USERS.pm.password, 8),
      { id: 13, desc: 'PM 审批通过', action: 'api_call', method: 'POST', endpoint: '/api/approval/leave/latest/approve', body: { comment: 'ok' } },
      { id: 14, desc: '再回到员工登录', action: 'navigate', to: '/login' },
      ...loginSteps(USERS.employee.username, USERS.employee.password, 15),
      { id: 20, desc: '访问通知页', action: 'navigate', to: '/notifications' },
      { id: 21, desc: '应存在请假通过通知', action: 'assert', check: { type: 'text_visible', value: '请假' } },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-SYS-11',
    title: '主链路 E2E：薪资结算→员工 PIN 确认',
    description: '回归基线。路径：财务创建周期 → 结算 → 员工 PIN 确认。期望：整条链路成功。',
    module: 'system',
    priority: 'P0',
    roles: ['finance', 'employee'],
    tags: ['e2e'],
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      { id: 6, desc: 'API 创建周期', action: 'api_call', method: 'POST', endpoint: '/api/payroll/cycles', body: { cycleMonth: '2026-04' } },
      { id: 7, desc: 'API 结算', action: 'api_call', method: 'POST', endpoint: '/api/payroll/cycles/latest/settle', body: {} },
      { id: 8, desc: 'API 发布', action: 'api_call', method: 'POST', endpoint: '/api/payroll/cycles/latest/publish', body: {} },
      { id: 9, desc: '回到登录页', action: 'navigate', to: '/login' },
      ...loginSteps(USERS.employee.username, USERS.employee.password, 10),
      { id: 15, desc: '员工 PIN 确认', action: 'api_call', method: 'POST', endpoint: '/api/payroll/slips/latest/confirm', body: { pin: '123456' } },
      { id: 16, desc: '截图记录最终状态', action: 'screenshot', label: 'payroll-e2e' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-SYS-12',
    title: '主链路 E2E：施工日志→审批',
    description: '回归基线。路径：劳工提交施工日志 → PM 审批通过。期望：整条链路成功。',
    module: 'system',
    priority: 'P0',
    roles: ['worker', 'pm'],
    tags: ['e2e'],
    steps: [
      ...loginSteps(USERS.worker.username, USERS.worker.password),
      { id: 6, desc: '劳工 API 提交施工日志', action: 'api_call', method: 'POST', endpoint: '/api/construction-logs', body: { date: '2026-04-14', content: 'E2E 施工', hours: 8 } },
      { id: 7, desc: '回登录页', action: 'navigate', to: '/login' },
      ...loginSteps(USERS.pm.username, USERS.pm.password, 8),
      { id: 13, desc: 'PM API 审批通过', action: 'api_call', method: 'POST', endpoint: '/api/approval/construction/latest/approve', body: { comment: 'E2E pass' } },
      { id: 14, desc: '截图', action: 'screenshot', label: 'construction-e2e' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-SYS-13',
    title: 'CEO 工作台摘要数据全部非零',
    description: '回归基线。路径：CEO 登录后 /。期望：员工数/项目数/待办数摘要卡片全部显示 > 0（种子数据存在）。',
    module: 'system',
    priority: 'P0',
    roles: ['ceo'],
    credentials: USERS.ceo,
    tags: ['e2e', 'baseline'],
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '员工数卡片可见', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'workbench-card-total-employees' } } },
      { id: 7, desc: '活跃项目卡片可见', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'workbench-card-active-projects' } } },
      { id: 8, desc: '待办卡片可见', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'workbench-card-todos' } } },
      { id: 9, desc: '截图人工确认数字非零', action: 'screenshot', label: 'workbench-non-zero' },
    ],
    expect: { result: 'pass', url: '/' },
  },
];

export default cases;
