/**
 * Construction module test cases — TC-CON-01 ~ TC-CON-10
 * Scope: construction log submission, PM approval/rejection, permission checks
 */
import type { TestCase } from '../../../../tools/autotest/runner/types.js';
import { loginSteps, USERS } from '../_helpers.js';

const cases: TestCase[] = [
  {
    id: 'TC-CON-01',
    title: '劳工提交施工日志（日期/工程内容/工时）',
    description: '角色：Worker。路径：登录 → /construction-log → 填写日志 → 选日期 → 添加工作项 → 提交。期望：出现"施工日志已提交"提示，列表显示待审批记录。',
    module: 'construction',
    priority: 'P0',
    roles: ['worker'],
    credentials: USERS.worker,
    steps: [
      ...loginSteps(USERS.worker.username, USERS.worker.password),
      { id: 6, desc: '访问施工日志页', action: 'navigate', to: '/construction-log' },
      { id: 7, desc: '点击"+ 填写日志"', action: 'click', locator: { by: 'catch', value: 'construction-log-create-btn' } },
      { id: 8, desc: '选择日志日期', action: 'fill', locator: { by: 'label', value: '日志日期' }, value: '2024-01-15' },
      { id: 9, desc: '点击添加工作项', action: 'click', locator: { by: 'text', value: '添加工作项', exact: false } },
      { id: 10, desc: '输入工作项名称', action: 'fill', locator: { by: 'role', role: 'textbox', name: '工作项名称' }, value: '钢筋绑扎' },
      { id: 11, desc: '输入数量', action: 'fill', locator: { by: 'role', role: 'spinbutton', name: '数量' }, value: '2' },
      { id: 12, desc: '点击提交', action: 'click', locator: { by: 'text', value: '提交', exact: true } },
      { id: 13, desc: '出现提交成功提示', action: 'assert', check: { type: 'toast_contains', value: '施工日志已提交' } },
      { id: 14, desc: '列表显示待审批记录', action: 'assert', check: { type: 'text_visible', value: '待审批' } },
    ],
    expect: { result: 'pass', url: '/construction-log' },
  },
  {
    id: 'TC-CON-02',
    title: 'PM 在待审批列表看到施工日志',
    description: '角色：PM。路径：登录 → /projects/1 → 施工日志审批 Tab。期望：列表中存在状态为"待审批"的施工日志记录。',
    module: 'construction',
    priority: 'P0',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问项目详情页', action: 'navigate', to: '/projects/1' },
      { id: 7, desc: '点击"施工日志审批"Tab', action: 'click', locator: { by: 'text', value: '施工日志审批', exact: true } },
      { id: 8, desc: '列表应显示待审批记录', action: 'assert', check: { type: 'text_visible', value: '待审批' } },
    ],
    expect: { result: 'pass', url: '/projects/1' },
  },
  {
    id: 'TC-CON-03',
    title: 'PM 批注并审批通过施工日志',
    description: '角色：PM。路径：/projects/1 → 施工日志审批 → 批注 → 通过。期望：记录状态变为"已通过"，出现通过提示。',
    module: 'construction',
    priority: 'P0',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问项目详情页', action: 'navigate', to: '/projects/1' },
      { id: 7, desc: '点击"施工日志审批"Tab', action: 'click', locator: { by: 'text', value: '施工日志审批', exact: true } },
      { id: 8, desc: '点击第一条记录"批注"', action: 'click', locator: { by: 'catch', value: 'construction-row-review-btn-1' } },
      { id: 9, desc: '输入批注内容', action: 'fill', locator: { by: 'label', value: '批注内容' }, value: '工作量确认无误' },
      { id: 10, desc: '保存批注', action: 'click', locator: { by: 'text', value: '确 定', exact: true } },
      { id: 11, desc: '点击第一条记录"通过"', action: 'click', locator: { by: 'catch', value: 'construction-row-approve-btn-1' } },
      { id: 12, desc: '出现审批通过提示', action: 'assert', check: { type: 'toast_contains', value: '已通过' } },
      { id: 13, desc: '记录状态显示已通过', action: 'assert', check: { type: 'text_visible', value: '已通过' } },
    ],
    expect: { result: 'pass', url: '/projects/1' },
  },
  {
    id: 'TC-CON-04',
    title: 'PM 驳回施工日志，劳工收到通知',
    description: '角色：PM。路径：/projects/1 → 施工日志审批 → 驳回 → 填写原因 → 确认。期望：记录状态变为"已驳回"，出现驳回提示。',
    module: 'construction',
    priority: 'P1',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问项目详情页', action: 'navigate', to: '/projects/1' },
      { id: 7, desc: '点击"施工日志审批"Tab', action: 'click', locator: { by: 'text', value: '施工日志审批', exact: true } },
      { id: 8, desc: '点击第一条记录"驳回"', action: 'click', locator: { by: 'catch', value: 'construction-row-reject-btn-1' } },
      { id: 9, desc: '输入驳回原因', action: 'fill', locator: { by: 'label', value: '驳回原因' }, value: '工程量填写有误，请补充说明' },
      { id: 10, desc: '确认驳回', action: 'click', locator: { by: 'text', value: '确 定', exact: true } },
      { id: 11, desc: '出现驳回成功提示', action: 'assert', check: { type: 'toast_contains', value: '已驳回' } },
      { id: 12, desc: '记录状态显示已驳回', action: 'assert', check: { type: 'text_visible', value: '已驳回' } },
    ],
    expect: { result: 'pass', url: '/projects/1' },
  },
  {
    id: 'TC-CON-05',
    title: '工长提交施工日志（第二角色权限）',
    description: '角色：Worker（兼工长）。路径：登录 → /construction-log → 填写日志 → 选日期 → 添加工作项 → 提交。期望：提交成功，列表显示待审批记录。',
    module: 'construction',
    priority: 'P1',
    roles: ['worker'],
    credentials: USERS.worker,
    steps: [
      ...loginSteps(USERS.worker.username, USERS.worker.password),
      { id: 6, desc: '访问施工日志页', action: 'navigate', to: '/construction-log' },
      { id: 7, desc: '点击"+ 填写日志"', action: 'click', locator: { by: 'catch', value: 'construction-log-create-btn' } },
      { id: 8, desc: '选择日志日期', action: 'fill', locator: { by: 'label', value: '日志日期' }, value: '2024-01-16' },
      { id: 9, desc: '点击添加工作项', action: 'click', locator: { by: 'text', value: '添加工作项', exact: false } },
      { id: 10, desc: '输入工作项名称', action: 'fill', locator: { by: 'role', role: 'textbox', name: '工作项名称' }, value: '混凝土浇筑' },
      { id: 11, desc: '输入数量', action: 'fill', locator: { by: 'role', role: 'spinbutton', name: '数量' }, value: '3' },
      { id: 12, desc: '点击提交', action: 'click', locator: { by: 'text', value: '提交', exact: true } },
      { id: 13, desc: '出现提交成功提示', action: 'assert', check: { type: 'toast_contains', value: '施工日志已提交' } },
    ],
    expect: { result: 'pass', url: '/construction-log' },
  },
  {
    id: 'TC-CON-06',
    title: '施工日志列表支持按日期范围筛选',
    description: '角色：PM。路径：登录 → 调用 GET /logs/records 并附加起止日期参数。期望：API 返回符合日期范围的施工日志记录。',
    module: 'construction',
    priority: 'P1',
    roles: ['pm'],
    credentials: USERS.pm,
    tags: ['api-only'],
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '调用带日期范围筛选的 API', action: 'api_call', method: 'GET', endpoint: '/api/logs/records?startDate=2024-01-01&endDate=2024-01-31' },
      { id: 7, desc: '人工核对返回结果符合日期范围', action: 'screenshot', label: 'construction-logs-date-filter' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-CON-07',
    title: '工程内容为空时提交',
    description: '角色：Worker。路径：/construction-log → 填写日志 → 不选日期/不填工作项 → 直接提交。期望：前端校验提示"请选择日志日期"，提交不生效。',
    module: 'construction',
    priority: 'P1',
    roles: ['worker'],
    credentials: USERS.worker,
    steps: [
      ...loginSteps(USERS.worker.username, USERS.worker.password),
      { id: 6, desc: '访问施工日志页', action: 'navigate', to: '/construction-log' },
      { id: 7, desc: '点击"+ 填写日志"', action: 'click', locator: { by: 'catch', value: 'construction-log-create-btn' } },
      { id: 8, desc: '直接点击提交（不填任何内容）', action: 'click', locator: { by: 'text', value: '提交', exact: true } },
      { id: 9, desc: '出现日期必填校验提示', action: 'assert', check: { type: 'toast_contains', value: '请选择日志日期' } },
    ],
    expect: { result: 'pass', url: '/construction-log' },
  },
  {
    id: 'TC-CON-08',
    title: '工时为 0 时提交',
    description: '角色：Worker。路径：/construction-log → 填写日志 → 选日期 → 添加工作项并将数量设为 0 → 提交。期望：截图记录系统反应（按业务规则校验或允许）。',
    module: 'construction',
    priority: 'P1',
    roles: ['worker'],
    credentials: USERS.worker,
    steps: [
      ...loginSteps(USERS.worker.username, USERS.worker.password),
      { id: 6, desc: '访问施工日志页', action: 'navigate', to: '/construction-log' },
      { id: 7, desc: '点击"+ 填写日志"', action: 'click', locator: { by: 'catch', value: 'construction-log-create-btn' } },
      { id: 8, desc: '选择日志日期', action: 'fill', locator: { by: 'label', value: '日志日期' }, value: '2024-01-17' },
      { id: 9, desc: '点击添加工作项', action: 'click', locator: { by: 'text', value: '添加工作项', exact: false } },
      { id: 10, desc: '输入工作项名称', action: 'fill', locator: { by: 'role', role: 'textbox', name: '工作项名称' }, value: '场地清理' },
      { id: 11, desc: '将数量设为 0', action: 'fill', locator: { by: 'role', role: 'spinbutton', name: '数量' }, value: '0' },
      { id: 12, desc: '点击提交', action: 'click', locator: { by: 'text', value: '提交', exact: true } },
      { id: 13, desc: '截图记录系统反应', action: 'screenshot', label: 'construction-zero-quantity-response' },
    ],
    expect: { result: 'pass', url: '/construction-log' },
  },
  {
    id: 'TC-CON-09',
    title: '员工（非劳工/工长）尝试提交施工日志',
    description: '角色：Employee。路径：登录后直接访问 /construction-log。期望：无"+ 填写日志"按钮，或被重定向/提示无权限。',
    module: 'construction',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    tags: ['permission'],
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '直接访问 /construction-log', action: 'navigate', to: '/construction-log' },
      { id: 7, desc: '不应显示"+ 填写日志"按钮', action: 'assert', check: { type: 'text_absent', value: '填写日志' } },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-CON-10',
    title: '重复提交同一日期的施工日志',
    description: '角色：Worker。路径：/construction-log → 对同一日期提交两次施工日志。期望：系统提示已存在，或按业务规则允许再次提交。',
    module: 'construction',
    priority: 'P2',
    roles: ['worker'],
    credentials: USERS.worker,
    steps: [
      ...loginSteps(USERS.worker.username, USERS.worker.password),
      { id: 6, desc: '访问施工日志页', action: 'navigate', to: '/construction-log' },
      { id: 7, desc: '点击"+ 填写日志"', action: 'click', locator: { by: 'catch', value: 'construction-log-create-btn' } },
      { id: 8, desc: '选择日志日期', action: 'fill', locator: { by: 'label', value: '日志日期' }, value: '2024-01-18' },
      { id: 9, desc: '点击添加工作项', action: 'click', locator: { by: 'text', value: '添加工作项', exact: false } },
      { id: 10, desc: '输入工作项名称', action: 'fill', locator: { by: 'role', role: 'textbox', name: '工作项名称' }, value: '重复测试项' },
      { id: 11, desc: '第一次提交', action: 'click', locator: { by: 'text', value: '提交', exact: true } },
      { id: 12, desc: '等待提示消失', action: 'wait', ms: 1500 },
      { id: 13, desc: '再次点击"+ 填写日志"', action: 'click', locator: { by: 'catch', value: 'construction-log-create-btn' } },
      { id: 14, desc: '再次选择同一日期', action: 'fill', locator: { by: 'label', value: '日志日期' }, value: '2024-01-18' },
      { id: 15, desc: '输入工作项', action: 'fill', locator: { by: 'role', role: 'textbox', name: '工作项名称' }, value: '重复测试项' },
      { id: 16, desc: '第二次提交', action: 'click', locator: { by: 'text', value: '提交', exact: true } },
      { id: 17, desc: '截图记录系统反应', action: 'screenshot', label: 'construction-duplicate-submit-response' },
    ],
    expect: { result: 'pass', url: '/construction-log' },
  },
];

export default cases;
