import type { TestCase } from '../../../../tools/autotest/runner/types.js';

export default {
  id: 'TC-SYS-11',
  title: '主链路 E2E：财务创建薪资周期 → 结算 → 员工 PIN 确认',
  module: 'system',
  priority: 'P0',
  tags: ['smoke'],
  steps: [
    { id: 1, desc: '财务登录', action: 'navigate', to: '/login' },
    { id: 2, desc: '输入财务用户名', action: 'fill', locator: { by: 'label', value: '用户名', exact: false }, value: 'finance.demo' },
    { id: 3, desc: '输入密码', action: 'fill', locator: { by: 'label', value: '密码', exact: false }, value: '123456' },
    { id: 4, desc: '点击登录', action: 'click', locator: { by: 'text', value: '登录', exact: false } },
    { id: 5, desc: '等待登录完成', action: 'wait', ms: 1500 },
    { id: 6, desc: '导航到薪资管理页', action: 'navigate', to: '/payroll' },
    { id: 7, desc: '点击新增薪资周期', action: 'click', locator: { by: 'text', value: '新增周期', exact: false } },
    { id: 8, desc: '选择月份', action: 'fill', locator: { by: 'label', value: '月份', exact: false }, value: '{{current_month}}' },
    { id: 9, desc: '点击确认', action: 'click', locator: { by: 'text', value: '确认', exact: false } },
    { id: 10, desc: '断言创建成功', action: 'assert', check: { type: 'toast_contains', value: '创建成功' } },
    { id: 11, desc: '点击开启确认窗口', action: 'click', locator: { by: 'text', value: '开启窗口', exact: false } },
    { id: 12, desc: '点击预检', action: 'click', locator: { by: 'text', value: '预检', exact: false } },
    { id: 13, desc: '断言预检通过', action: 'assert', check: { type: 'toast_contains', value: '预检通过' } },
    { id: 14, desc: '点击结算', action: 'click', locator: { by: 'text', value: '结算', exact: false } },
    { id: 15, desc: '等待结算完成', action: 'wait', ms: 3000 },
    { id: 16, desc: '断言结算成功', action: 'assert', check: { type: 'text_visible', value: '结算完成' } },
    { id: 17, desc: '点击发布', action: 'click', locator: { by: 'text', value: '发布', exact: false } },
    { id: 18, desc: '断言发布成功', action: 'assert', check: { type: 'toast_contains', value: '发布成功' } },
    { id: 19, desc: '退出登录', action: 'click', locator: { by: 'text', value: '退出', exact: false } },
    { id: 20, desc: '员工登录', action: 'fill', locator: { by: 'label', value: '用户名', exact: false }, value: 'employee.demo' },
    { id: 21, desc: '输入密码', action: 'fill', locator: { by: 'label', value: '密码', exact: false }, value: '123456' },
    { id: 22, desc: '点击登录', action: 'click', locator: { by: 'text', value: '登录', exact: false } },
    { id: 23, desc: '等待登录完成', action: 'wait', ms: 1500 },
    { id: 24, desc: '导航到工资条页', action: 'navigate', to: '/payroll/slip' },
    { id: 25, desc: '点击工资条记录', action: 'click', locator: { by: 'css', value: '.payroll-slip-row' } },
    { id: 26, desc: '输入 PIN 码', action: 'fill', locator: { by: 'label', value: 'PIN', exact: false }, value: '123456' },
    { id: 27, desc: '点击确认', action: 'click', locator: { by: 'text', value: '确认', exact: false } },
    { id: 28, desc: '断言确认成功', action: 'assert', check: { type: 'toast_contains', value: '确认成功' } },
    { id: 29, desc: '断言状态变为已确认', action: 'assert', check: { type: 'text_visible', value: '已确认' } },
  ],
  expect: { result: 'pass' },
} satisfies TestCase;
