import type { TestCase } from '../../../../tools/autotest/runner/types.js';

export default {
  id: 'TC-SYS-10',
  title: '主链路 E2E：员工请假 → PM 审批 → 状态 APPROVED → 员工收通知',
  module: 'system',
  priority: 'P0',
  tags: ['smoke'],
  steps: [
    { id: 1, desc: '员工登录', action: 'navigate', to: '/login' },
    { id: 2, desc: '输入员工用户名', action: 'fill', locator: { by: 'label', value: '用户名', exact: false }, value: 'employee.demo' },
    { id: 3, desc: '输入密码', action: 'fill', locator: { by: 'label', value: '密码', exact: false }, value: '123456' },
    { id: 4, desc: '点击登录', action: 'click', locator: { by: 'text', value: '登录', exact: false } },
    { id: 5, desc: '等待登录完成', action: 'wait', ms: 1500 },
    { id: 6, desc: '导航到请假申请页', action: 'navigate', to: '/attendance/leave' },
    { id: 7, desc: '点击新增请假', action: 'click', locator: { by: 'text', value: '新增请假', exact: false } },
    { id: 8, desc: '选择请假类型', action: 'select', locator: { by: 'label', value: '请假类型', exact: false }, value: 'annual' },
    { id: 9, desc: '填写开始时间', action: 'fill', locator: { by: 'label', value: '开始时间', exact: false }, value: '{{tomorrow}}' },
    { id: 10, desc: '填写结束时间', action: 'fill', locator: { by: 'label', value: '结束时间', exact: false }, value: '{{day_after_tomorrow}}' },
    { id: 11, desc: '填写原因', action: 'fill', locator: { by: 'label', value: '原因', exact: false }, value: 'E2E测试请假' },
    { id: 12, desc: '点击提交', action: 'click', locator: { by: 'text', value: '提交', exact: false } },
    { id: 13, desc: '断言提交成功', action: 'assert', check: { type: 'toast_contains', value: '提交成功' } },
    { id: 14, desc: '退出登录', action: 'click', locator: { by: 'text', value: '退出', exact: false } },
    { id: 15, desc: 'PM 登录', action: 'fill', locator: { by: 'label', value: '用户名', exact: false }, value: 'pm.demo' },
    { id: 16, desc: '输入密码', action: 'fill', locator: { by: 'label', value: '密码', exact: false }, value: '123456' },
    { id: 17, desc: '点击登录', action: 'click', locator: { by: 'text', value: '登录', exact: false } },
    { id: 18, desc: '等待登录完成', action: 'wait', ms: 1500 },
    { id: 19, desc: '导航到待办页', action: 'navigate', to: '/todos' },
    { id: 20, desc: '点击审批通过', action: 'click', locator: { by: 'text', value: '通过', exact: false } },
    { id: 21, desc: '断言审批成功', action: 'assert', check: { type: 'toast_contains', value: '审批成功' } },
    { id: 22, desc: '退出登录', action: 'click', locator: { by: 'text', value: '退出', exact: false } },
    { id: 23, desc: '员工再次登录', action: 'fill', locator: { by: 'label', value: '用户名', exact: false }, value: 'employee.demo' },
    { id: 24, desc: '输入密码', action: 'fill', locator: { by: 'label', value: '密码', exact: false }, value: '123456' },
    { id: 25, desc: '点击登录', action: 'click', locator: { by: 'text', value: '登录', exact: false } },
    { id: 26, desc: '等待登录完成', action: 'wait', ms: 1500 },
    { id: 27, desc: '导航到通知中心', action: 'navigate', to: '/notifications' },
    { id: 28, desc: '断言收到请假审批通知', action: 'assert', check: { type: 'text_visible', value: '请假' } },
    { id: 29, desc: '断言状态为已通过', action: 'assert', check: { type: 'text_visible', value: '已通过' } },
  ],
  expect: { result: 'pass' },
} satisfies TestCase;
