import type { TestCase } from '../../../../tools/autotest/runner/types.js';

export default {
  id: 'TC-SYS-12',
  title: '主链路 E2E：劳工提交施工日志 → PM 审批通过',
  module: 'system',
  priority: 'P0',
  tags: ['smoke'],
  steps: [
    { id: 1, desc: '劳工登录', action: 'navigate', to: '/login' },
    { id: 2, desc: '输入劳工用户名', action: 'fill', locator: { by: 'label', value: '用户名', exact: false }, value: 'worker.demo' },
    { id: 3, desc: '输入密码', action: 'fill', locator: { by: 'label', value: '密码', exact: false }, value: '123456' },
    { id: 4, desc: '点击登录', action: 'click', locator: { by: 'text', value: '登录', exact: false } },
    { id: 5, desc: '等待登录完成', action: 'wait', ms: 1500 },
    { id: 6, desc: '导航到施工日志页', action: 'navigate', to: '/construction/logs' },
    { id: 7, desc: '点击新增施工日志', action: 'click', locator: { by: 'text', value: '新增日志', exact: false } },
    { id: 8, desc: '填写日期', action: 'fill', locator: { by: 'label', value: '日期', exact: false }, value: '{{today}}' },
    { id: 9, desc: '填写工程内容', action: 'fill', locator: { by: 'label', value: '工程内容', exact: false }, value: 'E2E测试施工内容' },
    { id: 10, desc: '填写工时', action: 'fill', locator: { by: 'label', value: '工时', exact: false }, value: '8' },
    { id: 11, desc: '点击提交', action: 'click', locator: { by: 'text', value: '提交', exact: false } },
    { id: 12, desc: '断言提交成功', action: 'assert', check: { type: 'toast_contains', value: '提交成功' } },
    { id: 13, desc: '退出登录', action: 'click', locator: { by: 'text', value: '退出', exact: false } },
    { id: 14, desc: 'PM 登录', action: 'fill', locator: { by: 'label', value: '用户名', exact: false }, value: 'pm.demo' },
    { id: 15, desc: '输入密码', action: 'fill', locator: { by: 'label', value: '密码', exact: false }, value: '123456' },
    { id: 16, desc: '点击登录', action: 'click', locator: { by: 'text', value: '登录', exact: false } },
    { id: 17, desc: '等待登录完成', action: 'wait', ms: 1500 },
    { id: 18, desc: '导航到施工日志审批页', action: 'navigate', to: '/construction/pending' },
    { id: 19, desc: '点击审批通过', action: 'click', locator: { by: 'text', value: '通过', exact: false } },
    { id: 20, desc: '输入审批意见', action: 'fill', locator: { by: 'label', value: '审批意见', exact: false }, value: 'E2E测试通过' },
    { id: 21, desc: '点击确认', action: 'click', locator: { by: 'text', value: '确认', exact: false } },
    { id: 22, desc: '断言审批成功', action: 'assert', check: { type: 'toast_contains', value: '审批成功' } },
  ],
  expect: { result: 'pass' },
} satisfies TestCase;
