/**
 * Payroll module test cases — TC-PAY-01 ~ TC-PAY-18
 * Scope: cycle creation, pre-check, settle, confirm by employee, PIN sign, permissions
 */
import type { TestCase } from '../../../../tools/autotest/runner/types.js';
import { loginSteps, USERS } from '../_helpers.js';

const cases: TestCase[] = [
  {
    id: 'TC-PAY-01',
    title: '财务创建新薪资周期',
    description: '角色：Finance。路径：/payroll → 周期管理 → "创建周期" → 选择月份 → 保存。期望：列表出现新周期。',
    module: 'payroll',
    priority: 'P0',
    roles: ['finance'],
    credentials: USERS.finance,
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      { id: 6, desc: '访问 /payroll', action: 'navigate', to: '/payroll' },
      { id: 7, desc: '切换到"周期管理" tab', action: 'click', locator: { by: 'role', role: 'tab', name: '周期管理' } },
      { id: 8, desc: '点击"创建周期"', action: 'click', locator: { by: 'role', role: 'button', name: '+ 创建周期' } },
      { id: 9, desc: '输入周期', action: 'fill', locator: { by: 'label', value: '周期（格式：YYYY-MM）' }, value: '2026-04' },
      { id: 10, desc: '点击 Modal 确定', action: 'click', locator: { by: 'catch', value: 'payroll-cycle-create-ok' } },
      { id: 11, desc: '列表出现 2026-04', action: 'assert', check: { type: 'text_visible', value: '2026-04' } },
    ],
    expect: { result: 'pass', url: '/payroll' },
  },
  {
    id: 'TC-PAY-02',
    title: '开启工资条确认窗口',
    description: '角色：Finance。路径：/payroll → 周期管理 → 某周期"开启窗口"。期望：状态变为 WINDOW_OPEN，员工可见。',
    module: 'payroll',
    priority: 'P0',
    roles: ['finance'],
    credentials: USERS.finance,
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      { id: 6, desc: '访问 /payroll', action: 'navigate', to: '/payroll' },
      { id: 7, desc: '切换到"周期管理"', action: 'click', locator: { by: 'role', role: 'tab', name: '周期管理' } },
      { id: 8, desc: '点击某周期"开启窗口"', action: 'click', locator: { by: 'catch', value: 'payroll-cycle-open-btn-test' } },
      { id: 9, desc: '出现开启成功提示', action: 'assert', check: { type: 'toast_contains', value: '开启' } },
    ],
    expect: { result: 'pass', url: '/payroll' },
  },
  {
    id: 'TC-PAY-03',
    title: '预检通过',
    description: '角色：Finance。路径：/payroll → 结算操作 → 选择周期 → 点击"预检"。期望：显示无异常，可发起结算。',
    module: 'payroll',
    priority: 'P0',
    roles: ['finance'],
    credentials: USERS.finance,
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      { id: 6, desc: '访问 /payroll', action: 'navigate', to: '/payroll' },
      { id: 7, desc: '切换到"结算操作"', action: 'click', locator: { by: 'role', role: 'tab', name: '结算操作' } },
      { id: 8, desc: '选择周期下拉', action: 'click', locator: { by: 'label', value: '选择周期' } },
      { id: 9, desc: '选择周期项', action: 'click', locator: { by: 'catch', value: 'payroll-settle-cycle-option-latest' } },
      { id: 10, desc: '点击"预检"', action: 'click', locator: { by: 'catch', value: 'payroll-settle-precheck-btn' } },
      { id: 11, desc: '预检成功提示', action: 'assert', check: { type: 'toast_contains', value: '预检' } },
    ],
    expect: { result: 'pass', url: '/payroll' },
  },
  {
    id: 'TC-PAY-04',
    title: '发起结算生成工资条',
    description: '角色：Finance。路径：/payroll → 结算操作 → 点击"发起结算"。期望：员工工资条生成，状态可查询。',
    module: 'payroll',
    priority: 'P0',
    roles: ['finance'],
    credentials: USERS.finance,
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      { id: 6, desc: '访问 /payroll', action: 'navigate', to: '/payroll' },
      { id: 7, desc: '结算 tab', action: 'click', locator: { by: 'role', role: 'tab', name: '结算操作' } },
      { id: 8, desc: '点击"发起结算"', action: 'click', locator: { by: 'catch', value: 'payroll-settle-run-btn' } },
      { id: 9, desc: '成功提示', action: 'assert', check: { type: 'toast_contains', value: '结算' } },
    ],
    expect: { result: 'pass', url: '/payroll' },
  },
  {
    id: 'TC-PAY-05',
    title: '财务发布工资条',
    description: '角色：Finance。路径：/payroll → 周期管理 → "发布"操作。期望：工资条对员工可见。',
    module: 'payroll',
    priority: 'P0',
    roles: ['finance'],
    credentials: USERS.finance,
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      { id: 6, desc: '访问 /payroll', action: 'navigate', to: '/payroll' },
      { id: 7, desc: '周期管理 tab', action: 'click', locator: { by: 'role', role: 'tab', name: '周期管理' } },
      { id: 8, desc: '点击某周期"发布"', action: 'click', locator: { by: 'catch', value: 'payroll-cycle-publish-btn-test' } },
      { id: 9, desc: '成功提示', action: 'assert', check: { type: 'toast_contains', value: '发布' } },
    ],
    expect: { result: 'pass', url: '/payroll' },
  },
  {
    id: 'TC-PAY-06',
    title: '员工输入 PIN 确认工资条',
    description: '角色：Employee。路径：/payroll 工资条查看 → 打开详情 → 点击"确认收到" → 输入 PIN → 确认。期望：状态变 SIGNED。',
    module: 'payroll',
    priority: 'P0',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /payroll', action: 'navigate', to: '/payroll' },
      { id: 7, desc: '切换到工资条查看', action: 'click', locator: { by: 'role', role: 'tab', name: '工资条查看' } },
      { id: 8, desc: '打开第一条详情', action: 'click', locator: { by: 'catch', value: 'payroll-slip-row-detail-btn-latest' } },
      { id: 9, desc: '点击"确认收到"', action: 'click', locator: { by: 'role', role: 'button', name: '确认收到' } },
      { id: 10, desc: '输入 PIN', action: 'fill', locator: { by: 'label', value: 'PIN 码' }, value: '123456' },
      { id: 11, desc: '点击确认', action: 'click', locator: { by: 'catch', value: 'payroll-sign-confirm-btn' } },
      { id: 12, desc: '出现成功提示', action: 'assert', check: { type: 'toast_contains', value: '确认' } },
    ],
    expect: { result: 'pass', url: '/payroll' },
  },
  {
    id: 'TC-PAY-07',
    title: '员工查看历史工资条列表',
    description: '角色：Employee。路径：/payroll → 工资条查看 → 列表。期望：显示历史工资条记录。',
    module: 'payroll',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /payroll', action: 'navigate', to: '/payroll' },
      { id: 7, desc: '工资条查看 tab', action: 'click', locator: { by: 'role', role: 'tab', name: '工资条查看' } },
      { id: 8, desc: '列表容器可见', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'payroll-my-slips-list' } } },
    ],
    expect: { result: 'pass', url: '/payroll' },
  },
  {
    id: 'TC-PAY-08',
    title: '工资条 PDF 导出',
    description: '角色：Employee。路径：/payroll 工资条详情 → 导出 PDF。期望：下载链接返回 PDF 或 API 返回 200。',
    module: 'payroll',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '通过 API 导出', action: 'api_call', method: 'GET', endpoint: '/api/payroll/slips/latest/pdf' },
      { id: 7, desc: '截图记录', action: 'screenshot', label: 'pdf-export' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-PAY-09',
    title: '社保模式切换影响计算',
    description: '角色：Finance。路径：修改社保模式（正常分摊 / 公司全额）→ 重新结算。期望：工资条计算结果对应变化。',
    module: 'payroll',
    priority: 'P1',
    roles: ['finance'],
    credentials: USERS.finance,
    tags: ['api-only'],
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      { id: 6, desc: '切换社保模式 API', action: 'api_call', method: 'POST', endpoint: '/api/payroll/config/social-mode', body: { mode: 'COMPANY_FULL' } },
      { id: 7, desc: '重新结算', action: 'api_call', method: 'POST', endpoint: '/api/payroll/cycles/latest/settle', body: {} },
      { id: 8, desc: '查询工资条差值', action: 'api_call', method: 'GET', endpoint: '/api/payroll/slips/latest' },
      { id: 9, desc: '截图记录', action: 'screenshot', label: 'social-mode-switch' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-PAY-10',
    title: '财务查看全体员工工资条',
    description: '角色：Finance。路径：/payroll → 工资条查看 → 选择周期 → 查询。期望：表格列出所有员工工资条。',
    module: 'payroll',
    priority: 'P1',
    roles: ['finance'],
    credentials: USERS.finance,
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      { id: 6, desc: '访问 /payroll', action: 'navigate', to: '/payroll' },
      { id: 7, desc: '工资条查看 tab', action: 'click', locator: { by: 'role', role: 'tab', name: '工资条查看' } },
      { id: 8, desc: '选择周期', action: 'click', locator: { by: 'catch', value: 'payroll-slips-cycle-select' } },
      { id: 9, desc: '选择最新周期', action: 'click', locator: { by: 'catch', value: 'payroll-slips-cycle-option-latest' } },
      { id: 10, desc: '点击查询', action: 'click', locator: { by: 'role', role: 'button', name: '查询' } },
      { id: 11, desc: '表格可见', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'payroll-all-slips-table' } } },
    ],
    expect: { result: 'pass', url: '/payroll' },
  },
  {
    id: 'TC-PAY-11',
    title: '预检存在 PENDING_REVIEW 异议单',
    description: '角色：Finance。路径：预检时有异议单。期望：预检失败，提示原因。',
    module: 'payroll',
    priority: 'P0',
    roles: ['finance'],
    credentials: USERS.finance,
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      { id: 6, desc: '设置异议单状态（setup）', action: 'api_call', method: 'POST', endpoint: '/api/dev/create-pending-review-dispute', body: {} },
      { id: 7, desc: '触发预检', action: 'api_call', method: 'POST', endpoint: '/api/payroll/cycles/latest/precheck', body: {} },
      { id: 8, desc: '截图记录', action: 'screenshot', label: 'pending-review-precheck' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-PAY-12',
    title: '预检存在 CALCULATING 并行周期',
    description: '角色：Finance。路径：已有 CALCULATING 周期再触发预检。期望：预检失败。',
    module: 'payroll',
    priority: 'P0',
    roles: ['finance'],
    credentials: USERS.finance,
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      { id: 6, desc: '触发预检 API', action: 'api_call', method: 'POST', endpoint: '/api/payroll/cycles/latest/precheck', body: {} },
      { id: 7, desc: '同时运行另一周期', action: 'api_call', method: 'POST', endpoint: '/api/payroll/cycles/other/settle', body: {} },
      { id: 8, desc: '截图记录', action: 'screenshot', label: 'parallel-calc' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-PAY-13',
    title: '窗口未关闭时重复结算',
    description: '角色：Finance。路径：短时间重复点击"发起结算"。期望：第二次被拒绝或提示"结算进行中"。',
    module: 'payroll',
    priority: 'P1',
    roles: ['finance'],
    credentials: USERS.finance,
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      { id: 6, desc: '访问 /payroll', action: 'navigate', to: '/payroll' },
      { id: 7, desc: '结算 tab', action: 'click', locator: { by: 'role', role: 'tab', name: '结算操作' } },
      { id: 8, desc: '连续点击发起结算两次', action: 'rapid', repeat: 2, interval: 200, step: { id: 0, desc: '点击发起结算', action: 'click', locator: { by: 'catch', value: 'payroll-settle-run-btn' } } },
      { id: 9, desc: '应出现重复提示或加载中', action: 'screenshot', label: 'duplicate-settle' },
    ],
    expect: { result: 'pass', url: '/payroll' },
  },
  {
    id: 'TC-PAY-14',
    title: '员工输入错误 PIN',
    description: '角色：Employee。路径：工资条确认 → PIN 输入错误 → 确认。期望：提示 PIN 错误，拒绝确认。',
    module: 'payroll',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /payroll', action: 'navigate', to: '/payroll' },
      { id: 7, desc: '工资条查看', action: 'click', locator: { by: 'role', role: 'tab', name: '工资条查看' } },
      { id: 8, desc: '打开详情', action: 'click', locator: { by: 'catch', value: 'payroll-slip-row-detail-btn-latest' } },
      { id: 9, desc: '确认收到', action: 'click', locator: { by: 'role', role: 'button', name: '确认收到' } },
      { id: 10, desc: '输入错误 PIN', action: 'fill', locator: { by: 'label', value: 'PIN 码' }, value: '000000' },
      { id: 11, desc: '点击确认', action: 'click', locator: { by: 'catch', value: 'payroll-sign-confirm-btn' } },
      { id: 12, desc: '出现 PIN 错误提示', action: 'assert', check: { type: 'toast_contains', value: 'PIN' } },
    ],
    expect: { result: 'pass', url: '/payroll' },
  },
  {
    id: 'TC-PAY-15',
    title: 'CEO 越权访问 /payroll/settle',
    description: '角色：CEO。路径：直接访问 /payroll。期望：跳转或无"结算操作"权限。',
    module: 'payroll',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    tags: ['permission'],
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /payroll', action: 'navigate', to: '/payroll' },
      { id: 7, desc: '结算操作按钮不应可见（应仅 Finance）', action: 'assert', check: { type: 'text_absent', value: '发起结算' } },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-PAY-16',
    title: '员工访问财务薪资管理被拦截',
    description: '角色：Employee。路径：API 访问 /api/payroll/cycles。期望：返回 403。',
    module: 'payroll',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    tags: ['api-only', 'permission'],
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '调用 GET /api/payroll/cycles', action: 'api_call', method: 'GET', endpoint: '/api/payroll/cycles' },
      { id: 7, desc: '截图记录 403', action: 'screenshot', label: 'employee-forbidden' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-PAY-17',
    title: '两个财务并发对同一周期发起结算',
    description: '并发。路径：parallel finance.demo 两次对同一 cycleId 发起结算。期望：只有一次真正执行，另一次拒绝。',
    module: 'payroll',
    priority: 'P1',
    roles: ['finance'],
    tags: ['concurrency'],
    steps: [
      {
        id: 1,
        desc: '并行发起两次结算',
        action: 'parallel',
        contexts: [
          [
            ...loginSteps(USERS.finance.username, USERS.finance.password, 1),
            { id: 6, desc: '会话 A settle', action: 'api_call', method: 'POST', endpoint: '/api/payroll/cycles/latest/settle', body: {} },
          ],
          [
            ...loginSteps(USERS.finance.username, USERS.finance.password, 1),
            { id: 6, desc: '会话 B settle', action: 'api_call', method: 'POST', endpoint: '/api/payroll/cycles/latest/settle', body: {} },
          ],
        ],
      },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-PAY-18',
    title: '员工与财务并发操作同一工资条',
    description: '并发。路径：parallel 员工 PIN 确认 + 财务撤回。期望：按时序决定最终状态，无数据错乱。',
    module: 'payroll',
    priority: 'P2',
    roles: ['employee', 'finance'],
    tags: ['concurrency'],
    steps: [
      {
        id: 1,
        desc: '员工与财务并发操作',
        action: 'parallel',
        contexts: [
          [
            ...loginSteps(USERS.employee.username, USERS.employee.password, 1),
            { id: 6, desc: '员工 PIN 确认', action: 'api_call', method: 'POST', endpoint: '/api/payroll/slips/latest/confirm', body: { pin: '123456' } },
          ],
          [
            ...loginSteps(USERS.finance.username, USERS.finance.password, 1),
            { id: 6, desc: '财务撤回工资条', action: 'api_call', method: 'POST', endpoint: '/api/payroll/slips/latest/withdraw', body: {} },
          ],
        ],
      },
    ],
    expect: { result: 'pass' },
  },
];

export default cases;
