/**
 * Position module test cases — TC-POS-01 ~ TC-POS-09
 * Scope: position CRUD, level config, role-based permissions
 */
import type { TestCase } from '../../../../tools/autotest/runner/types.js';
import { loginSteps, USERS } from '../_helpers.js';

const cases: TestCase[] = [
  {
    id: 'TC-POS-01',
    title: 'CEO 创建新岗位',
    description: '角色：CEO。路径：登录 → /positions → 点击"新增岗位" → 填写名称 → 提交。期望：列表出现新岗位。',
    module: 'position',
    priority: 'P0',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问岗位管理页', action: 'navigate', to: '/positions' },
      { id: 7, desc: '点击"新增岗位"', action: 'click', locator: { by: 'catch', value: 'positions-list-create-btn' } },
      { id: 8, desc: '输入岗位名称', action: 'fill', locator: { by: 'label', value: '岗位名称' }, value: '测试岗位自动化' },
      { id: 9, desc: '选择员工类别', action: 'click', locator: { by: 'label', value: '员工类别' } },
      { id: 10, desc: '选择"正式员工"', action: 'click', locator: { by: 'text', value: '正式员工', exact: true } },
      { id: 11, desc: '点击保存', action: 'click', locator: { by: 'catch', value: 'positions-modal-save-btn' } },
      { id: 12, desc: '列表出现新岗位', action: 'assert', check: { type: 'text_visible', value: '测试岗位自动化' } },
    ],
    expect: { result: 'pass', url: '/positions' },
  },
  {
    id: 'TC-POS-02',
    title: '为岗位创建初级/中级/高级三个等级',
    description: '角色：CEO。路径：/positions → 选中岗位 → 点击"新增等级" → 填写名称和工资 → 保存。重复 3 次。期望：等级表格显示三条记录。',
    module: 'position',
    priority: 'P0',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问岗位管理页', action: 'navigate', to: '/positions' },
      { id: 7, desc: '展开某岗位等级区', action: 'click', locator: { by: 'catch', value: 'positions-row-expand-btn-test' } },
      { id: 8, desc: '点击"新增等级"', action: 'click', locator: { by: 'catch', value: 'positions-levels-create-btn-test' } },
      { id: 9, desc: '输入等级名称"初级"', action: 'fill', locator: { by: 'label', value: '等级名称' }, value: '初级' },
      { id: 10, desc: '输入基本工资', action: 'fill', locator: { by: 'label', value: '基本工资' }, value: '6000' },
      { id: 11, desc: '保存等级', action: 'click', locator: { by: 'catch', value: 'positions-level-modal-save-btn' } },
      { id: 12, desc: '等级表格出现"初级"', action: 'assert', check: { type: 'text_visible', value: '初级' } },
    ],
    expect: { result: 'pass', url: '/positions' },
  },
  {
    id: 'TC-POS-03',
    title: '新建员工时岗位下拉可选到新岗位',
    description: '角色：HR。路径：员工新建表单。期望：岗位下拉包含上一步创建的"测试岗位自动化"（通过 API 验证返回列表）。',
    module: 'position',
    priority: 'P0',
    roles: ['hr'],
    credentials: USERS.hr,
    tags: ['api-only'],
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '调用 GET /api/positions', action: 'api_call', method: 'GET', endpoint: '/api/positions' },
      { id: 7, desc: '人工核对返回列表包含"测试岗位自动化"', action: 'screenshot', label: 'positions-list-api' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-POS-04',
    title: '编辑岗位名称',
    description: '角色：CEO。路径：/positions → 某行"编辑" → 修改名称 → 保存。期望：列表显示新名称。',
    module: 'position',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /positions', action: 'navigate', to: '/positions' },
      { id: 7, desc: '点击某行编辑', action: 'click', locator: { by: 'catch', value: 'positions-row-edit-btn-test' } },
      { id: 8, desc: '清除原名称', action: 'fill', locator: { by: 'label', value: '岗位名称' }, value: '' },
      { id: 9, desc: '输入新名称', action: 'fill', locator: { by: 'label', value: '岗位名称' }, value: '岗位已重命名' },
      { id: 10, desc: '保存', action: 'click', locator: { by: 'catch', value: 'positions-modal-save-btn' } },
      { id: 11, desc: '列表显示新名称', action: 'assert', check: { type: 'text_visible', value: '岗位已重命名' } },
    ],
    expect: { result: 'pass', url: '/positions' },
  },
  {
    id: 'TC-POS-05',
    title: '编辑等级薪资金额',
    description: '角色：CEO。路径：/positions → 展开岗位 → 某等级"编辑" → 改基本工资 → 保存。期望：列表显示新金额。',
    module: 'position',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /positions', action: 'navigate', to: '/positions' },
      { id: 7, desc: '展开岗位', action: 'click', locator: { by: 'catch', value: 'positions-row-expand-btn-test' } },
      { id: 8, desc: '点击某等级编辑', action: 'click', locator: { by: 'catch', value: 'positions-level-row-edit-btn-test' } },
      { id: 9, desc: '清除基本工资', action: 'fill', locator: { by: 'label', value: '基本工资' }, value: '' },
      { id: 10, desc: '输入新基本工资', action: 'fill', locator: { by: 'label', value: '基本工资' }, value: '9999' },
      { id: 11, desc: '保存', action: 'click', locator: { by: 'catch', value: 'positions-level-modal-save-btn' } },
      { id: 12, desc: '列表显示新金额', action: 'assert', check: { type: 'text_visible', value: '9999' } },
    ],
    expect: { result: 'pass', url: '/positions' },
  },
  {
    id: 'TC-POS-06',
    title: '删除无人员关联的岗位',
    description: '角色：CEO。路径：/positions → 某无人关联岗位"删除" → 确认。期望：列表不再显示该岗位。',
    module: 'position',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /positions', action: 'navigate', to: '/positions' },
      { id: 7, desc: '点击某无关联岗位"删除"', action: 'click', locator: { by: 'catch', value: 'positions-row-delete-btn-test' } },
      { id: 8, desc: '确认删除', action: 'click', locator: { by: 'text', value: '确定', exact: true } },
      { id: 9, desc: '出现删除成功提示', action: 'assert', check: { type: 'toast_contains', value: '删除成功' } },
    ],
    expect: { result: 'pass', url: '/positions' },
  },
  {
    id: 'TC-POS-07',
    title: '岗位名称为空时创建失败',
    description: '角色：CEO。路径：/positions → 新增岗位 → 名称留空 → 保存。期望：表单必填校验提示。',
    module: 'position',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /positions', action: 'navigate', to: '/positions' },
      { id: 7, desc: '点击"新增岗位"', action: 'click', locator: { by: 'catch', value: 'positions-list-create-btn' } },
      { id: 8, desc: '直接点击保存（不填名称）', action: 'click', locator: { by: 'catch', value: 'positions-modal-save-btn' } },
      { id: 9, desc: '出现必填校验提示', action: 'assert', check: { type: 'text_visible', value: '请' } },
    ],
    expect: { result: 'pass', url: '/positions' },
  },
  {
    id: 'TC-POS-08',
    title: '删除有员工关联的岗位失败',
    description: '角色：CEO。路径：/positions → 选择有员工关联的岗位"删除" → 确认。期望：提示无法删除或 409。',
    module: 'position',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /positions', action: 'navigate', to: '/positions' },
      { id: 7, desc: '点击有关联岗位"删除"', action: 'click', locator: { by: 'catch', value: 'positions-row-delete-btn-inuse' } },
      { id: 8, desc: '确认删除', action: 'click', locator: { by: 'text', value: '确定', exact: true } },
      { id: 9, desc: '出现错误提示', action: 'assert', check: { type: 'toast_contains', value: '无法删除' } },
    ],
    expect: { result: 'pass', url: '/positions' },
  },
  {
    id: 'TC-POS-09',
    title: 'HR 账号无法删除岗位',
    description: '角色：HR。路径：/positions。期望：列表加载但行操作列不显示"删除"按钮（按钮 v-if="isCEO"）。',
    module: 'position',
    priority: 'P1',
    roles: ['hr'],
    credentials: USERS.hr,
    tags: ['permission'],
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '访问 /positions', action: 'navigate', to: '/positions' },
      { id: 7, desc: '"新增岗位"按钮不应可见', action: 'assert', check: { type: 'text_absent', value: '新增岗位' } },
      { id: 8, desc: '"新增等级"按钮不应可见', action: 'assert', check: { type: 'text_absent', value: '新增等级' } },
    ],
    expect: { result: 'pass', url: '/positions' },
  },
];

export default cases;
