/**
 * Overtime module test cases — TC-OT-01 ~ TC-OT-07
 * Scope: overtime declaration, self-report, approval, history, validation
 */
import type { TestCase } from '../../../../tools/autotest/runner/types.js';
import { loginSteps, USERS } from '../_helpers.js';

const cases: TestCase[] = [
  {
    id: 'TC-OT-01',
    title: '员工提交加班申报状态直接通过',
    description: '角色：员工。路径：登录 → /attendance → 加班申报 → 填写并提交。期望：记录出现在我的记录中且状态为已通过。',
    module: 'overtime',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /attendance', action: 'navigate', to: '/attendance' },
      { id: 7, desc: '点击加班申报标签', action: 'click', locator: { by: 'text', value: '加班申报', exact: true } },
      { id: 8, desc: '填写加班日期', action: 'fill', locator: { by: 'label', value: '加班日期' }, value: '2024-01-15' },
      { id: 9, desc: '填写开始时间', action: 'fill', locator: { by: 'label', value: '开始时间' }, value: '18:00' },
      { id: 10, desc: '填写结束时间', action: 'fill', locator: { by: 'label', value: '结束时间' }, value: '20:00' },
      { id: 11, desc: '点击加班类型下拉', action: 'click', locator: { by: 'label', value: '加班类型' } },
      { id: 12, desc: '选择周末加班', action: 'click', locator: { by: 'text', value: '周末加班', exact: true } },
      { id: 13, desc: '填写说明', action: 'fill', locator: { by: 'label', value: '说明' }, value: '项目紧急加班' },
      { id: 14, desc: '点击提交申报', action: 'click', locator: { by: 'catch', value: 'attendance-overtime-submit' } },
      { id: 15, desc: '记录状态显示已通过', action: 'assert', check: { type: 'text_visible', value: '已通过' } },
    ],
    expect: { result: 'pass', url: '/attendance' },
  },
  {
    id: 'TC-OT-02',
    title: '员工提交加班补申报',
    description: '角色：员工。路径：/attendance → 自补加班 → 填写并提交。期望：提交成功，记录状态为审批中。',
    module: 'overtime',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /attendance', action: 'navigate', to: '/attendance' },
      { id: 7, desc: '点击自补加班标签', action: 'click', locator: { by: 'text', value: '自补加班', exact: true } },
      { id: 8, desc: '填写加班日期', action: 'fill', locator: { by: 'label', value: '加班日期' }, value: '2024-01-16' },
      { id: 9, desc: '填写开始时间', action: 'fill', locator: { by: 'label', value: '开始时间' }, value: '19:00' },
      { id: 10, desc: '填写结束时间', action: 'fill', locator: { by: 'label', value: '结束时间' }, value: '21:00' },
      { id: 11, desc: '点击加班类型下拉', action: 'click', locator: { by: 'label', value: '加班类型' } },
      { id: 12, desc: '选择工作日加班', action: 'click', locator: { by: 'text', value: '工作日加班', exact: true } },
      { id: 13, desc: '填写补申报原因', action: 'fill', locator: { by: 'label', value: '补申报原因' }, value: '忘记及时申报' },
      { id: 14, desc: '点击提交申请', action: 'click', locator: { by: 'catch', value: 'attendance-selfreport-submit' } },
      { id: 15, desc: '记录状态显示审批中', action: 'assert', check: { type: 'text_visible', value: '审批中' } },
    ],
    expect: { result: 'pass', url: '/attendance' },
  },
  {
    id: 'TC-OT-03',
    title: 'PM审批通过加班补申报',
    description: '角色：PM。路径：登录 → /todo → 考勤审批 → 查看审批 → 通过。期望：审批成功，待办列表不再显示该记录。',
    module: 'overtime',
    priority: 'P1',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问 /todo', action: 'navigate', to: '/todo' },
      { id: 7, desc: '点击考勤审批标签', action: 'click', locator: { by: 'text', value: '考勤审批', exact: true } },
      { id: 8, desc: '点击查看审批', action: 'click', locator: { by: 'text', value: '查看审批' } },
      { id: 9, desc: '点击通过按钮', action: 'click', locator: { by: 'role', role: 'button', name: '通过' } },
      { id: 10, desc: '审批弹窗已关闭', action: 'assert', check: { type: 'element_hidden', locator: { by: 'role', role: 'button', name: '通过' } } },
    ],
    expect: { result: 'pass', url: '/todo' },
  },
  {
    id: 'TC-OT-04',
    title: '加班记录在考勤历史中正确显示',
    description: '角色：员工。路径：登录 → /attendance → 我的记录。期望：列表显示加班记录，包含日期、类型、状态字段。',
    module: 'overtime',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /attendance', action: 'navigate', to: '/attendance' },
      { id: 7, desc: '页面显示我的记录', action: 'assert', check: { type: 'text_visible', value: '我的记录' } },
      { id: 8, desc: '列表包含加班类型', action: 'assert', check: { type: 'text_visible', value: '加班' } },
      { id: 9, desc: '列表包含已通过状态', action: 'assert', check: { type: 'text_visible', value: '已通过' } },
    ],
    expect: { result: 'pass', url: '/attendance' },
  },
  {
    id: 'TC-OT-05',
    title: '加班结束时间早于开始时间校验',
    description: '角色：员工。路径：/attendance → 加班申报 → 结束时间早于开始时间 → 提交。期望：表单校验或后端报错，提交失败。',
    module: 'overtime',
    priority: 'P0',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /attendance', action: 'navigate', to: '/attendance' },
      { id: 7, desc: '点击加班申报标签', action: 'click', locator: { by: 'text', value: '加班申报', exact: true } },
      { id: 8, desc: '填写加班日期', action: 'fill', locator: { by: 'label', value: '加班日期' }, value: '2024-01-17' },
      { id: 9, desc: '填写开始时间（20:00）', action: 'fill', locator: { by: 'label', value: '开始时间' }, value: '20:00' },
      { id: 10, desc: '填写结束时间（18:00）', action: 'fill', locator: { by: 'label', value: '结束时间' }, value: '18:00' },
      { id: 11, desc: '点击加班类型下拉', action: 'click', locator: { by: 'label', value: '加班类型' } },
      { id: 12, desc: '选择节假日加班', action: 'click', locator: { by: 'text', value: '节假日加班', exact: true } },
      { id: 13, desc: '点击提交申报', action: 'click', locator: { by: 'catch', value: 'attendance-overtime-submit' } },
      { id: 14, desc: '等待响应', action: 'wait', ms: 1000 },
      { id: 15, desc: '截图记录校验结果', action: 'screenshot', label: 'ot-time-validation' },
      { id: 16, desc: '提交按钮仍可见（未跳转）', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'attendance-overtime-submit' } } },
    ],
    expect: { result: 'pass', url: '/attendance' },
  },
  {
    id: 'TC-OT-06',
    title: '加班类型未选择校验',
    description: '角色：员工。路径：/attendance → 自补加班 → 不选类型 → 提交。期望：表单校验提示“请选择类型”。',
    module: 'overtime',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /attendance', action: 'navigate', to: '/attendance' },
      { id: 7, desc: '点击自补加班标签', action: 'click', locator: { by: 'text', value: '自补加班', exact: true } },
      { id: 8, desc: '填写加班日期', action: 'fill', locator: { by: 'label', value: '加班日期' }, value: '2024-01-18' },
      { id: 9, desc: '填写开始时间', action: 'fill', locator: { by: 'label', value: '开始时间' }, value: '18:00' },
      { id: 10, desc: '填写结束时间', action: 'fill', locator: { by: 'label', value: '结束时间' }, value: '20:00' },
      { id: 11, desc: '填写补申报原因', action: 'fill', locator: { by: 'label', value: '补申报原因' }, value: '测试类型校验' },
      { id: 12, desc: '点击提交申请', action: 'click', locator: { by: 'catch', value: 'attendance-selfreport-submit' } },
      { id: 13, desc: '显示请选择类型校验提示', action: 'assert', check: { type: 'text_visible', value: '请选择类型' } },
    ],
    expect: { result: 'pass', url: '/attendance' },
  },
  {
    id: 'TC-OT-07',
    title: '申报时间与已有申报重叠校验',
    description: '角色：员工。路径：/attendance → 加班申报 → 填写与已有记录重叠的时间段 → 提交。期望：提示冲突或拒绝。',
    module: 'overtime',
    priority: 'P2',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /attendance', action: 'navigate', to: '/attendance' },
      { id: 7, desc: '点击加班申报标签', action: 'click', locator: { by: 'text', value: '加班申报', exact: true } },
      { id: 8, desc: '填写与已有记录重叠的日期', action: 'fill', locator: { by: 'label', value: '加班日期' }, value: '2024-01-15' },
      { id: 9, desc: '填写开始时间（19:00）', action: 'fill', locator: { by: 'label', value: '开始时间' }, value: '19:00' },
      { id: 10, desc: '填写结束时间（21:00）', action: 'fill', locator: { by: 'label', value: '结束时间' }, value: '21:00' },
      { id: 11, desc: '点击加班类型下拉', action: 'click', locator: { by: 'label', value: '加班类型' } },
      { id: 12, desc: '选择周末加班', action: 'click', locator: { by: 'text', value: '周末加班', exact: true } },
      { id: 13, desc: '点击提交申报', action: 'click', locator: { by: 'catch', value: 'attendance-overtime-submit' } },
      { id: 14, desc: '等待响应', action: 'wait', ms: 1000 },
      { id: 15, desc: '截图记录校验结果', action: 'screenshot', label: 'ot-overlap-validation' },
      { id: 16, desc: '提交按钮仍可见（未跳转）', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'attendance-overtime-submit' } } },
    ],
    expect: { result: 'pass', url: '/attendance' },
  },
];

export default cases;
