/**
 * Role module test cases — TC-ROLE-01 ~ TC-ROLE-09
 * Scope: role list, custom role CRUD, system role protection, permissions
 */
import type { TestCase } from '../../../../tools/autotest/runner/types.js';
import { loginSteps, USERS } from '../_helpers.js';

const cases: TestCase[] = [
  {
    id: 'TC-ROLE-01',
    title: '角色列表展示所有内置角色',
    description: '角色：CEO。路径：登录 → /role。期望：表格显示 CEO/HR/财务/部门经理/项目经理/员工/劳工 等内置角色。',
    module: 'role',
    priority: 'P0',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /role', action: 'navigate', to: '/role' },
      { id: 7, desc: '页面标题"角色管理"可见', action: 'assert', check: { type: 'text_visible', value: '角色管理' } },
      { id: 8, desc: '应显示"CEO"角色行', action: 'assert', check: { type: 'text_visible', value: 'CEO' } },
      { id: 9, desc: '应显示"HR"角色行', action: 'assert', check: { type: 'text_visible', value: 'HR' } },
      { id: 10, desc: '应显示"财务"角色行', action: 'assert', check: { type: 'text_visible', value: '财务' } },
    ],
    expect: { result: 'pass', url: '/role' },
  },
  {
    id: 'TC-ROLE-02',
    title: 'CEO 创建自定义角色',
    description: '角色：CEO。路径：/role → 新增角色 → 填写编码/名称/描述 → 保存。期望：列表出现新角色且类型为"自定义"。',
    module: 'role',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /role', action: 'navigate', to: '/role' },
      { id: 7, desc: '点击"新增角色"', action: 'click', locator: { by: 'role', role: 'button', name: '新增角色' } },
      { id: 8, desc: '输入角色编码', action: 'fill', locator: { by: 'label', value: '角色编码' }, value: 'auto_test_role' },
      { id: 9, desc: '输入角色名称', action: 'fill', locator: { by: 'label', value: '角色名称' }, value: '自动化测试角色' },
      { id: 10, desc: '输入描述', action: 'fill', locator: { by: 'label', value: '描述' }, value: '由 autotest 创建' },
      { id: 11, desc: '点击 Modal 保存', action: 'click', locator: { by: 'catch', value: 'role-modal-save-btn' } },
      { id: 12, desc: '出现"角色创建成功"提示', action: 'assert', check: { type: 'toast_contains', value: '角色创建成功' } },
      { id: 13, desc: '列表出现新角色', action: 'assert', check: { type: 'text_visible', value: '自动化测试角色' } },
    ],
    expect: { result: 'pass', url: '/role' },
  },
  {
    id: 'TC-ROLE-03',
    title: '自定义角色在新建员工时可选',
    description: '角色：HR。路径：调 GET /api/roles。期望：返回列表包含上一步创建的"自动化测试角色"。',
    module: 'role',
    priority: 'P1',
    roles: ['hr'],
    credentials: USERS.hr,
    tags: ['api-only'],
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '调用 GET /api/roles', action: 'api_call', method: 'GET', endpoint: '/api/roles' },
      { id: 7, desc: '人工核对返回包含"自动化测试角色"', action: 'screenshot', label: 'roles-api-response' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-ROLE-04',
    title: '编辑自定义角色描述',
    description: '角色：CEO。路径：/role → 找到"自动化测试角色" → 编辑 → 改描述 → 保存。期望：列表显示新描述。',
    module: 'role',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /role', action: 'navigate', to: '/role' },
      { id: 7, desc: '点击自定义角色"编辑"', action: 'click', locator: { by: 'catch', value: 'role-row-edit-btn-auto_test_role' } },
      { id: 8, desc: '修改描述', action: 'fill', locator: { by: 'label', value: '描述' }, value: '已更新描述文本' },
      { id: 9, desc: '点击保存', action: 'click', locator: { by: 'catch', value: 'role-modal-save-btn' } },
      { id: 10, desc: '出现"角色更新成功"提示', action: 'assert', check: { type: 'toast_contains', value: '角色更新成功' } },
      { id: 11, desc: '列表显示新描述', action: 'assert', check: { type: 'text_visible', value: '已更新描述文本' } },
    ],
    expect: { result: 'pass', url: '/role' },
  },
  {
    id: 'TC-ROLE-05',
    title: '删除未被使用的自定义角色',
    description: '角色：CEO。路径：/role → 找到未被使用的自定义角色 → 删除 → 确认。期望：列表不再显示该角色。',
    module: 'role',
    priority: 'P2',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /role', action: 'navigate', to: '/role' },
      { id: 7, desc: '点击自定义角色"删除"', action: 'click', locator: { by: 'catch', value: 'role-row-delete-btn-auto_test_role' } },
      { id: 8, desc: '确认删除', action: 'click', locator: { by: 'text', value: '确定', exact: true } },
      { id: 9, desc: '出现删除成功提示', action: 'assert', check: { type: 'toast_contains', value: '角色删除成功' } },
    ],
    expect: { result: 'pass', url: '/role' },
  },
  {
    id: 'TC-ROLE-06',
    title: '内置角色不可删除',
    description: '角色：CEO。路径：/role → 系统角色行（如 CEO）。期望：删除按钮不可见（代码 isSystem 时隐藏）。',
    module: 'role',
    priority: 'P0',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /role', action: 'navigate', to: '/role' },
      { id: 7, desc: 'CEO 系统角色行不应有"删除"按钮', action: 'assert', check: { type: 'element_hidden', locator: { by: 'catch', value: 'role-row-delete-btn-ceo' } } },
    ],
    expect: { result: 'pass', url: '/role' },
  },
  {
    id: 'TC-ROLE-07',
    title: '创建自定义角色但名称为空',
    description: '角色：CEO。路径：/role → 新增角色 → 名称留空 → 保存。期望：出现"角色名称不能为空"校验提示。',
    module: 'role',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /role', action: 'navigate', to: '/role' },
      { id: 7, desc: '点击"新增角色"', action: 'click', locator: { by: 'role', role: 'button', name: '新增角色' } },
      { id: 8, desc: '输入角色编码', action: 'fill', locator: { by: 'label', value: '角色编码' }, value: 'empty_name_test' },
      { id: 9, desc: '点击保存（不填名称）', action: 'click', locator: { by: 'catch', value: 'role-modal-save-btn' } },
      { id: 10, desc: '出现必填校验提示', action: 'assert', check: { type: 'text_visible', value: '角色名称不能为空' } },
    ],
    expect: { result: 'pass', url: '/role' },
  },
  {
    id: 'TC-ROLE-08',
    title: '删除仍有员工使用的自定义角色',
    description: '角色：CEO。路径：/role → 找到仍被引用的自定义角色 → 删除 → 确认。期望：出现"不能删除"或 409 错误提示。',
    module: 'role',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /role', action: 'navigate', to: '/role' },
      { id: 7, desc: '点击仍被引用角色"删除"', action: 'click', locator: { by: 'catch', value: 'role-row-delete-btn-inuse' } },
      { id: 8, desc: '确认删除', action: 'click', locator: { by: 'text', value: '确定', exact: true } },
      { id: 9, desc: '出现错误提示', action: 'assert', check: { type: 'toast_contains', value: '不能删除' } },
    ],
    expect: { result: 'pass', url: '/role' },
  },
  {
    id: 'TC-ROLE-09',
    title: 'HR 账号无权访问角色管理',
    description: '角色：HR。路径：登录后直接访问 /role。期望：无"新增角色"按钮，或页面被重定向。',
    module: 'role',
    priority: 'P1',
    roles: ['hr'],
    credentials: USERS.hr,
    tags: ['permission'],
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '访问 /role', action: 'navigate', to: '/role' },
      { id: 7, desc: '不应显示"新增角色"按钮', action: 'assert', check: { type: 'text_absent', value: '新增角色' } },
    ],
    expect: { result: 'pass' },
  },
];

export default cases;
