/**
 * Org module test cases — TC-ORG-01 ~ TC-ORG-18
 * Scope: department tree CRUD, employee CRUD, search, permission checks
 * Note: Employee create/disable UI is absent on /employees; related cases use api_call.
 */
import type { TestCase } from '../../../../tools/autotest/runner/types.js';
import { loginSteps, USERS } from '../_helpers.js';

const cases: TestCase[] = [
  {
    id: 'TC-ORG-01',
    title: '创建部门',
    description: '角色：CEO。路径：/org → 新建部门 → 填写名称 → 保存。期望：部门树出现新部门。',
    module: 'org',
    priority: 'P0',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /org', action: 'navigate', to: '/org' },
      { id: 7, desc: '点击"新建部门"', action: 'click', locator: { by: 'role', role: 'button', name: '+ 新建部门' } },
      { id: 8, desc: '输入部门名称', action: 'fill', locator: { by: 'label', value: '部门名称' }, value: 'autotest-dept-01' },
      { id: 9, desc: '点击 Modal 确定', action: 'click', locator: { by: 'catch', value: 'org-dept-modal-ok' } },
      { id: 10, desc: '树中出现新部门', action: 'assert', check: { type: 'text_visible', value: 'autotest-dept-01' } },
    ],
    expect: { result: 'pass', url: '/org' },
  },
  {
    id: 'TC-ORG-02',
    title: '编辑部门名称',
    description: '角色：CEO。路径：/org → 某部门"编辑" → 修改名称 → 确定。期望：树显示新名称。',
    module: 'org',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /org', action: 'navigate', to: '/org' },
      { id: 7, desc: '点击某部门"编辑"', action: 'click', locator: { by: 'catch', value: 'org-dept-edit-btn-autotest' } },
      { id: 8, desc: '清空名称', action: 'fill', locator: { by: 'label', value: '部门名称' }, value: '' },
      { id: 9, desc: '输入新名称', action: 'fill', locator: { by: 'label', value: '部门名称' }, value: 'autotest-dept-renamed' },
      { id: 10, desc: '点击确定', action: 'click', locator: { by: 'catch', value: 'org-dept-modal-ok' } },
      { id: 11, desc: '树显示新名称', action: 'assert', check: { type: 'text_visible', value: 'autotest-dept-renamed' } },
    ],
    expect: { result: 'pass', url: '/org' },
  },
  {
    id: 'TC-ORG-03',
    title: '通过 API 创建员工',
    description: '角色：HR。路径：调 POST /api/employees（当前 /employees 页无创建 UI）。期望：返回 201，新员工生成员工编号。',
    module: 'org',
    priority: 'P0',
    roles: ['hr'],
    credentials: USERS.hr,
    tags: ['api-only'],
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      {
        id: 6,
        desc: '调用 POST /api/employees',
        action: 'api_call',
        method: 'POST',
        endpoint: '/api/employees',
        body: {
          name: '测试员工01',
          phone: '18800001111',
          gender: 'M',
          entryDate: '2026-04-14',
          departmentId: 1,
          positionId: 1,
          roleCode: 'employee',
        },
      },
      { id: 7, desc: '访问 /employees 搜索新员工', action: 'navigate', to: '/employees' },
      { id: 8, desc: '搜索框输入姓名', action: 'fill', locator: { by: 'placeholder', value: '搜索姓名/部门/岗位' }, value: '测试员工01' },
      { id: 9, desc: '点击搜索', action: 'click', locator: { by: 'role', role: 'button', name: '搜索' } },
      { id: 10, desc: '列表出现新员工', action: 'assert', check: { type: 'text_visible', value: '测试员工01' } },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-ORG-04',
    title: '新员工用初始密码登录成功',
    description: '角色：新员工。路径：退出登录 → 用新创建账号（系统生成用户名/手机号 + 密码 123456）登录。期望：登录成功。',
    module: 'org',
    priority: 'P0',
    roles: ['employee'],
    steps: [
      { id: 1, desc: '打开登录页', action: 'navigate', to: '/login' },
      { id: 2, desc: '输入手机号（新员工）', action: 'fill', locator: { by: 'label', value: '工号 / 手机号' }, value: '18800001111' },
      { id: 3, desc: '输入初始密码', action: 'fill', locator: { by: 'label', value: '登录密码' }, value: '123456' },
      { id: 4, desc: '点击登录', action: 'click', locator: { by: 'catch', value: 'login-form-submit' } },
      { id: 5, desc: '登录成功，跳转工作台', action: 'assert', check: { type: 'text_visible', value: '博渊 OA' } },
      { id: 6, desc: '首次登录应显示初始密码警告', action: 'assert', check: { type: 'text_visible', value: '当前密码为初始密码' } },
    ],
    expect: { result: 'pass', url: '/' },
  },
  {
    id: 'TC-ORG-05',
    title: '通过 API 编辑员工信息',
    description: '角色：HR。路径：PUT /api/employees/{id} 修改手机号。期望：返回 200，查询应为新值。',
    module: 'org',
    priority: 'P1',
    roles: ['hr'],
    credentials: USERS.hr,
    tags: ['api-only'],
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      {
        id: 6,
        desc: '调用 PUT /api/employees/{id}',
        action: 'api_call',
        method: 'PUT',
        endpoint: '/api/employees/999',
        body: { phone: '18899998888' },
      },
      { id: 7, desc: '截图记录 API 响应', action: 'screenshot', label: 'employee-edit-response' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-ORG-06',
    title: '员工列表按姓名搜索',
    description: '角色：HR。路径：/employees → 搜索框输入姓名 → 点击搜索。期望：列表仅展示匹配的员工。',
    module: 'org',
    priority: 'P1',
    roles: ['hr'],
    credentials: USERS.hr,
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '访问 /employees', action: 'navigate', to: '/employees' },
      { id: 7, desc: '输入搜索关键字', action: 'fill', locator: { by: 'placeholder', value: '搜索姓名/部门/岗位' }, value: 'demo' },
      { id: 8, desc: '点击搜索按钮', action: 'click', locator: { by: 'role', role: 'button', name: '搜索' } },
      { id: 9, desc: '列表渲染完成', action: 'wait', ms: 800 },
      { id: 10, desc: '列表应包含关键字', action: 'assert', check: { type: 'text_visible', value: 'demo' } },
    ],
    expect: { result: 'pass', url: '/employees' },
  },
  {
    id: 'TC-ORG-07',
    title: '停用员工账号后无法登录',
    description: '角色：HR + 员工。路径：HR 调 PUT /api/employees/{id}/disable → 员工尝试登录。期望：登录失败。',
    module: 'org',
    priority: 'P1',
    roles: ['hr', 'employee'],
    credentials: USERS.hr,
    tags: ['api-only', 'permission'],
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '调 API 停用员工', action: 'api_call', method: 'PUT', endpoint: '/api/employees/test/disable', body: {} },
      { id: 7, desc: '跳到登录页', action: 'navigate', to: '/login' },
      { id: 8, desc: '用被停用账号尝试登录', action: 'fill', locator: { by: 'label', value: '工号 / 手机号' }, value: 'disabled.test' },
      { id: 9, desc: '输入密码', action: 'fill', locator: { by: 'label', value: '登录密码' }, value: '123456' },
      { id: 10, desc: '点击登录', action: 'click', locator: { by: 'catch', value: 'login-form-submit' } },
      { id: 11, desc: '应停留在 /login', action: 'assert', check: { type: 'url_contains', value: '/login' } },
    ],
    expect: { result: 'pass', url: '/login' },
  },
  {
    id: 'TC-ORG-08',
    title: '重启已停用账号后恢复登录',
    description: '角色：HR + 员工。路径：HR 调 PUT /api/employees/{id}/enable → 员工登录。期望：登录成功。',
    module: 'org',
    priority: 'P1',
    roles: ['hr', 'employee'],
    credentials: USERS.hr,
    tags: ['api-only', 'permission'],
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '调 API 启用员工', action: 'api_call', method: 'PUT', endpoint: '/api/employees/test/enable', body: {} },
      { id: 7, desc: '跳到登录页', action: 'navigate', to: '/login' },
      { id: 8, desc: '用恢复账号登录', action: 'fill', locator: { by: 'label', value: '工号 / 手机号' }, value: 'disabled.test' },
      { id: 9, desc: '输入密码', action: 'fill', locator: { by: 'label', value: '登录密码' }, value: '123456' },
      { id: 10, desc: '点击登录', action: 'click', locator: { by: 'catch', value: 'login-form-submit' } },
      { id: 11, desc: '登录成功', action: 'assert', check: { type: 'text_visible', value: '博渊 OA' } },
    ],
    expect: { result: 'pass', url: '/' },
  },
  {
    id: 'TC-ORG-09',
    title: '组织架构树加载',
    description: '角色：任意登录用户。路径：/org。期望：部门树正常渲染，包含至少一个部门节点。',
    module: 'org',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /org', action: 'navigate', to: '/org' },
      { id: 7, desc: '页面标题"组织架构"可见', action: 'assert', check: { type: 'text_visible', value: '组织架构' } },
      { id: 8, desc: '至少存在一个部门标签（如"人数"）', action: 'assert', check: { type: 'text_visible', value: '人' } },
    ],
    expect: { result: 'pass', url: '/org' },
  },
  {
    id: 'TC-ORG-10',
    title: '员工详情弹窗字段完整',
    description: '角色：HR。路径：/employees → 某行"详情"。期望：弹窗显示姓名/部门/角色/员工类型/入职日期/账号状态。',
    module: 'org',
    priority: 'P1',
    roles: ['hr'],
    credentials: USERS.hr,
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '访问 /employees', action: 'navigate', to: '/employees' },
      { id: 7, desc: '点击某行"详情"', action: 'click', locator: { by: 'catch', value: 'employees-row-detail-btn-1' } },
      { id: 8, desc: '弹窗标题包含"员工详情"', action: 'assert', check: { type: 'text_visible', value: '员工详情' } },
      { id: 9, desc: '姓名字段可见', action: 'assert', check: { type: 'text_visible', value: '姓名' } },
      { id: 10, desc: '部门字段可见', action: 'assert', check: { type: 'text_visible', value: '部门' } },
      { id: 11, desc: '角色字段可见', action: 'assert', check: { type: 'text_visible', value: '角色' } },
    ],
    expect: { result: 'pass', url: '/employees' },
  },
  {
    id: 'TC-ORG-11',
    title: '创建员工缺少姓名失败',
    description: '角色：HR。路径：POST /api/employees 无 name 字段。期望：返回 400 校验错误。',
    module: 'org',
    priority: 'P0',
    roles: ['hr'],
    credentials: USERS.hr,
    tags: ['api-only'],
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      {
        id: 6,
        desc: '调用 POST /api/employees（缺 name）',
        action: 'api_call',
        method: 'POST',
        endpoint: '/api/employees',
        body: { phone: '13000000000', departmentId: 1, positionId: 1 },
      },
      { id: 7, desc: '截图记录响应', action: 'screenshot', label: 'missing-name-response' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-ORG-12',
    title: '创建员工缺少手机号失败',
    description: '角色：HR。路径：POST /api/employees 无 phone。期望：返回 400。',
    module: 'org',
    priority: 'P1',
    roles: ['hr'],
    credentials: USERS.hr,
    tags: ['api-only'],
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      {
        id: 6,
        desc: '调用 POST /api/employees（缺 phone）',
        action: 'api_call',
        method: 'POST',
        endpoint: '/api/employees',
        body: { name: '缺手机号', departmentId: 1, positionId: 1 },
      },
      { id: 7, desc: '截图记录', action: 'screenshot', label: 'missing-phone' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-ORG-13',
    title: '手机号格式不合法',
    description: '角色：HR。路径：POST /api/employees phone=abc123。期望：返回 400，提示格式不合法。',
    module: 'org',
    priority: 'P1',
    roles: ['hr'],
    credentials: USERS.hr,
    tags: ['api-only'],
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      {
        id: 6,
        desc: '调用 POST（非法手机号）',
        action: 'api_call',
        method: 'POST',
        endpoint: '/api/employees',
        body: { name: '非法手机号测试', phone: 'abc123', departmentId: 1, positionId: 1 },
      },
      { id: 7, desc: '截图记录', action: 'screenshot', label: 'invalid-phone' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-ORG-14',
    title: '重复手机号提示冲突',
    description: '角色：HR。路径：POST /api/employees 使用已有手机号。期望：返回 409。',
    module: 'org',
    priority: 'P1',
    roles: ['hr'],
    credentials: USERS.hr,
    tags: ['api-only'],
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      {
        id: 6,
        desc: '首次创建',
        action: 'api_call',
        method: 'POST',
        endpoint: '/api/employees',
        body: { name: '冲突测试 A', phone: '19999000001', departmentId: 1, positionId: 1 },
      },
      {
        id: 7,
        desc: '再次用同手机号创建',
        action: 'api_call',
        method: 'POST',
        endpoint: '/api/employees',
        body: { name: '冲突测试 B', phone: '19999000001', departmentId: 1, positionId: 1 },
      },
      { id: 8, desc: '截图记录 409', action: 'screenshot', label: 'duplicate-phone' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-ORG-15',
    title: '创建员工不选部门失败',
    description: '角色：HR。路径：POST /api/employees 无 departmentId。期望：返回 400。',
    module: 'org',
    priority: 'P1',
    roles: ['hr'],
    credentials: USERS.hr,
    tags: ['api-only'],
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      {
        id: 6,
        desc: '调用 POST（缺部门）',
        action: 'api_call',
        method: 'POST',
        endpoint: '/api/employees',
        body: { name: '无部门测试', phone: '13100000000', positionId: 1 },
      },
      { id: 7, desc: '截图记录', action: 'screenshot', label: 'no-department' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-ORG-16',
    title: '财务账号访问员工创建接口被拒',
    description: '角色：Finance。路径：finance 登录后 POST /api/employees。期望：返回 403。',
    module: 'org',
    priority: 'P1',
    roles: ['finance'],
    credentials: USERS.finance,
    tags: ['api-only', 'permission'],
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      {
        id: 6,
        desc: '财务调用 POST /api/employees',
        action: 'api_call',
        method: 'POST',
        endpoint: '/api/employees',
        body: { name: '越权测试', phone: '13200000000', departmentId: 1, positionId: 1 },
      },
      { id: 7, desc: '截图记录 403', action: 'screenshot', label: 'finance-forbidden' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-ORG-17',
    title: '删除有员工关联的部门失败',
    description: '角色：CEO。路径：/org → 某有员工的部门"删除" → 确认。期望：提示"需无员工且无子部门"。',
    module: 'org',
    priority: 'P2',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /org', action: 'navigate', to: '/org' },
      { id: 7, desc: '点击有员工部门"删除"', action: 'click', locator: { by: 'catch', value: 'org-dept-delete-btn-hr' } },
      { id: 8, desc: '确认删除', action: 'click', locator: { by: 'text', value: '确定', exact: true } },
      { id: 9, desc: '出现无法删除提示', action: 'assert', check: { type: 'toast_contains', value: '无' } },
    ],
    expect: { result: 'pass', url: '/org' },
  },
  {
    id: 'TC-ORG-18',
    title: 'HR 和 CEO 并发编辑同一员工',
    description: '并发场景。路径：parallel HR 和 CEO 同时 PUT /api/employees/{id}。期望：后者覆盖前者或返回冲突提示。',
    module: 'org',
    priority: 'P2',
    roles: ['hr', 'ceo'],
    tags: ['concurrency', 'api-only'],
    steps: [
      {
        id: 1,
        desc: '并行 HR 与 CEO 编辑同一员工',
        action: 'parallel',
        contexts: [
          [
            ...loginSteps(USERS.hr.username, USERS.hr.password, 1),
            { id: 6, desc: 'HR PUT 员工', action: 'api_call', method: 'PUT', endpoint: '/api/employees/1', body: { phone: '13111111111' } },
          ],
          [
            ...loginSteps(USERS.ceo.username, USERS.ceo.password, 1),
            { id: 6, desc: 'CEO PUT 员工', action: 'api_call', method: 'PUT', endpoint: '/api/employees/1', body: { phone: '13222222222' } },
          ],
        ],
      },
    ],
    expect: { result: 'pass' },
  },
];

export default cases;
