/**
 * Auth module test cases — TC-AUTH-01 ~ TC-AUTH-20
 * Scope: login, logout, session, password policy, security edge cases
 */
import type { TestCase } from '../../../../tools/autotest/runner/types.js';
import { loginSteps, USERS } from '../_helpers.js';

const cases: TestCase[] = [
  {
    id: 'TC-AUTH-01',
    title: 'CEO 正确账号密码登录',
    description: '角色：CEO。路径：登录页 → 输入 ceo.demo/123456 → 点击登录。期望：跳转到工作台，顶部显示"博渊 OA"与 CEO 身份。',
    module: 'auth',
    priority: 'P0',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '顶部应显示"博渊 OA"品牌文本', action: 'assert', check: { type: 'text_visible', value: '博渊 OA' } },
    ],
    expect: { result: 'pass', url: '/' },
  },
  {
    id: 'TC-AUTH-02',
    title: 'HR 正确账号密码登录',
    description: '角色：HR。路径：登录页 → 输入 hr.demo/123456 → 登录。期望：进入工作台，侧栏显示"组织架构"。',
    module: 'auth',
    priority: 'P0',
    roles: ['hr'],
    credentials: USERS.hr,
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '侧边栏应显示"组织架构"', action: 'assert', check: { type: 'text_visible', value: '组织架构' } },
    ],
    expect: { result: 'pass', url: '/' },
  },
  {
    id: 'TC-AUTH-03',
    title: '财务正确账号密码登录',
    description: '角色：Finance。路径：登录页 → 输入 finance.demo/123456 → 登录。期望：进入工作台，侧栏显示"薪资结算"。',
    module: 'auth',
    priority: 'P0',
    roles: ['finance'],
    credentials: USERS.finance,
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      { id: 6, desc: '侧边栏应显示"薪资结算"', action: 'assert', check: { type: 'text_visible', value: '薪资结算' } },
    ],
    expect: { result: 'pass', url: '/' },
  },
  {
    id: 'TC-AUTH-04',
    title: '项目经理正确账号密码登录',
    description: '角色：PM。路径：登录页 → 输入 pm.demo/123456 → 登录。期望：进入工作台，侧栏显示"项目管理"。',
    module: 'auth',
    priority: 'P0',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '侧边栏应显示"项目管理"', action: 'assert', check: { type: 'text_visible', value: '项目管理' } },
    ],
    expect: { result: 'pass', url: '/' },
  },
  {
    id: 'TC-AUTH-05',
    title: '员工正确账号密码登录',
    description: '角色：Employee。路径：登录页 → 输入 employee.demo/123456 → 登录。期望：进入工作台，侧栏显示"考勤"。',
    module: 'auth',
    priority: 'P0',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '侧边栏应显示"考勤"', action: 'assert', check: { type: 'text_visible', value: '考勤' } },
    ],
    expect: { result: 'pass', url: '/' },
  },
  {
    id: 'TC-AUTH-06',
    title: '登录后刷新页面保持登录态',
    description: '角色：CEO。路径：登录成功 → 手动刷新页面。期望：仍在 /，token 持久化生效，无需重新登录。',
    module: 'auth',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '重新导航到根路径模拟刷新', action: 'navigate', to: '/' },
      { id: 7, desc: '顶部仍显示品牌栏', action: 'assert', check: { type: 'text_visible', value: '博渊 OA' } },
    ],
    expect: { result: 'pass', url: '/' },
  },
  {
    id: 'TC-AUTH-07',
    title: '点击退出登录跳转到登录页',
    description: '角色：CEO。路径：登录 → 点击头像 → 选择"退出登录"。期望：跳转至 /login。',
    module: 'auth',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '点击顶部头像按钮', action: 'click', locator: { by: 'catch', value: 'header-avatar-btn' } },
      { id: 7, desc: '点击下拉"退出登录"', action: 'click', locator: { by: 'text', value: '退出登录', exact: true } },
      { id: 8, desc: '跳回登录页', action: 'assert', check: { type: 'url_contains', value: '/login' } },
    ],
    expect: { result: 'pass', url: '/login' },
  },
  {
    id: 'TC-AUTH-08',
    title: '退出后访问受保护页跳回登录页',
    description: '角色：CEO。路径：登录 → 退出 → 手动访问 /employees。期望：被重定向回 /login。',
    module: 'auth',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '点击头像', action: 'click', locator: { by: 'catch', value: 'header-avatar-btn' } },
      { id: 7, desc: '点击"退出登录"', action: 'click', locator: { by: 'text', value: '退出登录', exact: true } },
      { id: 8, desc: '尝试访问 /employees', action: 'navigate', to: '/employees' },
      { id: 9, desc: '应被重定向到 /login', action: 'assert', check: { type: 'url_contains', value: '/login' } },
    ],
    expect: { result: 'pass', url: '/login' },
  },
  {
    id: 'TC-AUTH-09',
    title: '错误密码登录失败',
    description: '角色：CEO。路径：登录页 → ceo.demo + 错误密码 → 登录。期望：显示错误提示，停留 /login。',
    module: 'auth',
    priority: 'P0',
    roles: ['ceo'],
    steps: [
      { id: 1, desc: '打开登录页', action: 'navigate', to: '/login' },
      { id: 2, desc: '输入工号', action: 'fill', locator: { by: 'label', value: '工号 / 手机号' }, value: 'ceo.demo' },
      { id: 3, desc: '输入错误密码', action: 'fill', locator: { by: 'label', value: '登录密码' }, value: 'wrong-pwd-xxxxx' },
      { id: 4, desc: '点击登录', action: 'click', locator: { by: 'catch', value: 'login-form-submit' } },
      { id: 5, desc: '应停留在 /login', action: 'assert', check: { type: 'url_contains', value: '/login' } },
      { id: 6, desc: '应出现错误提示', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'login-form-error-alert' } } },
    ],
    expect: { result: 'pass', url: '/login' },
  },
  {
    id: 'TC-AUTH-10',
    title: '不存在的账号登录失败',
    description: '角色：未知。路径：登录页 → 账号 notexist.xxx + 任意密码 → 登录。期望：提示账号不存在或凭证错误，停留 /login。',
    module: 'auth',
    priority: 'P0',
    roles: ['anonymous'],
    steps: [
      { id: 1, desc: '打开登录页', action: 'navigate', to: '/login' },
      { id: 2, desc: '输入不存在账号', action: 'fill', locator: { by: 'label', value: '工号 / 手机号' }, value: 'notexist.xxx' },
      { id: 3, desc: '输入任意密码', action: 'fill', locator: { by: 'label', value: '登录密码' }, value: '123456' },
      { id: 4, desc: '点击登录', action: 'click', locator: { by: 'catch', value: 'login-form-submit' } },
      { id: 5, desc: '应停留在 /login', action: 'assert', check: { type: 'url_contains', value: '/login' } },
      { id: 6, desc: '应出现错误提示', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'login-form-error-alert' } } },
    ],
    expect: { result: 'pass', url: '/login' },
  },
  {
    id: 'TC-AUTH-11',
    title: '账号为空时登录失败',
    description: '角色：未知。路径：登录页 → 账号留空 + 密码有值 → 登录。期望：表单校验报错"请输入工号或手机号"，不发起请求。',
    module: 'auth',
    priority: 'P1',
    roles: ['anonymous'],
    steps: [
      { id: 1, desc: '打开登录页', action: 'navigate', to: '/login' },
      { id: 2, desc: '输入密码', action: 'fill', locator: { by: 'label', value: '登录密码' }, value: '123456' },
      { id: 3, desc: '点击登录', action: 'click', locator: { by: 'catch', value: 'login-form-submit' } },
      { id: 4, desc: '应出现表单校验提示', action: 'assert', check: { type: 'text_visible', value: '请输入工号或手机号' } },
      { id: 5, desc: '应停留在 /login', action: 'assert', check: { type: 'url_contains', value: '/login' } },
    ],
    expect: { result: 'pass', url: '/login' },
  },
  {
    id: 'TC-AUTH-12',
    title: '密码为空时登录失败',
    description: '角色：未知。路径：登录页 → 账号 ceo.demo + 密码留空 → 登录。期望：表单校验报错"请输入密码"，不发起请求。',
    module: 'auth',
    priority: 'P1',
    roles: ['anonymous'],
    steps: [
      { id: 1, desc: '打开登录页', action: 'navigate', to: '/login' },
      { id: 2, desc: '输入账号', action: 'fill', locator: { by: 'label', value: '工号 / 手机号' }, value: 'ceo.demo' },
      { id: 3, desc: '点击登录', action: 'click', locator: { by: 'catch', value: 'login-form-submit' } },
      { id: 4, desc: '应出现密码必填提示', action: 'assert', check: { type: 'text_visible', value: '请输入密码' } },
      { id: 5, desc: '应停留在 /login', action: 'assert', check: { type: 'url_contains', value: '/login' } },
    ],
    expect: { result: 'pass', url: '/login' },
  },
  {
    id: 'TC-AUTH-13',
    title: '账号密码均为空时登录失败',
    description: '角色：未知。路径：登录页 → 两项均留空 → 登录。期望：同时出现两项必填校验。',
    module: 'auth',
    priority: 'P1',
    roles: ['anonymous'],
    steps: [
      { id: 1, desc: '打开登录页', action: 'navigate', to: '/login' },
      { id: 2, desc: '点击登录', action: 'click', locator: { by: 'catch', value: 'login-form-submit' } },
      { id: 3, desc: '账号必填提示', action: 'assert', check: { type: 'text_visible', value: '请输入工号或手机号' } },
      { id: 4, desc: '密码必填提示', action: 'assert', check: { type: 'text_visible', value: '请输入密码' } },
    ],
    expect: { result: 'pass', url: '/login' },
  },
  {
    id: 'TC-AUTH-14',
    title: 'SQL 注入账号不触发 500',
    description: '角色：未知。路径：登录页 → 账号输入 "\' OR 1=1 --" + 任意密码 → 登录。期望：登录失败，服务端无 500 异常。',
    module: 'auth',
    priority: 'P1',
    roles: ['anonymous'],
    tags: ['security'],
    steps: [
      { id: 1, desc: '打开登录页', action: 'navigate', to: '/login' },
      { id: 2, desc: '输入 SQL 注入字符串', action: 'fill', locator: { by: 'label', value: '工号 / 手机号' }, value: "' OR 1=1 --" },
      { id: 3, desc: '输入密码', action: 'fill', locator: { by: 'label', value: '登录密码' }, value: '123456' },
      { id: 4, desc: '点击登录', action: 'click', locator: { by: 'catch', value: 'login-form-submit' } },
      { id: 5, desc: '应停留在 /login', action: 'assert', check: { type: 'url_contains', value: '/login' } },
      { id: 6, desc: '应出现错误提示', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'login-form-error-alert' } } },
    ],
    expect: { result: 'pass', url: '/login' },
  },
  {
    id: 'TC-AUTH-15',
    title: '超长账号不崩溃',
    description: '角色：未知。路径：登录页 → 账号 500 字符 → 登录。期望：登录失败但页面不崩溃，给出错误提示。',
    module: 'auth',
    priority: 'P2',
    roles: ['anonymous'],
    tags: ['edge-case'],
    steps: [
      { id: 1, desc: '打开登录页', action: 'navigate', to: '/login' },
      { id: 2, desc: '输入 500 字符账号', action: 'fill', locator: { by: 'label', value: '工号 / 手机号' }, value: 'a'.repeat(500) },
      { id: 3, desc: '输入密码', action: 'fill', locator: { by: 'label', value: '登录密码' }, value: '123456' },
      { id: 4, desc: '点击登录', action: 'click', locator: { by: 'catch', value: 'login-form-submit' } },
      { id: 5, desc: '应停留在 /login', action: 'assert', check: { type: 'url_contains', value: '/login' } },
    ],
    expect: { result: 'pass', url: '/login' },
  },
  {
    id: 'TC-AUTH-16',
    title: '特殊字符密码不崩溃',
    description: '角色：CEO。路径：登录页 → ceo.demo + 密码 !@#$%^&*() → 登录。期望：登录失败但服务端无 500。',
    module: 'auth',
    priority: 'P2',
    roles: ['ceo'],
    tags: ['edge-case'],
    steps: [
      { id: 1, desc: '打开登录页', action: 'navigate', to: '/login' },
      { id: 2, desc: '输入账号', action: 'fill', locator: { by: 'label', value: '工号 / 手机号' }, value: 'ceo.demo' },
      { id: 3, desc: '输入特殊字符密码', action: 'fill', locator: { by: 'label', value: '登录密码' }, value: '!@#$%^&*()' },
      { id: 4, desc: '点击登录', action: 'click', locator: { by: 'catch', value: 'login-form-submit' } },
      { id: 5, desc: '应停留在 /login', action: 'assert', check: { type: 'url_contains', value: '/login' } },
    ],
    expect: { result: 'pass', url: '/login' },
  },
  {
    id: 'TC-AUTH-17',
    title: 'Token 过期后前端自动跳回登录页',
    description: '角色：CEO。路径：登录后通过 DevAPI 清除 token → 访问 /employees。期望：前端检测无效 token，跳转 /login。',
    module: 'auth',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    tags: ['security', 'session'],
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '清除 session（dev API）', action: 'api_call', method: 'POST', endpoint: '/api/dev/clear-session', body: {} },
      { id: 7, desc: '访问 /employees', action: 'navigate', to: '/employees' },
      { id: 8, desc: '应被重定向到 /login', action: 'assert', check: { type: 'url_contains', value: '/login' } },
    ],
    expect: { result: 'pass', url: '/login' },
  },
  {
    id: 'TC-AUTH-18',
    title: '已停用账号尝试登录失败',
    description: '角色：HR + Employee。路径：HR 登录 → 员工列表停用某测试员工 → 退出 → 以该员工账号尝试登录。期望：提示账号已停用。',
    module: 'auth',
    priority: 'P1',
    roles: ['hr', 'employee'],
    tags: ['permission'],
    steps: [
      ...loginSteps(USERS.hr.username, USERS.hr.password),
      { id: 6, desc: '进入员工列表', action: 'navigate', to: '/employees' },
      { id: 7, desc: '点击某员工"停用"按钮', action: 'click', locator: { by: 'catch', value: 'employees-row-disable-btn-test' } },
      { id: 8, desc: '确认停用', action: 'click', locator: { by: 'catch', value: 'confirm-modal-ok' } },
      { id: 9, desc: '跳转到登录页', action: 'navigate', to: '/login' },
      { id: 10, desc: '以停用账号尝试登录', action: 'fill', locator: { by: 'label', value: '工号 / 手机号' }, value: 'employee.disabled.test' },
      { id: 11, desc: '输入密码', action: 'fill', locator: { by: 'label', value: '登录密码' }, value: '123456' },
      { id: 12, desc: '点击登录', action: 'click', locator: { by: 'catch', value: 'login-form-submit' } },
      { id: 13, desc: '应停留在 /login 并提示', action: 'assert', check: { type: 'url_contains', value: '/login' } },
    ],
    expect: { result: 'pass', url: '/login' },
  },
  {
    id: 'TC-AUTH-19',
    title: '6 个角色同时登录各自独立',
    description: '并发场景。路径：parallel 同时登录 6 个角色。期望：每个 session 独立，互不污染。',
    module: 'auth',
    priority: 'P1',
    roles: ['ceo', 'hr', 'finance', 'pm', 'employee', 'worker'],
    tags: ['concurrency'],
    steps: [
      {
        id: 1,
        desc: '并行登录 6 个角色',
        action: 'parallel',
        contexts: [
          loginSteps(USERS.ceo.username, USERS.ceo.password),
          loginSteps(USERS.hr.username, USERS.hr.password),
          loginSteps(USERS.finance.username, USERS.finance.password),
          loginSteps(USERS.pm.username, USERS.pm.password),
          loginSteps(USERS.employee.username, USERS.employee.password),
          loginSteps(USERS.worker.username, USERS.worker.password),
        ],
      },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-AUTH-20',
    title: '同一账号在两个上下文同时登录',
    description: '并发场景。路径：parallel 让 CEO 账号在两个上下文同时登录。期望：按业务规则处理（后者成功，前者可能失效）。',
    module: 'auth',
    priority: 'P2',
    roles: ['ceo'],
    tags: ['concurrency', 'session'],
    steps: [
      {
        id: 1,
        desc: '并行登录同一 CEO 账号两次',
        action: 'parallel',
        contexts: [
          loginSteps(USERS.ceo.username, USERS.ceo.password),
          loginSteps(USERS.ceo.username, USERS.ceo.password),
        ],
      },
    ],
    expect: { result: 'pass' },
  },
];

export default cases;
