/**
 * Project module test cases — TC-PROJ-01 ~ TC-PROJ-15
 * Scope: project CRUD, milestones, progress, status transitions, permissions, concurrency
 */
import type { TestCase } from '../../../../tools/autotest/runner/types.js';
import { loginSteps, USERS } from '../_helpers.js';

const cases: TestCase[] = [
  {
    id: 'TC-PROJ-01',
    title: 'CEO 创建新项目',
    description: '角色：CEO。路径：/projects → 新建项目 → 填写名称/开始日期 → 保存。期望：列表出现新项目，项目号格式 PRJ-YYYYMM-XXXX。',
    module: 'project',
    priority: 'P0',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /projects', action: 'navigate', to: '/projects' },
      { id: 7, desc: '点击"新建项目"', action: 'click', locator: { by: 'role', role: 'button', name: '+ 新建项目' } },
      { id: 8, desc: '输入项目名称', action: 'fill', locator: { by: 'label', value: '项目名称' }, value: 'autotest 项目 01' },
      { id: 9, desc: '点击 Modal 确定', action: 'click', locator: { by: 'catch', value: 'project-create-modal-ok' } },
      { id: 10, desc: '列表出现新项目', action: 'assert', check: { type: 'text_visible', value: 'autotest 项目 01' } },
      { id: 11, desc: '项目号包含 PRJ-', action: 'assert', check: { type: 'text_visible', value: 'PRJ-' } },
    ],
    expect: { result: 'pass', url: '/projects' },
  },
  {
    id: 'TC-PROJ-02',
    title: '添加里程碑',
    description: '角色：PM。路径：/projects/{id} → 里程碑 tab → 添加 → 填写名称和目标日期。期望：列表出现新里程碑。',
    module: 'project',
    priority: 'P1',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问某项目详情', action: 'navigate', to: '/projects/1' },
      { id: 7, desc: '点击里程碑 tab', action: 'click', locator: { by: 'role', role: 'tab', name: '里程碑' } },
      { id: 8, desc: '点击"新增里程碑"', action: 'click', locator: { by: 'catch', value: 'project-milestone-add-btn' } },
      { id: 9, desc: '输入名称', action: 'fill', locator: { by: 'label', value: '里程碑名称' }, value: '一期开工' },
      { id: 10, desc: '保存', action: 'click', locator: { by: 'catch', value: 'project-milestone-save-btn' } },
      { id: 11, desc: '列表出现新里程碑', action: 'assert', check: { type: 'text_visible', value: '一期开工' } },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-PROJ-03',
    title: '更新项目进度',
    description: '角色：PM。路径：/projects/{id} → 进度 → 输入百分比 → 保存。期望：进度显示新百分比。',
    module: 'project',
    priority: 'P1',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问某项目', action: 'navigate', to: '/projects/1' },
      { id: 7, desc: '点击进度 tab', action: 'click', locator: { by: 'role', role: 'tab', name: '进度' } },
      { id: 8, desc: '点击"更新进度"', action: 'click', locator: { by: 'catch', value: 'project-progress-update-btn' } },
      { id: 9, desc: '输入进度 35', action: 'fill', locator: { by: 'label', value: '完成百分比' }, value: '35' },
      { id: 10, desc: '保存', action: 'click', locator: { by: 'catch', value: 'project-progress-save-btn' } },
      { id: 11, desc: '进度显示 35%', action: 'assert', check: { type: 'text_visible', value: '35' } },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-PROJ-04',
    title: 'CEO 项目列表查看全部',
    description: '角色：CEO。路径：/projects。期望：列表显示所有项目。',
    module: 'project',
    priority: 'P0',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /projects', action: 'navigate', to: '/projects' },
      { id: 7, desc: '列表容器可见', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'projects-list-table' } } },
      { id: 8, desc: '标题"项目管理"可见', action: 'assert', check: { type: 'text_visible', value: '项目' } },
    ],
    expect: { result: 'pass', url: '/projects' },
  },
  {
    id: 'TC-PROJ-05',
    title: 'PM 仅看到自己负责的项目',
    description: '角色：PM。路径：/projects。期望：列表只显示 PM 为负责人的项目（依业务规则）。',
    module: 'project',
    priority: 'P1',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问 /projects', action: 'navigate', to: '/projects' },
      { id: 7, desc: '列表至少有 1 个项目行', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'projects-list-table' } } },
      { id: 8, desc: '截图人工核对仅本人项目', action: 'screenshot', label: 'pm-filtered-projects' },
    ],
    expect: { result: 'pass', url: '/projects' },
  },
  {
    id: 'TC-PROJ-06',
    title: '项目状态流转 ACTIVE→COMPLETED',
    description: '角色：PM。路径：/projects/{id} → 关闭 → 确认。期望：状态变 COMPLETED。',
    module: 'project',
    priority: 'P1',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问 /projects', action: 'navigate', to: '/projects' },
      { id: 7, desc: '点击某项目"关闭"', action: 'click', locator: { by: 'catch', value: 'project-row-close-btn-1' } },
      { id: 8, desc: '确认', action: 'click', locator: { by: 'text', value: '确定', exact: true } },
      { id: 9, desc: '出现成功提示', action: 'assert', check: { type: 'toast_contains', value: '关闭' } },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-PROJ-07',
    title: '财务录入项目实体成本',
    description: '角色：Finance。路径：/projects/{id} → 成本 tab → 录入金额。期望：显示新成本。',
    module: 'project',
    priority: 'P1',
    roles: ['finance'],
    credentials: USERS.finance,
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      { id: 6, desc: '访问某项目', action: 'navigate', to: '/projects/1' },
      { id: 7, desc: '点击成本 tab', action: 'click', locator: { by: 'role', role: 'tab', name: '成本' } },
      { id: 8, desc: '点击"新增成本"', action: 'click', locator: { by: 'catch', value: 'project-cost-add-btn' } },
      { id: 9, desc: '输入金额', action: 'fill', locator: { by: 'label', value: '金额' }, value: '50000' },
      { id: 10, desc: '保存', action: 'click', locator: { by: 'catch', value: 'project-cost-save-btn' } },
      { id: 11, desc: '列表显示 50000', action: 'assert', check: { type: 'text_visible', value: '50000' } },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-PROJ-08',
    title: '工作台活跃项目卡片跳转',
    description: '角色：CEO。路径：工作台 → 点击"活跃项目"卡片。期望：跳转到 /projects。',
    module: 'project',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '点击活跃项目卡片', action: 'click', locator: { by: 'catch', value: 'workbench-card-active-projects' } },
      { id: 7, desc: '跳转 /projects', action: 'assert', check: { type: 'url_contains', value: '/projects' } },
    ],
    expect: { result: 'pass', url: '/projects' },
  },
  {
    id: 'TC-PROJ-09',
    title: '项目详情页展示成员列表',
    description: '角色：PM。路径：/projects/{id} → 成员 tab。期望：显示成员列表。',
    module: 'project',
    priority: 'P1',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问某项目', action: 'navigate', to: '/projects/1' },
      { id: 7, desc: '点击成员 tab', action: 'click', locator: { by: 'role', role: 'tab', name: '成员' } },
      { id: 8, desc: '成员列表可见', action: 'assert', check: { type: 'element_visible', locator: { by: 'catch', value: 'project-members-list' } } },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-PROJ-10',
    title: '为项目添加劳工成员并分配工长',
    description: '角色：PM。路径：/projects/{id} 成员 → 添加劳工 → 分配工长第二角色。期望：列表显示该劳工和其角色。',
    module: 'project',
    priority: 'P2',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问某项目', action: 'navigate', to: '/projects/1' },
      { id: 7, desc: '成员 tab', action: 'click', locator: { by: 'role', role: 'tab', name: '成员' } },
      { id: 8, desc: '点击"添加成员"', action: 'click', locator: { by: 'catch', value: 'project-members-add-btn' } },
      { id: 9, desc: '选择劳工', action: 'click', locator: { by: 'catch', value: 'project-members-user-select' } },
      { id: 10, desc: '选择"工长"角色', action: 'click', locator: { by: 'text', value: '工长', exact: true } },
      { id: 11, desc: '保存', action: 'click', locator: { by: 'catch', value: 'project-members-save-btn' } },
      { id: 12, desc: '列表出现该成员与工长角色', action: 'assert', check: { type: 'text_visible', value: '工长' } },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-PROJ-11',
    title: '项目名称为空创建失败',
    description: '角色：CEO。路径：/projects → 新建 → 名称空 → 保存。期望：表单校验报错。',
    module: 'project',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /projects', action: 'navigate', to: '/projects' },
      { id: 7, desc: '点击"新建项目"', action: 'click', locator: { by: 'role', role: 'button', name: '+ 新建项目' } },
      { id: 8, desc: '直接点确定', action: 'click', locator: { by: 'catch', value: 'project-create-modal-ok' } },
      { id: 9, desc: '出现"请输入"校验', action: 'assert', check: { type: 'text_visible', value: '请' } },
    ],
    expect: { result: 'pass', url: '/projects' },
  },
  {
    id: 'TC-PROJ-12',
    title: '里程碑目标日期早于今天',
    description: '角色：PM。路径：/projects/{id} 里程碑 → 添加 → 过去日期。期望：警告或校验提示。',
    module: 'project',
    priority: 'P2',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问某项目', action: 'navigate', to: '/projects/1' },
      { id: 7, desc: '里程碑 tab', action: 'click', locator: { by: 'role', role: 'tab', name: '里程碑' } },
      { id: 8, desc: '添加', action: 'click', locator: { by: 'catch', value: 'project-milestone-add-btn' } },
      { id: 9, desc: '输入名称', action: 'fill', locator: { by: 'label', value: '里程碑名称' }, value: '历史日期测试' },
      { id: 10, desc: '截图，手动选过去日期', action: 'screenshot', label: 'past-date-milestone' },
      { id: 11, desc: '保存', action: 'click', locator: { by: 'catch', value: 'project-milestone-save-btn' } },
      { id: 12, desc: '应出现警告或校验提示', action: 'screenshot', label: 'past-date-response' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-PROJ-13',
    title: 'COMPLETED 项目不可变回 ACTIVE',
    description: '角色：PM。路径：对已关闭项目点击"重开"。期望：按钮不可见或操作被拒。',
    module: 'project',
    priority: 'P1',
    roles: ['pm'],
    credentials: USERS.pm,
    steps: [
      ...loginSteps(USERS.pm.username, USERS.pm.password),
      { id: 6, desc: '访问 /projects', action: 'navigate', to: '/projects' },
      { id: 7, desc: '点击某已关闭项目"重开"', action: 'click', locator: { by: 'catch', value: 'project-row-reopen-btn-1' } },
      { id: 8, desc: '人工核对是否被拒绝', action: 'screenshot', label: 'reopen-response' },
    ],
    expect: { result: 'pass' },
  },
  {
    id: 'TC-PROJ-14',
    title: '财务尝试创建项目被拒',
    description: '角色：Finance。路径：/projects。期望：无"新建项目"按钮或 API 返回 403。',
    module: 'project',
    priority: 'P1',
    roles: ['finance'],
    credentials: USERS.finance,
    tags: ['permission'],
    steps: [
      ...loginSteps(USERS.finance.username, USERS.finance.password),
      { id: 6, desc: '访问 /projects', action: 'navigate', to: '/projects' },
      { id: 7, desc: '不应显示"+ 新建项目"按钮', action: 'assert', check: { type: 'text_absent', value: '+ 新建项目' } },
    ],
    expect: { result: 'pass', url: '/projects' },
  },
  {
    id: 'TC-PROJ-15',
    title: 'PM 和 CEO 并发修改同一项目进度',
    description: '并发。路径：parallel PM 与 CEO 同时 PUT progress。期望：只有最终一次生效，或提示冲突。',
    module: 'project',
    priority: 'P2',
    roles: ['pm', 'ceo'],
    tags: ['concurrency'],
    steps: [
      {
        id: 1,
        desc: '并发更新项目进度',
        action: 'parallel',
        contexts: [
          [
            ...loginSteps(USERS.pm.username, USERS.pm.password, 1),
            { id: 6, desc: 'PM 更新进度 60', action: 'api_call', method: 'POST', endpoint: '/api/projects/1/progress', body: { percent: 60 } },
          ],
          [
            ...loginSteps(USERS.ceo.username, USERS.ceo.password, 1),
            { id: 6, desc: 'CEO 更新进度 80', action: 'api_call', method: 'POST', endpoint: '/api/projects/1/progress', body: { percent: 80 } },
          ],
        ],
      },
    ],
    expect: { result: 'pass' },
  },
];

export default cases;
