/**
 * Profile module test cases — TC-PROF-01 ~ TC-PROF-11
 * Scope: personal profile view, change password flow, default password banner
 */
import type { TestCase } from '../../../../tools/autotest/runner/types.js';
import { loginSteps, USERS } from '../_helpers.js';

const cases: TestCase[] = [
  {
    id: 'TC-PROF-01',
    title: 'CEO 个人信息页展示正确字段',
    description: '角色：CEO。路径：登录 → 头像菜单 → 个人信息。期望：显示姓名、工号、角色、部门字段非空。',
    module: 'profile',
    priority: 'P0',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问 /me', action: 'navigate', to: '/me' },
      { id: 7, desc: '页面标题显示"个人信息"', action: 'assert', check: { type: 'text_visible', value: '个人信息' } },
      { id: 8, desc: '姓名字段可见', action: 'assert', check: { type: 'text_visible', value: '姓名' } },
      { id: 9, desc: '工号字段可见', action: 'assert', check: { type: 'text_visible', value: '工号' } },
      { id: 10, desc: '角色字段可见', action: 'assert', check: { type: 'text_visible', value: '角色' } },
    ],
    expect: { result: 'pass', url: '/me' },
  },
  {
    id: 'TC-PROF-02',
    title: '员工个人信息页展示正确字段',
    description: '角色：Employee。路径：登录 → /me。期望：姓名、工号、手机号、角色字段非空。',
    module: 'profile',
    priority: 'P0',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /me', action: 'navigate', to: '/me' },
      { id: 7, desc: '页面标题显示"个人信息"', action: 'assert', check: { type: 'text_visible', value: '个人信息' } },
      { id: 8, desc: '手机号字段可见', action: 'assert', check: { type: 'text_visible', value: '手机号' } },
    ],
    expect: { result: 'pass', url: '/me' },
  },
  {
    id: 'TC-PROF-03',
    title: 'CEO 修改密码后新密码可登录',
    description: '角色：CEO。路径：/me/password → 输入旧密码 + 新密码 + 确认 → 保存 → 重新登录。期望：新密码登录成功。',
    module: 'profile',
    priority: 'P0',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问修改密码页', action: 'navigate', to: '/me/password' },
      { id: 7, desc: '输入当前密码', action: 'fill', locator: { by: 'label', value: '当前密码' }, value: '123456' },
      { id: 8, desc: '输入新密码', action: 'fill', locator: { by: 'label', value: '新密码' }, value: '654321Aa' },
      { id: 9, desc: '输入确认新密码', action: 'fill', locator: { by: 'label', value: '确认新密码' }, value: '654321Aa' },
      { id: 10, desc: '点击保存', action: 'click', locator: { by: 'catch', value: 'me-password-submit' } },
      { id: 11, desc: '出现"密码修改成功"提示', action: 'assert', check: { type: 'toast_contains', value: '密码修改成功' } },
      { id: 12, desc: '退回登录页', action: 'navigate', to: '/login' },
      { id: 13, desc: '用新密码登录', action: 'fill', locator: { by: 'label', value: '工号 / 手机号' }, value: USERS.ceo.username },
      { id: 14, desc: '输入新密码', action: 'fill', locator: { by: 'label', value: '登录密码' }, value: '654321Aa' },
      { id: 15, desc: '点击登录', action: 'click', locator: { by: 'catch', value: 'login-form-submit' } },
      { id: 16, desc: '跳转到工作台', action: 'assert', check: { type: 'text_visible', value: '博渊 OA' } },
    ],
    expect: { result: 'pass', url: '/' },
  },
  {
    id: 'TC-PROF-04',
    title: '修改密码后旧密码失效',
    description: '角色：Employee。路径：/me/password 改密码 → 退出 → 用旧密码登录。期望：旧密码登录失败。',
    module: 'profile',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问修改密码页', action: 'navigate', to: '/me/password' },
      { id: 7, desc: '输入当前密码', action: 'fill', locator: { by: 'label', value: '当前密码' }, value: '123456' },
      { id: 8, desc: '输入新密码', action: 'fill', locator: { by: 'label', value: '新密码' }, value: 'NewPass123' },
      { id: 9, desc: '输入确认新密码', action: 'fill', locator: { by: 'label', value: '确认新密码' }, value: 'NewPass123' },
      { id: 10, desc: '点击保存', action: 'click', locator: { by: 'catch', value: 'me-password-submit' } },
      { id: 11, desc: '退回登录页', action: 'navigate', to: '/login' },
      { id: 12, desc: '用旧密码尝试登录', action: 'fill', locator: { by: 'label', value: '工号 / 手机号' }, value: USERS.employee.username },
      { id: 13, desc: '输入旧密码', action: 'fill', locator: { by: 'label', value: '登录密码' }, value: '123456' },
      { id: 14, desc: '点击登录', action: 'click', locator: { by: 'catch', value: 'login-form-submit' } },
      { id: 15, desc: '应停留在 /login', action: 'assert', check: { type: 'url_contains', value: '/login' } },
    ],
    expect: { result: 'pass', url: '/login' },
  },
  {
    id: 'TC-PROF-05',
    title: '初始密码登录时工作台显示警告横幅',
    description: '角色：Employee（需确保密码为 123456）。路径：登录 → /me。期望：页面顶部出现"当前密码为初始密码"警告 alert。',
    module: 'profile',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /me', action: 'navigate', to: '/me' },
      { id: 7, desc: '应显示初始密码警告横幅', action: 'assert', check: { type: 'text_visible', value: '当前密码为初始密码' } },
    ],
    expect: { result: 'pass', url: '/me' },
  },
  {
    id: 'TC-PROF-06',
    title: '点击警告横幅"立即修改"跳转到修改密码页',
    description: '角色：Employee。路径：/me → 点击警告横幅中的"立即修改"按钮。期望：跳转到 /me/password。',
    module: 'profile',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问 /me', action: 'navigate', to: '/me' },
      { id: 7, desc: '点击"立即修改"按钮', action: 'click', locator: { by: 'role', role: 'button', name: '立即修改' } },
      { id: 8, desc: '跳转到修改密码页', action: 'assert', check: { type: 'url_contains', value: '/me/password' } },
    ],
    expect: { result: 'pass', url: '/me/password' },
  },
  {
    id: 'TC-PROF-07',
    title: '修改密码成功后警告横幅消失',
    description: '角色：Employee。路径：/me/password 改密码 → 返回 /me。期望：警告横幅不再显示。',
    module: 'profile',
    priority: 'P1',
    roles: ['employee'],
    credentials: USERS.employee,
    steps: [
      ...loginSteps(USERS.employee.username, USERS.employee.password),
      { id: 6, desc: '访问修改密码页', action: 'navigate', to: '/me/password' },
      { id: 7, desc: '输入当前密码', action: 'fill', locator: { by: 'label', value: '当前密码' }, value: '123456' },
      { id: 8, desc: '输入新密码', action: 'fill', locator: { by: 'label', value: '新密码' }, value: 'NewPass999' },
      { id: 9, desc: '输入确认新密码', action: 'fill', locator: { by: 'label', value: '确认新密码' }, value: 'NewPass999' },
      { id: 10, desc: '点击保存', action: 'click', locator: { by: 'catch', value: 'me-password-submit' } },
      { id: 11, desc: '等待跳转回 /me', action: 'wait', ms: 2000 },
      { id: 12, desc: '访问 /me', action: 'navigate', to: '/me' },
      { id: 13, desc: '警告横幅不再显示', action: 'assert', check: { type: 'text_absent', value: '当前密码为初始密码' } },
    ],
    expect: { result: 'pass', url: '/me' },
  },
  {
    id: 'TC-PROF-08',
    title: '旧密码错误时修改失败',
    description: '角色：CEO。路径：/me/password 输入错误旧密码 → 保存。期望：出现"原密码错误"或类似错误提示，密码未修改。',
    module: 'profile',
    priority: 'P0',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问修改密码页', action: 'navigate', to: '/me/password' },
      { id: 7, desc: '输入错误旧密码', action: 'fill', locator: { by: 'label', value: '当前密码' }, value: 'wrong-old-pwd' },
      { id: 8, desc: '输入新密码', action: 'fill', locator: { by: 'label', value: '新密码' }, value: 'NewPass888' },
      { id: 9, desc: '输入确认新密码', action: 'fill', locator: { by: 'label', value: '确认新密码' }, value: 'NewPass888' },
      { id: 10, desc: '点击保存', action: 'click', locator: { by: 'catch', value: 'me-password-submit' } },
      { id: 11, desc: '出现错误提示', action: 'assert', check: { type: 'text_visible', value: '密码' } },
      { id: 12, desc: '应停留在修改密码页', action: 'assert', check: { type: 'url_contains', value: '/me/password' } },
    ],
    expect: { result: 'pass', url: '/me/password' },
  },
  {
    id: 'TC-PROF-09',
    title: '两次新密码不一致时校验失败',
    description: '角色：CEO。路径：/me/password 新密码与确认不一致 → 保存。期望：表单校验提示"两次输入的密码不一致"，不提交。',
    module: 'profile',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问修改密码页', action: 'navigate', to: '/me/password' },
      { id: 7, desc: '输入当前密码', action: 'fill', locator: { by: 'label', value: '当前密码' }, value: '123456' },
      { id: 8, desc: '输入新密码 A', action: 'fill', locator: { by: 'label', value: '新密码' }, value: 'PassA999' },
      { id: 9, desc: '输入确认密码 B', action: 'fill', locator: { by: 'label', value: '确认新密码' }, value: 'PassB000' },
      { id: 10, desc: '点击保存', action: 'click', locator: { by: 'catch', value: 'me-password-submit' } },
      { id: 11, desc: '出现不一致校验提示', action: 'assert', check: { type: 'text_visible', value: '两次输入的密码不一致' } },
    ],
    expect: { result: 'pass', url: '/me/password' },
  },
  {
    id: 'TC-PROF-10',
    title: '新密码过短时校验失败',
    description: '角色：CEO。路径：/me/password 新密码"123"（短于 6 位）→ 保存。期望：出现"密码长度至少 6 位"校验提示。',
    module: 'profile',
    priority: 'P1',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问修改密码页', action: 'navigate', to: '/me/password' },
      { id: 7, desc: '输入当前密码', action: 'fill', locator: { by: 'label', value: '当前密码' }, value: '123456' },
      { id: 8, desc: '输入过短新密码', action: 'fill', locator: { by: 'label', value: '新密码' }, value: '123' },
      { id: 9, desc: '输入确认新密码', action: 'fill', locator: { by: 'label', value: '确认新密码' }, value: '123' },
      { id: 10, desc: '点击保存', action: 'click', locator: { by: 'catch', value: 'me-password-submit' } },
      { id: 11, desc: '出现密码长度校验提示', action: 'assert', check: { type: 'text_visible', value: '密码长度至少6位' } },
    ],
    expect: { result: 'pass', url: '/me/password' },
  },
  {
    id: 'TC-PROF-11',
    title: '新密码与旧密码相同时的处理',
    description: '角色：CEO。路径：/me/password 新密码与旧密码相同 → 保存。期望：若后端有此校验则提示"不能与旧密码相同"，否则保存成功但没有业务意义（均视为通过此用例）。',
    module: 'profile',
    priority: 'P2',
    roles: ['ceo'],
    credentials: USERS.ceo,
    steps: [
      ...loginSteps(USERS.ceo.username, USERS.ceo.password),
      { id: 6, desc: '访问修改密码页', action: 'navigate', to: '/me/password' },
      { id: 7, desc: '输入当前密码', action: 'fill', locator: { by: 'label', value: '当前密码' }, value: '123456' },
      { id: 8, desc: '新密码与旧密码相同', action: 'fill', locator: { by: 'label', value: '新密码' }, value: '123456' },
      { id: 9, desc: '确认密码', action: 'fill', locator: { by: 'label', value: '确认新密码' }, value: '123456' },
      { id: 10, desc: '点击保存', action: 'click', locator: { by: 'catch', value: 'me-password-submit' } },
      { id: 11, desc: '截图记录反应（人工判定）', action: 'screenshot', label: 'same-password-response' },
    ],
    expect: { result: 'pass' },
  },
];

export default cases;
